### ISSUE TITLE
How to insert data into header and/or footer

### ISSUE THREAD

**Issue by datenwort** [guigrpa/docx-templates#1]
Hey everybody,

actually I try to add data into a header section in word. Is this possible with this library and if so, how to do this?

Thanks.

**Comment by guigrpa** [comment]
Hi, and thanks for the issue.

No, that's currently not supported. Docx-templates only processes `document.xml` for the time being. I'll leave this issue open and try to address it asap. Any idea on which other `*.xml` files carry user-visible contents (not just styles)?

**Comment by guigrpa** [comment]
Well, "asap" came sooner than expected. Just released [version 2.1.0](https://github.com/guigrpa/docx-templates/blob/master/CHANGELOG.md)!

@datenwort Could you please have a look and confirm that we can close this issue?

**Comment by datenwort** [comment]
Fantastic service. It works as expected in my test case.

**Comment by guigrpa** [comment]
Thanks for the confirmation
