### ISSUE TITLE
HTML Strange Encoding of Spanish HTML Characters

### ISSUE THREAD

**Issue by flaglerkid** [guigrpa/docx-templates#100]
Hello, 

I have been using your amazing package to create word documents from an Angular 7/Electron 4/ Node 12.13.1/docx-templater 3.1.1. I have been able to successfully produce both English and Chinese language versions and generally love the package.

However, today when I tried to produce a Spanish Language version the HTML converter is incorrectly displaying the accented characters as Ã³, Ã¡, Ã±, etc.

All content comes from JSON objects compiled prior to being passed to this package.

Here is the line in JSON:
`"es": "<p>Una evaluación anual de riesgos de seguridad es, por lejos, la práctica de seguridad más valiosa que una instalación puede implementar. Existen muchos marcos de evaluación de riesgos efectivos disponibles, como el Análisis modal de fallos y efectos (Failure Modes and Effects Analysis, FMEA), la Evaluación de amenazas, activos y vulnerabilidades operacionalmente críticas (Operationally Critical Threat, Asset and Vulnerability Evaluation, OCTAVE) o el Margo de gestión de riesgos (Risk Management Framework, RMF) del Instituto Nacional de Estándares y Tecnología (National Institute of Standards and Technology, NIST). Independientemente del marco que se utilice, cada evaluación de riesgos debe tener los siguientes pasos:</p><ol><li>Definir los activos</li><li>Definir los riesgos para esos activos</li><li>Definir las amenazas a esos riesgos</li><li>Definir el impacto de esas amenazas</li><li>Definir la probabilidad de esas amenazas</li><li>Definir las mitigaciones a esas amenazas</li><li>Definir el impacto residual y la probabilidad después de esas mitigaciones</li></ol>",
`

Here is what it looks like outputted to Word:
![image](https://user-images.githubusercontent.com/37170952/75926432-8b82b500-5e38-11ea-8c91-80a3f718cc4c.png)

I have tried to use Javascript escape notation and HTML Unicode escape notation, but neither is actually interpreted by the HTML to OOXML interpreter so no improvement. Any ideas on how I can get the accented characters to display properly?

**Comment by guigrpa** [comment]
Is the original content (the JSON object) encoded as UTF8? I guess you can try converting it among different encodings (including at least UTF8 and Latin1) to see which one works...

**Comment by flaglerkid** [comment]
Hi Guigrpa, thanks for responding. It is encoded in UTF8, but so is the Chinese language version. I ingest all the content into a javascript memory object prior to passing that object on to the docx-templater service so I am not sure that changing the source encoding will matter. Happy to try.

I just tried to [convert to ASCII](https://onlineutf8tools.com/convert-utf8-to-ascii) to see what would happen and it is giving the same encoding on the accented characters. 
![image](https://user-images.githubusercontent.com/37170952/75928356-39439300-5e3c-11ea-846a-412963ccc827.png)

Why would the HTML to OOXML encoder be converting from UTF8 to ASCII?

**Comment by guigrpa** [comment]
Hmm, the online tool you have used doesn’t give information on the particular encoding, only that it’s ASCII but not the ASCII “flavour”. I would try to convert using a text editor which is specific for developing... example with VS Code: https://stackoverflow.com/questions/30082741/change-the-encoding-of-a-file-in-visual-studio-code

**Comment by flaglerkid** [comment]
Changing the encoding definitely has an effect on the output, but I am just guessing right now. Is there any way to identify the most compatible encoding for the conversion?

I tried ISO8859-15/3/1:
![image](https://user-images.githubusercontent.com/37170952/75934223-ea045f00-5e49-11ea-9a85-9c12a9a68f63.png)

Windows 1250:
![image](https://user-images.githubusercontent.com/37170952/75934413-68f99780-5e4a-11ea-977c-775dd36f8420.png)

UTF-16 BE:
![image](https://user-images.githubusercontent.com/37170952/75934537-c68de400-5e4a-11ea-9a69-90c39990894f.png)

**Comment by flaglerkid** [comment]
I worked with the output and created a workaround that I thought I would share here in case anyone else is having the problem.

Ã³ = ó
Ã¡ = á
Ã© = é
Ã± = ñ
Ãº = ú
Â = non-breaking space
Ã­ = í
Ã = í

I wrote a down and dirty macro that replaces the output in the final document:

`Public Sub CleanSpanishLetters()
    Dim vDirectory As String
    Dim oDoc As Document
    vDirectory = "PATH_TO_FOLDER"
    
    vFile = Dir(vDirectory & "*.*")
    
    Application.ScreenUpdating = False
    Application.Visible = False
    
    
    Do While vFile <> ""
        Set oDoc = Documents.Open(FileName:=vDirectory & vFile)
        
        Selection.Find.ClearFormatting
        Selection.Find.Replacement.ClearFormatting
        With Selection.Find
            .Text = "Ã³"
            .MatchCase = True
            .Replacement.Text = "ó"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll

        With Selection.Find
            .Text = "Ã¡"
            .MatchCase = True
            .Replacement.Text = "á"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll
        
        With Selection.Find
            .Text = "Ã©"
            .MatchCase = True
            .Replacement.Text = "é"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll
        
        With Selection.Find
            .Text = "Ã±"
            .MatchCase = True
            .Replacement.Text = "ñ"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll
        
        With Selection.Find
            .Text = "Ãº"
            .MatchCase = True
            .Replacement.Text = "ú"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll
        
        With Selection.Find
            .Text = "Â"
            .MatchCase = True
            .Replacement.Text = ""
        End With
        Selection.Find.Execute Replace:=wdReplaceAll
        
        With Selection.Find
            .Text = "Ã­"
            .MatchCase = True
            .Replacement.Text = "í"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll
        
        With Selection.Find
            .Text = "Ã"
            .MatchCase = True
            .Replacement.Text = "í"
        End With
        Selection.Find.Execute Replace:=wdReplaceAll

        ' save and close the current document
        ActiveDocument.Close wdSaveChanges
        vFile = Dir()
    Loop
    
    Application.ScreenUpdating = True
    Application.Visible = True
End Sub
`

**Comment by jjhbw** [comment]
I think i may have found the cause/solution. Bear with me here, because i'm not an expert at all in the docx spec or how it treats embedded HTML.

See the repro template and test case i made in d4614ea3ada787e90b615a6936956808c551e8f1.

it seems that wrapping your HTML literal in a `<body>` tag solves the encoding issues. Like this:

```typescript
+++HTML `
<body>
  ${text}
</body>
`+++
```

Word (2016) then seems to render it correctly.

In short, I don't think this is a bug in docx-templates, but maybe a bit of a footgun inherent to embedding HTML chunks that we can document or avoid.

**Comment by flaglerkid** [comment]
Thank you! I would never have thought to do that.

**Comment by Alebat** [comment]
Hi everyone, I still have this problem after using the body thag and also the head with the meta-encoding=UTF-8 tag. The only way I found is to encode the JSON input file into an ASCII encoding, for me the ISO 8859-15 encoding which is for Central Europe.
The problem is, as I can see, that the html is saved in the docx with a fixed ASCII encoding despite the input being UTF-8. In fact, I can find the HTML templates in the docx file encoded as ASCII. Another way would be using HTML entities for encoding non ASCII characters contained in the input JSON, like, for example, &agrave; &ograve; &egrave: etc.
