### ISSUE TITLE
Question: Modifying template syntax

### ISSUE THREAD

**Issue by RahulRathodGitHub** [guigrpa/docx-templates#101]
Hello, Thanks for the amazing work! I wanted to change the way I write the template for the FOR LOOP. Or generally want to modify the syntax of how we write the templates.

For instance, instead of:
![image](https://user-images.githubusercontent.com/42928792/76578259-30c61900-651c-11ea-907c-27d6736da147.png)

If I wanted:
![image](https://user-images.githubusercontent.com/42928792/76578280-43405280-651c-11ea-8cfb-29b4e97c6b69.png)

Which part of the source code should I modify?

I have been stepping into the flow of code for a while, especially in processTemplate.js but can not pinpoint what part should I modify.  Apologies if this isn't the correct place to ask this.

**Comment by jjhbw** [comment]
You can take a look at these functions: https://github.com/guigrpa/docx-templates/blob/f29675efdcb4f017aab6aac9166ee91dc6dd9a63/src/processTemplate.ts#L551-L652

I'm not super familiar with this part of the codebase, so I would be interested to hear what you come up with!
