### ISSUE TITLE
4.0.0-rc.0 is not published on NPM

### ISSUE THREAD

**Issue by mathe42** [guigrpa/docx-templates#109]
Why is v4.0.0-rc.0 not published on NPM? It would help to test it out with my current project :D

Also I will remove @types/dox-templates on release of v4 see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43864

**Comment by jjhbw** [comment]
Its just a release candidate at this point. @guigrpa has to do the actual publishing. We'll create a `v4.0.0` when that happens. We're working on getting github actions set up to smoothen this out.

Sorry for the confusion! And thanks for keeping track of the type definitions package.

**Comment by guigrpa** [comment]
It's just been published as v4.0.0. Thanks to @jjhbw for all the hard work!

**Comment by vdechef** [comment]
Thanks you guys for this ! 👍
