### ISSUE TITLE
[bug] IMAGE tag cause exception on header 

### ISSUE THREAD

**Issue by arelg** [guigrpa/docx-templates#113]
when adding IMAGE to the header it will result a **Cannot read property 'async' of null**
at zip.js **zipGetText**

the issue is caused because processImages function is getting 
**header1.xml** as documentComponent resulting it to try and use **word/_rels/header1.xml.rels**
that doesn't exist inside the docx

![Screen Shot 2020-04-23 at 11 40 15](https://user-images.githubusercontent.com/34028785/80078307-661c4880-8557-11ea-902d-cd0b6190101a.png)

**Comment by jjhbw** [comment]
Scratch that, i found it myself. Again, thanks for the report. I'll fix it ASAP.

**Comment by arelg** [comment]
great ! just was about so send a zip with the example. thanks for the quick response. amazing project!!!

**Comment by jjhbw** [comment]
Should be fixed in the next release (4.1.0) which has been finalised today. We will tag it and publish it to npm shortly. Please reopen if you still encounter this problem.

**Comment by arelg** [comment]
awesome work great lib, thank you
