### ISSUE TITLE
Google docs and Microsoft online Word HTML tag and literalXml issues

### ISSUE THREAD

**Issue by arelg** [guigrpa/docx-templates#115]
**Google Docs -**
1. HTML block is blank after docx generation.(maybe they dont support altchunk?)
2. LiteralXml is ignored

**Microsoft online Word**
1. LiteralXml blocks display only on the view mode, toggling edit mode ignores the LiteralXml
2. HTML blocks display on view mode but prevents the file from opening on edit mode(this is known by Microsoft as they popup a message to edit file with those objects on desktop word)

im more interested on LiteralXml as i tried to play with it using examples from  
[http://officeopenxml.com/WPsampleDoc.php] but managed only to corrupt the docx file.

**example of LiteralXml that i managed to make work**  
`
||<w:rPr><w:b w:val="true"/><w:u w:val="single"/><w:color w:val="ff0000"/></w:rPr>||my cool text
`  
am i missing something while using this markup?

**Comment by jjhbw** [comment]
Thanks for the report! 

So if i understand it correctly, html and literalXML blocks inserted using the docx-templates library do not render in Online Word and google docs?

Does it work on your local machine's Word?

Can you show me a short repro example of the docx-templates code you used to generate the problematic document?

**Comment by arelg** [comment]
on local machine Word it's working.
i found out that the xml that was generated by the lib is different from what word is creating(text that was edited from word). 
attached diff xml files 
[diff_files.zip](https://github.com/guigrpa/docx-templates/files/4524452/diff_files.zip)

```javascript
const res = await createReport({
    additionalJsContext: {
        logo: async url => {
            const bitmap = fs.readFileSync('newlogo.png');
            const img = new Buffer(bitmap);
            return { width: 3.38, height: 1.47, data: img, extension: '.png' };                        
        }            
      },        
        cmdDelimiter: ['[',']'],
        template,            
        data: {                           
            orngb:`||
            <w:rPr>
                <w:b w:val="true"/>
                <w:u w:val="single"/>
                <w:color w:val="ff0000"/>
                <w:t>Introduction</w:t>
            </w:rPr>||`,                  
        }        
      })
``

**Comment by vdechef** [comment]
Regarding HTML, it can only work for Microsoft Word, because it uses `AltChunks` functionnality.  
As far as I know, no other docx editor support AltChunks.

An AltChunk is linked to an html file inside the zip archive, and when the docx is opened for the first time the HTML is parsed by Word and converted to literal XML.

I found no better way to implement this without having to recreate an html-to-docx parser ... :(

**Comment by arelg** [comment]
thanks @vdechef just wanted to make sure i'm not missing something. any ideas regarding the literalXml? and thanks @jjhbw for your responsiveness ^^

**Comment by jjhbw** [comment]
Thanks for clarifying @vdechef ! I'm not a .docx expert so this kind of knowledge is very welcome.

So as I understand it this is not something we can fix, as this is a detail of how Word viewers work with literal HTML and XML in the document. Be sure to correct me if i'm misunderstanding here.

I'll close this issue to keep the tracker clean, but feel free to continue the discussion (I may learn a thing or two).

**Comment by arelg** [comment]
@jjhbw so HTML will work only for desktop Word, but i'm missing something with the literal XML. can someone provide an example as the documentation have a simplistic use cases. when i use the <w:p> tag it corrupts the docx file that is generated

**Comment by vdechef** [comment]
I didn't know that we could insert Word xml parts. This feature is not documented, but it seems promising to solve some formatting problems I encounter in my application.  

If someone could provide some insight, I would appreciate :) Otherwise I will dig in the code and try to understand.

**Comment by jjhbw** [comment]
Ddocx-templates can AFAIK insert literal XML, but that's about all I know. I didn't write the relevant code so I don't really have the know-how to properly document it. Would be great if you could contribute!

**Comment by arelg** [comment]
sure @jjhbw ^^ this project rocks ! I'll investigate bit more about the literal XML.
@vdechef so far as i pointed out above i managed to use this:
```javascript 
const res = await createReport({
        cmdDelimiter: ['[',']'],
        template,            
        data: {                           
            myparam:`||
            <w:rPr>
                <w:b w:val="true"/>
                <w:u w:val="single"/>
                <w:color w:val="ff0000"/>
                <w:t>Introduction</w:t>
            </w:rPr>||`,                  
        }        
      })
``    
this will inject the docx a bold underline with colour "Introduction" text.
works on word desktop(view/edit) and word online(view).
the issue is that docx-templates not creating the xml block correctly as seen on the attached zip 
[diff_files.zip](https://github.com/guigrpa/docx-templates/files/4527946/diff_files.zip)
if this issue will be resolved i think it will make it work on every docx editor

[ooXML documentation]: http://officeopenxml.com/WPsampleDoc.php
