### ISSUE TITLE
Unable to generate word document from template. Can't read the data of 'the loaded zip file'

### ISSUE THREAD

**Issue by shyamcharit03** [guigrpa/docx-templates#119]
I'm following the simple steps to replace a value in the attached word document. However, I get the below error. Also see the code snippet below. Please let me know what could be causing this issue. I'm running this code on Node version 10.18.0 on Ubuntu 18.04. I'm on the latest version of docx-templates 4.1.0

**Error**
(node:1728) UnhandledPromiseRejectionWarning: Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?

**Code snippet**

const transactionTemplate = fs.readFileSync(
    __dirname + '/../../data/transactionTemplates/DATE.docx'
  );

  const transactionDocument = await docxTemplate.createReport({
    transactionTemplate,
    data: {
      date: '1/1/2020',
    },
  });

[DATE.docx](https://github.com/guigrpa/docx-templates/files/4543527/DATE.docx)

**Comment by mathe42** [comment]
You sould add the template to the template Option:

```js
const transactionTemplate = fs.readFileSync(
  __dirname + '/../../data/transactionTemplates/DATE.docx'
);

const transactionDocument = await docxTemplate.createReport({
  template: transactionTemplate,
  data: {
    date: '1/1/2020',
  },
});
```

**Comment by jjhbw** [comment]
```javascript
const transactionTemplate = fs.readFileSync(
    __dirname + '/../../data/transactionTemplates/DATE.docx'
);

const transactionDocument = await docxTemplate.createReport({
    template: transactionTemplate, <---- !
    data: {
        date: '1/1/2020',
    },
});
```

See above. You seem to be using ES6 object property value shorthand to initialise the object. Note that `transactionTemplate` should map to the `template` property.

Feel free to reopen if this doesn't work for you.

**Comment by shyamcharit03** [comment]
Thanks guys.. I swear I was staring at it and could not spot the difference.
