### ISSUE TITLE
Allow passing zip compression parameters as options.

### ISSUE THREAD

**Issue by icegnome** [guigrpa/docx-templates#12]
Hey, first and foremost... I really appreciate this code.   

I am going to be pushing my files over an api, and attaching them in a database.  Adding a small amount of compression is extremely helpful for file size.  By adding the compression options on jszip, the size difference is immense.   Could that be easily added to the docx-templates options for pass through?

zip.js line 30 

     _jszip2.default.prototype.toFile = function toFile() {
      // compression and compressionOptions added
       return this.generateAsync({ type: 'uint8array',  compression: "DEFLATE", compressionOptions : 
      {level:1} });
     };

As another size idea, I pulled the white space out of the document.xml,  which generally saves a good amount of space as well.  I understand why you'd want the whitespace in development.  But perhaps again a way to extend with an option..... or my quick and dirty current code.

mainBrowser.js line 172

          case 43:
            DEBUG && log.debug('Writing report...');
         // LINE ADDED            
            reportXml = reportXml.replace(/\s+/g, ' ').trim();
            zip.setText(templatePath + '/document.xml', reportXml);

With these two additives my test file went from a 67kb template generating a 1301kb file.  To a 67kb template generating a 87kb file.

**Comment by vdechef** [comment]
IMO, compression could be interesting.
Can Word and LibreOffice read compressed docx files ?
What would be the compensation regarding performances ?

**Comment by icegnome** [comment]
A compression of 1 seems to duplicate the file size of a natural word docx file.  Word opens the files fine.  
I didn't seem to have any performance change for zipping or the regex.

**Comment by vdechef** [comment]
I tested this, and it greatly reduces the output size. I will create a PR with the code.

**Comment by guigrpa** [comment]
I hadn't noticed that #8 (which replaced unzip+archiver with jszip) increased that much the size of the generated documents. I support adding compression to the jszip options, but as a default (no need for a user option).

On the other hand, I would leave "space removal" for another PR, which would need to be done with care (and might not be so useful with jszip compression after all).

**Comment by vdechef** [comment]
Yep, sorry for that. I did not checked file size when changing compression lib :(
I just created the PR #13. Let me know if something is wrong.

**Comment by guigrpa** [comment]
Shipped in v2.3.2. Thanks for the issue and the PR!

**Comment by icegnome** [comment]
Thanks guys!
