### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by JacobReynolds** [guigrpa/docx-templates#120]
Does the browser support include IE11? I've been trying to get it to work through a mix of polyfills but have yet to successfully generate a template.

**Comment by jjhbw** [comment]
Can you show me what you have tried already?
What goes wrong exactly?
One thing to try may be to disable sandboxing mode.

I'll check our compiler setup in the meantime.

**Comment by JacobReynolds** [comment]
Hey, thanks for the quick reply. I think it was a result of a couple issues on my side. I needed to upgrade to the latest version of docx-templates and also set up some polyfills in the webpack/babel configs.

The issue I'm running into now is in this code example
```
+++HTML `
<body>
  <h1>${$film.title}</h1>
  <h3>${$film.releaseDate.slice(0, 4)}</h3>
  <p>
    <strong style="color: red;">This paragraph should be red and strong</strong>
  </p>
</body>
`+++
```
IE doesn't support the template literal syntax here, but that's not really a problem with this repo. May be worth noting in the docs though, I'll probably just go with direct string concatenation.

Either way, thanks and I love the repo!

**Comment by jjhbw** [comment]
Ah, thanks for clarifying. Yes that makes a lot of sense. Template syntax won't be transpiled, so cannot be polyfilled! Didn't even think of that. I'll add it to the docs.

**Comment by jjhbw** [comment]
eb0c8cf313c9c555d5da5416a2225b176164f869
