### ISSUE TITLE
Cannot populate docx template in node.js 

### ISSUE THREAD

**Issue by glatorre** [guigrpa/docx-templates#122]
Hello, I cannot create a docx from a template. I don't receive any errors, but the output file is corrupted (16 bytes). I've tried on both OSX and Linux.

This is my simple template (**template.docx**):

```
+++=name+++
+++=surname+++
```

And this is my node.js code:
```
const createReport = require ('docx-templates').default;
const fs = require('fs');
 
const template = fs.readFileSync('./template.docx');
 
const buffer = createReport({
  template,
  data: {
    name:"foo",
    surname: "foo2"
  },
});
 
fs.writeFileSync('./report.docx', buffer);
```

Is this my fault?
Thank you in advance

**Comment by jjhbw** [comment]
Note that the createReport function returns a promise. In your example you are writing a promise to a file. It seems this is my fault: the example in the README is missing an `await` statement! I'm sorry for that. Thanks for the report!

See the fix here: https://github.com/guigrpa/docx-templates/commit/336a66b15a63437880823ced34709686366855bc

Be sure to reopen this issue if it doesn't solve the problem!

**Comment by glatorre** [comment]
Thank you. It was the problem.

**Comment by Mahmoud-A-Noor** [comment]
> +++=name+++

thank you man that's just what i wanted
