### ISSUE TITLE
Access data by bracket notation

### ISSUE THREAD

**Issue by lcyin** [guigrpa/docx-templates#124]
Thanks for the awesome package!
Is there any way to access data by bracket notation?
Thanks!

**Comment by jjhbw** [comment]
Can you elaborate? How would this look?

**Comment by lcyin** [comment]
Let say I have a data object like this:
![Screenshot 2020-05-19 at 3 50 54 PM](https://user-images.githubusercontent.com/39464039/82299921-b49ef480-99e8-11ea-90c6-91a9fe34bd95.png)

Can I access project name by bracket notation?
`+++INS project['project name'] +++ `

**Comment by lcyin** [comment]
I found that it access through use template string (` `) to wrap a property key.

For the above example,
Original I passed property key by wrap by single quote (' '). Instead of that, wrap property key by template string (``) can solve the problem. 

It is a minor mistake, sorry to bother you. I will close it.

Thanks for your help though!
