### ISSUE TITLE
Error: If you return image `data`, make sure you return an extension as well! when trying to embed image

### ISSUE THREAD

**Issue by ku3b1k0** [guigrpa/docx-templates#126]
I am trying to execute the examples inside the example-node directory on a Windows 10 Enterprise/Node version 12.13 and keep getting the error message below. What am I doing wrong ?
example-node>node index.js images-path.docx images-test.docx
Error: Error executing command: IMAGE ({ width: 3, height: 3, path: './sample.png' }) If you return image `data`, make sure you return an extension as well!

**Comment by jjhbw** [comment]
Ah, thanks i forgot to update that example.

Note that the library no longer supports reading directly from the filesystem, as we have taken this out of the library's scope.

See the example code in the readme on how to use images in the report.

I'll update the examples soon.

**Comment by ku3b1k0** [comment]
Many thanks for the prompt update and Many thanks for this wonderful package,
