### ISSUE TITLE
JS within HTML tag

### ISSUE THREAD

**Issue by KAVA-Leigh** [guigrpa/docx-templates#129]
Hi guys,

Just wanting to confirm that JS (script tags) are not permitted within the HTML tag..?

We were hoping to use the HTML tag to insert images & this works fine for a static URL for the src value, however, as we need the image to be dynamically set - we had tried to use JS to set this, with no luck.

The reason we wanted to use the HTML rather than IMAGE tag is because we didn't want to have to set the image size params in the backend service & the HTML tag can obviously have height/width set for each HTML tag independently.

That was the first issue, the second would obviously be whether we could then access a variable set in EXEC outside of the HTML tag as well, as the URL would be in the data object & would want to be able to access that within the JS of the HTML tag (if that makes sense).

If you are able to please clarify, that would be much appreciated.

Thanks

**Comment by jjhbw** [comment]
I don't know the docx spec by heart, but I highly doubt it. As I understand it, this would require Word to have a javascript engine to run the script with...

In case you want to investigate further, the part of the OpenXML (docx) specification related to embedding HTML is called `altChunk`, as far as I know.

Feel free to reopen if this doesn't answer your question.
