### ISSUE TITLE
"document.xml could not be found" for SharePoint files

### ISSUE THREAD

**Issue by speedpro** [guigrpa/docx-templates#131]
I''m trying to use this for documents hosted on SharePoint, and I keep getting a "document.xml not found" error when I try to run createReport(). I seem to recall that sharepoint uses a `document2.xml` instead of `document.xml`

I did a search & replace inside /node_modules for this module ("document.xml" -> "document2.xml") and everything seemed to work after that. 

I'm not sure how much work it would be to update the source code to support this format, but I'd be happy to submit a PR if you could point me in the right direction for a dev setup.

**Comment by speedpro** [comment]
Also, refer to https://github.com/open-xml-templating/docxtemplater/issues/366 where I encountered the same issue

**Comment by jjhbw** [comment]
Thanks for this report! Reading the issue you linked, it appears this is also the case for Word Online / Office 365 files. Obviously we want to be able to support those, so i'll classify this as a bug.

**Comment by jjhbw** [comment]
@speedpro do you have an example of such a file? I'm trying to get access to the relevant MS software, but until then it would be useful to have an example.

**Comment by jjhbw** [comment]
@speedpro never mind, found an example in the issue you linked. 🙏

**Comment by jjhbw** [comment]
@speedpro This should do it. I'll incorporate this fix in the next point release.
