### ISSUE TITLE
When use noSandbox = true, function in EXEC will be undefined

### ISSUE THREAD

**Issue by saknarak** [guigrpa/docx-templates#134]
When use ```noSandbox: true```, ```EXEC``` user defined function cannot use in ```INS```

```
UnhandledPromiseRejectionWarning: Error: Error executing command: INS test(name) test is not defined
```

step to reproduce
test.docx
```
+++EXEC
function test(x) {
  return x.toUpperCase()
}
+++
+++INS test(name)+++
```
```
createReport({
  template: fs.readFileSync('./test.docx'),
  data: {
    name: 'myname',
  },
  noSandbox: true, // <- this cause error
}).then(buff => {
  fs.writeFileSync('./out3.docx', buff)
})
```

**Comment by jjhbw** [comment]
Thanks for reporting! I'll take a look.

**Comment by saknarak** [comment]
I found workaround,

```
function test() {}; // work in sandbox only
var test = function() {}; // work in sandbox only
test = () => {}; // work both
test = function() {}; // work both
let test = function() {}; // not work both
```

**Comment by jjhbw** [comment]
Great find. I was just playing around with this bug and it seems this issue arises from differences in scoping behaviour between the sandbox and non-sandbox execution modes.

I also think that symbols/functions from the script's global scope are reachable from your template if you set `noSandbox: true`. This may also be undesirable/surprising behaviour.

I didn't write the sandboxing-related code, but i'll dig around a bit and see what I can do.

**Comment by jjhbw** [comment]
I have studied the issue a bit, and I think it is indeed a scoping issue.

In sandbox mode (`noSandbox: false`), each code snippet is run in a context that is managed by the [require('vm')](https://nodejs.org/api/vm.html#vm_vm_executing_javascript) API. This API treats the context object the way you'd expect as the global script context: each `EXEC` snippet in a template declares variables in the JS VM's global scope by default, as if they were part of the same `.js` file.

When disabling sandbox mode (`noSandbox: true`), the scoping behaviour is slightly different. As you can see [here](https://github.com/guigrpa/docx-templates/blob/1468c258063d58e3c5d9ed3544a01e7c7ad40e46/src/jsSandbox.ts#L47-L61), disabling the sandbox will execute each EXEC snippet's code in a `with(this){...}` context, where `this` is the 'context' object. This 'context' object is re-used between `EXEC` snippets. The critical difference of this approach is that _you are not assigning to the global scope by default_. The only way to assign to the global scope is to assign explicitly to the context object. This is simplified by the `with(context){}` wrapper: all _global_ declarations are actually added as properties to the `context` object. Locally scoped declarations are not.

An example:

This declares the `test` function in the `context` object
```js
test = () => {};
```
While the below example only declares `test` in the local scope of the snippet, meaning it gets garbage collected after the snippet has executed.
```js
function test() {};
```

I can't think of a fix that won't involve a significant amount of hacking, so I think it is better to just document this behaviour for now.

**Comment by jjhbw** [comment]
I will close this for now. Be sure to reopen or shoot a PR if you think of a reliable way to harmonise the two scoping behaviours!

Thanks for your help 👍

**Comment by saknarak** [comment]
It's OK to use either ```test = function() {};``` or ```test => () => {};``` in ```noSandbox: true``` mode

Thank you for your effort.
