### ISSUE TITLE
.xlsx support?

### ISSUE THREAD

**Issue by bkoltai** [guigrpa/docx-templates#136]
This is an awesome library and has been a huge help in my app, thank you!

Have you thought about whether this approach would work in .xlsx files as well? I'd love to be able to build custom reports using the GQL data fetching approach and template strings in the cells.

Even if you have a sense of what parts would be the same and which would need to change

**Comment by jjhbw** [comment]
While an interesting idea in general, i would not recommend extending this library to work with XLSX. 

From the top of my head, i expect the amount of code that could be reused to be minimal, as the xlsx file structure is quite different. Most of this library's code is actually about navigating the docx file structure.

Hence, for the sake of not introducing scope creep and associated maintenance burden in the current library I dont think this is a good fit...

I think the best approach would be to make a separate library.

I have had good results with Exceljs in the past for reading and writing Excel files. If you are able to parse the xlsx template with Exceljs, i guess you should be able to execute any JS code snippets that you find in the cells. There are probably some snakes on the road before you can build a full fledged xlsx templating solution from that, but it's a start.

Your feature suggestion is appreciated, though!
