### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by tomspeed22** [guigrpa/docx-templates#137]
Could you please provide an example changing text color using If condition ? 
Thanks appreciate the help

**Comment by jjhbw** [comment]
You need to embed HTML snippets for that. See the example in the README:

```
+++HTML `
<body>
  <p>
    <strong style="color: red;">This paragraph should be red and strong</strong>
  </p>
</body>
`+++
```

Note that the actual HTML in this snippet is a javascript string literal. This snippet gets executed as javascript and inserted as HTML into the document. You can also build up an HTML string in your code and inject it in a `+++HTML yourstring+++` command. You can simply use javascript if statements or wrap the whole snippet in an IF statement, as shown in the examples.

Alternatively, you can try something like this:

```
+++HTML `
<body>
  <p>
    <strong style="color: ${desiredColor};">This paragraph should be colored and strong</strong>
  </p>
</body>
`+++
```

Feel free to reopen if this doesn't answer your question.

**Comment by vdechef** [comment]
Beware of a limitation when changing colors through HTML : 
- the style set as default for font when usiong HTML is `Normal (Web)`
- this style won't be applied if a `style` attribute is set in the html tag

@jjhbw I would recommend to define charset before `<body>` tag, to avoid problems with text encoding : 
```html
+++HTML `
<meta charset="UTF-8">
<body>
  <p>
    <strong>This paragraph should be strong</strong>
  </p>
</body>
`+++
```

**Comment by jjhbw** [comment]
Thanks for pitching in! The <meta> tag sounds like a good idea. Did you run in to issues with text encoding in the wild?

I'll add `<meta charset="UTF-8">` to the relevant examples.

**Comment by vdechef** [comment]
Yes, I had trouble with french characters like à / é /è and was forced to add this `<meta>` tag to solve it.

**Comment by jjhbw** [comment]
👍 
Added it to the examples/docs in 31bc3c4b9d9e98fb44cb3dbb9ffddb2054839f2e.
