### ISSUE TITLE
Cannot replace data in window 10

### ISSUE THREAD

**Issue by dnguyenlearning** [guigrpa/docx-templates#141]
I ran this function on window 10. 
local ENV working fine but when I packaged and run it as application. I saw this message: " Can't find end of central directory : is this a zip file ?"

can anyone help me out?

**Comment by jjhbw** [comment]
Please provide a way for us to reproduce your issue. This is not enough information.

**Comment by dnguyenlearning** [comment]
oh sorry. the problem is about my code. fs.writefileSync in nodejs not override in window. I thought that message is error but it is not. Thank for kindly response.

**Comment by jjhbw** [comment]
Good to hear that you found a solution! Thanks for the update.
