### ISSUE TITLE
Error when use docx-templates in typescript

### ISSUE THREAD

**Issue by tuan-cs** [guigrpa/docx-templates#142]
I have a issue when use docx-templates with typescript. When I build code it show 

`
node_modules/docx-templates/lib/main.d.ts(3,8): error TS1259: Module '"/tmp/node_modules/jszip/index"' can only be default-imported using the 'esModuleInterop' flag
src/service/FollowupService.ts(7,8): error TS1259: Module '"/tmp/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag
`
I don't want to use esModuleInterop: true because it will break other code. Can you help me?

**Comment by jjhbw** [comment]
Can you provide me with a minimal example project so I can see if I fixed this correctly? I'm not sure exactly what I should change for this library to work with your compiler configuration. Let me know if you have any pointers.

**Comment by tuan-cs** [comment]
I have fixed it. Because I config wrong tsconfig file

**Comment by jjhbw** [comment]
Great! Thanks for taking the time to close the issue 👍
