### ISSUE TITLE
Call function within FOR

### ISSUE THREAD

**Issue by KAVA-Leigh** [guigrpa/docx-templates#147]
Hi guys,

First off, I didn't see anything in the change log to indicate that this was an issue that has been addressed, but this is occurring on v3.1.1, just in case that is the issue here..

The issue I am facing is calling a function within a FOR loop (in a table);

| Title | Value |
| --- | --- |
| `{#FOR Item in Data.ItemData#}` |  |
| `{#$Item.displayName#}` | `{#formatVal($Item.value)#}` |
| `{#END-FOR Item#}` | |

It doesn't matter whether I pass `$Item` or a hardcoded value in that function argument, I get the `Invalid Command Syntax` error. I am using many functions (outside of FOR) elsewhere in this template & they work fine.

Any thoughts on this one please?

Thanks :)

**Comment by jjhbw** [comment]
Out of interest, any particular reason you're not running 4.3? A lot of 'backend'/robustness improvements were integrated in the meantime that may have squashed this bug silently.

**Comment by KAVA-Leigh** [comment]
We hadn't yet updated on this project, as it is in production & was a backlog item.

I can proceed to update, but was just wondering if this was something that you might have been aware of being resolved at some point.

Thanks for getting back to me so quickly.

**Comment by jjhbw** [comment]
I recommend that you upgrade to 4.3. The code has been polished quite a bit since 3.1.1, and the breaking changes should be manageable (let me know if you run into anything).

Can you send me a template docx and code example to reproduce this issue? I'll quickly check if this issue still exists in 4.3.

**Comment by KAVA-Leigh** [comment]
Ran testing on 4.3 & confirm that this is now working, amazing!
Thanks for offering to test this & the suggestion that this might be addressed in more recent releases :)

**Comment by jjhbw** [comment]
Good to hear! Don't hesitate to make an issue if you run into any other problems.
