### ISSUE TITLE
Is there a way to iterate over object

### ISSUE THREAD

**Issue by fprijate** [guigrpa/docx-templates#149]
**===FOR x IN arr** 
iterates over an array arr.
Is there a way to iterate over object properties of some object ?

**Comment by jjhbw** [comment]
How about something like:

```
+++FOR name IN Object.values(companies)+++
+++INS $name+++
+++END-FOR name+++
```

Does this answer your question?

**Comment by jjhbw** [comment]
Closing to keep the issue tracker lean. Feel free to reopen if this doesn't answer your question.
