### ISSUE TITLE
listCommands() Error: Can't read the data of 'the loaded zip file'

### ISSUE THREAD

**Issue by Arend-dev** [guigrpa/docx-templates#151]
Hi there,

I always get the following error when trying to use listCommands:

"node_modules\jszip\lib\utils.js:454
                new Error("Can't read the data of '" + name + "'. Is it " +
                ^

Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?   
    at C:\xampp\htdocs\Nodejs\Test DOCX Assembly\node_modules\jszip\lib\utils.js:454:17                               etc) ? "

Here ist the code I used:

```
const listCommands = require("docx-templates").default;
const fs = require("fs");

const template_buffer = fs.readFileSync("myTemplate.docx");

try {
  listCommands(template_buffer, ["{#", "#}"]).then((commands) =>
    console.log(commands)
  );
} catch (errors) {
  if (Array.isArray(errors)) {
    // An array of errors likely caused by bad commands in the template.
    console.log(errors);
  } else {
    // Not an array of template errors, indicating something more serious.
    throw errors;
  }
}
```
Maybe I am overlooking something. Would be great if anybody could help on this.

**Comment by jjhbw** [comment]
You're importing the `default` export of the `docx-templates` module, which refers to `createReport`. Your `listCommands` symbol now points at `createReport`.

Try importing the function by name instead:

```javascript
const { listCommands } = require("docx-templates");
```

I have added the correct import statement to the examples in the README to prevent future confusion (557fb5b476a24ca4f59e82363f12eefbb028f58c).

Unrelated note: you are not catching any errors that may occur in `listCommands` in this snippet, as you aren't `await`-ing the Promise. Alternatively, you can add a `.catch()` handler after `.then()`.

Feel free to reopen if this doesn't answer your question.

**Comment by Arend-dev** [comment]
Awesome thank you so much!
