### ISSUE TITLE
Application web page freeze while creating large docx file.

### ISSUE THREAD

**Issue by NikunjPansuriya** [guigrpa/docx-templates#153]
I am creating docx file with large array data(e.g. array[2182]), once createReport method invoked whole web page is freeze during docx creation, page is responsive after document downloaded. it took 1hours to generate full document with approx 95 - 100 pages till 1 hours whole web page is freeze.
Creating table using below syntax where data is array of objects with size 2182.
col1 | col2 | col3 | col4
-- | -- | -- | --
+++FOR obj IN data+++ |   |   |  
+++*col1+++ | +++*col2+++ | +++*col3+++ | +++*col4+++
+++END-FOR 						obj+++ |   |   |

**Comment by jjhbw** [comment]
Try turning off the sandbox mode for bigger data.

**Comment by vdechef** [comment]
You can also generate the document inside a webworker to avoid freezing the page.

**Comment by jjhbw** [comment]
Thats also a great idea. Webpages tend to freeze when the js event loop is busy with CPU-intensive work. 

Note that a 100+ page Word file is going to be quite a bit of work to parse and create regardless.

Feel free to reopen if the above suggestions dont bring the runtime down significantly. Disabling the sandbox should be low-hanging fruit performance-wise.
