### ISSUE TITLE
Docx Merge with +++HTML

### ISSUE THREAD

**Issue by benhaddoureda** [guigrpa/docx-templates#155]
Hello i have used your docx-template to generate one file with data and for now it's working greate, since i have rich text fileds and it works greate with the +++HTML.

Now i need to generate one file but with multiple data, 
for example i have generated a word file with data from one projet x.
now i need generate data for two projects, x and y, and i need them to be one word file.
Till now i have done that with using DocxMerger, but the problem is in the HTML fields or parts of the word template, i have duplicated data in the y project, to make it more simple data for the x project is good on the first page of the word file, but in the second page where i have data for project y, the part where we use +++HTML is bugged since it shows me the same data as the first page, means project x.

to be more clarified, i'm using this with salesforce : 
```javascript
data = response.getReturnValue();
const j = data.length;
  for (let i = 0; i < j; i++) {
                            console.log("this is i : " + i);
                           helper.createBlob(i,data,component,event, helper);
                        }
                         helper.waitUntil(() => helper.reportGlob[j - 1], () => {
                          var docx = new DocxMerger({}, helper.reportGlob);
                           docx.save('blob', function (data) {
                               saveAs(data, "output.docx");
                           });
```

**Comment by jjhbw** [comment]
So if i understand you correctly, the individual files you're trying to merge are correctly rendered by `docx-templates`?
In that case, you're best off asking the maintainers of `DocxMerger` first.

I have no idea what `DocxMerger` is or how it works, i'm afraid. If it doesn't play nice with embedded HTML, you'll likely get weird results. 

Feel free to reopen if it turns out to be an issue with `docx-templates`.

**Comment by vdechef** [comment]
@benhaddoureda when using +++HTML, the html content is embedded as .html files in the docx archive. These html files are transformed in docx xml tags the first time the docx file is opened. So when DocxMerge runs on your docx file, the html files have not yet been imported, and I guess that DocxMerger does not handle html files in docx archive.

**Comment by benhaddoureda** [comment]
thank you all for your response.
indeed im using +++HTML as this in a cell
+++HTML `<head><meta charset="utf-8"> <style> li{mso-margin-top-alt:0pt;mso-margin-bottom-alt:0pt;text-indent:-8pt} ul{margin-left: 10pt} </style></head><body>${(Foncier.Commentaires__c != undefined ? Foncier.Commentaires__c : '')}</body>`+++
Foncier.Commentaires__c contains : <ul><li>Test <span style="color: rgb(255, 0, 0);">commentaires</span> HSE</li></ul><pre class="ql-syntax"></pre>
when i remove the HTML part and i replace it by +++Foncier.Commentaires__c+++ i have the html part that shows up wich means that the data is correct.
Also when i use the docxmerger i always have an error when i try to open the word document "unreadable content..."

One more thing instead of merging the files (Blob) i download them all and it works fine, no errors

 for(var k = 0; k < helper.reportGlob.length; k++){
                                    var blob = new Blob([helper.reportGlob[k]], {type : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
                                    var url = URL.createObjectURL(blob);
                                    var a = document.createElement("a");
                                    a.href = url;
                                    a.download = 'output.docx';
                                    document.body.appendChild(a);
                                    a.style = 'display: none';
                                    a.click();
                                    a.remove();
                               }

Do you guys have any idea how to merge these files before download without docxmerger?
Thank you all

**Comment by jjhbw** [comment]
@benhaddoureda i don't know anything about merging documents... However, you can take a look at using a FOR loop to template multiple documents in a single call to docx-templates at the same time.
