### ISSUE TITLE
unable to get image size

### ISSUE THREAD

**Issue by AhmadMasri** [guigrpa/docx-templates#159]
Thanks a lot for this library,
I am facing a problem when i add an image:

my code is :

 ```
const template = fs.readFileSync('./templates/template.docx');
    const buffer = await createReport({
      template,
      data: {
        name: "Fname",
        surname: "Lname",
        fatherName: "fatherName",
        motherName: "motherName",
        date: moment().format("DD-MM-YYYY"),
       
      },
      additionalJsContext: {
        photo: ()=> {
          const img_data=fs.readFileSync('./public/images/1/2.png');
          return { width: 3, height: 3, data: img_data, extension: ".png", };                    
        }
      }
    });
```

    fs.writeFileSync('report.docx', buffer)

the result is :
<img width="682" alt="Screen Shot 2020-10-31 at 10 04 23 PM" src="https://user-images.githubusercontent.com/10615994/97787748-264cb280-1bc5-11eb-8cac-8e36f6dc8a63.png">

the template is :
<img width="472" alt="Screen Shot 2020-10-31 at 10 04 56 PM" src="https://user-images.githubusercontent.com/10615994/97787749-2cdb2a00-1bc5-11eb-8265-364b21498407.png">

**Comment by jjhbw** [comment]
You need to invoke the 'photo' function. Try photo() instead of photo.

**Comment by jjhbw** [comment]
Pretty sure that's it. Feel free to reopen if not!
