### ISSUE TITLE
No way to add paragraphs in literal xml

### ISSUE THREAD

**Issue by kodibear** [guigrpa/docx-templates#16]
Greetings! Loving your project. However, the literal XML functionality is not very useful in its current shape. Reason being is that you cannot add a table, new paragraphs and a lot of other XML content, because the parent paragraph is not being removed after the XML content is injected, which results in invalid XML. Any plans to change that in the future?

**Comment by guigrpa** [comment]
Could you please share an example template (and JS script, if needed)?

**Comment by guigrpa** [comment]
You could try this (in other words, closing the current paragraph, opening a new one with some text):

```
{
  someRawXml: `||</w:t></w:r></w:p>
<w:p>
  <w:r>
    <w:t>String from WriteToWordDoc method.||`
}
```

Or even this (i.e. close the current paragraph, insert a new one with some text, open a new paragraph to continue…):

```
{
  someRawXml: `||</w:t></w:r></w:p>
<w:p>
  <w:r>
    <w:t>String from WriteToWordDoc method.</w:t>
  </w:r>
</w:p>
<w:p><w:r><w:t>||`
}
```

Please let me know if it works.

**Comment by guigrpa** [comment]
Closed due to lack of activity, please reopen if needed

**Comment by jwasnoggin** [comment]
@guigrpa I was having the same issue and your second suggestion worked for me.
