### ISSUE TITLE
createReport is not a function

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#162]
![image](https://user-images.githubusercontent.com/46158826/98364103-2c73e080-2056-11eb-81de-6c48f08289b8.png)

`import createReport from "docx-templates";
import fs from "fs";

const template = fs.readFileSync("output.docx");

const create = async () => {
  const buffer = await createReport({
    template,
    data: {
      lol: "John",
      surname: "Appleseed",
    },
  });
  fs.writeFileSync("report.docx", buffer);
};
create().then(() => console.log("done"));`

**Comment by jjhbw** [comment]
Please ensure your compiler toolchain and import statements line up.

I cant help you with this.

**Comment by DVGY** [comment]
> Please ensure your compiler toolchain and import statements line up.
> 
> I cant help you with this.

I have used type: module, is there anything other than that I should look for?

**Comment by jjhbw** [comment]
Which toolchain are you using? Try require() if vanilla NodeJS. Also be sure to check how it is done in the various examples in the examples directory of this repository.

**Comment by RezaRahmati** [comment]
if you have `type:module` in your package.json use this way

```
import { createReport } from 'docx-templates';
```

**Comment by anjanvb** [comment]
With `'type': 'module'` in `package.json`, this works-

```js
import pkg from 'docx-templates';
const {createReport} = pkg;
```
