### ISSUE TITLE
{some_text} is not replacing the some_text with value

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#163]
const { createReport } = require("docx-templates");
const fs = require("fs");

const template = fs.readFileSync("1.docx");

const create = async () => {
  const buffer = await createReport({
    template,
    data: {
      S: "UU",
    },
  });
  fs.writeFileSync("output.docx", buffer);
};
create().then(() => console.log("done"));

I have created a text as `{S}` and I want to replace it, but it's not working

**Comment by KAVA-Leigh** [comment]
You haven't specified a custom delimiter, which is what you are trying to use ```'{' '}'```. Add the ```delimiter``` option as documented in readme & then it should work (default is '+++' i.e. ```+++S+++``` in template).

**Comment by DVGY** [comment]
> You haven't specified a custom delimiter, which is what you are trying to use `'{' '}'`. Add the `delimiter` option as documented in readme & then it should work (default is '+++' i.e. `+++S+++` in template).

Thanks it's working
