### ISSUE TITLE
dynamic table and placeholder

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#164]
Can someone help me to point to part of documentation where I can search to add dynamic tables with placeholder (So table will be made according to the data present in JSON)

Note: My English is pretty bad my frnd who would help me to read documentation is out of town,

**Comment by jjhbw** [comment]
Your English is clear, don't worry.

An example of table generation is given in the README [here](https://github.com/guigrpa/docx-templates#for-and-end-for). An example Word template containing a table can be found [here](https://github.com/guigrpa/docx-templates#for-and-end-for). 

Note that you need to know which columns you want to render beforehand. It is currently not supported to dynamically generate columns, only rows. There is a feature request open for this in issue #15.
