### ISSUE TITLE
Adding for in loop inside table generates empty row. 

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#168]
![image](https://user-images.githubusercontent.com/46158826/99393041-be0b0a00-2902-11eb-95b9-4c932be7782f.png)

My code looks likes this 
![image](https://user-images.githubusercontent.com/46158826/99393320-2c4fcc80-2903-11eb-856a-fcfb3a7f23a6.png)

**Comment by DVGY** [comment]
No I haven't, let me try that

**Comment by DVGY** [comment]
> This is deep Word voodoo, but have you tried removing the two empty 'Root Cause' and 'Corrective Action' cells above and below the templated row in your template?

Hey so I tried with two different types of tables. 
1. Simple Table 
2. Nested merged cells tables

![image](https://user-images.githubusercontent.com/46158826/99483156-a9bb2180-2983-11eb-8fec-dd39acdde894.png)
![image](https://user-images.githubusercontent.com/46158826/99483245-d1aa8500-2983-11eb-95a9-cde736f4da68.png)
Some extra rows are still added in the nested tables

The code of nested table looks like this 
![image](https://user-images.githubusercontent.com/46158826/99483319-f69ef800-2983-11eb-991b-865b61e5fd26.png)

Help me sort out this issue

**Comment by DVGY** [comment]
> template

> This is deep Word voodoo, but have you tried removing the two empty 'Root Cause' and 'Corrective Action' cells above and below the templated row in your template?

Yup this works thanks

**Comment by abhinovpankaj** [comment]
<img width="1094" alt="Screenshot 2023-08-27 at 1 18 11 PM" src="https://github.com/guigrpa/docx-templates/assets/15319976/b1c9166d-ccaa-4f2b-9722-3456c55dfc5a">

I am trying this, it is creating just fine except a row is being added at the end of the table, also is it possible to ignore cells if image is empty?
report docx:
<img width="1095" alt="Screenshot 2023-08-27 at 1 20 22 PM" src="https://github.com/guigrpa/docx-templates/assets/15319976/0395c901-6e4f-436f-b4b4-2897ed64fb2f">
