### ISSUE TITLE
Error when running NodeJS examples

### ISSUE THREAD

**Issue by gitowiec** [guigrpa/docx-templates#175]
I just cloned the repo and on the master branch I get this error when I try to run NodeJS examples:
```
$ yarn start
yarn run v1.22.5
$ node . swapi-simple.docx
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.openSync (fs.js:435:3)
    at Object.writeFileSync (fs.js:1194:35)
    at createReport.then.rendered (/home/user/workspace/investigations/docx-templates/examples/example-node/index.js:38:18)
Done in 0.93s.
```

NodeJS version: v10.16.2

**Comment by jjhbw** [comment]
You need to provide an output filename.

Agreed that this is not really clear just from looking at `package.json`. Note that the example is intended for you to read the code so you understand what is happening.

I'll add the output filename in the `start` script to avoid further confusion.
