### ISSUE TITLE
How to use docx-templates without SWAPI?

### ISSUE THREAD

**Issue by gitowiec** [guigrpa/docx-templates#176]
I just put simple placeholders in my Word document eg: [[place]], [[date]], [[nameOfCompany]] and I run
```
createReport({
  template,
  data: {
    nameOfCompany: 'Very long name of very important company',
    place 'CITY',
    date: '10/10/2020',
  },
}).then(
  rendered => fs.writeFileSync(
    process.argv.length > 3 ? process.argv[3] : null,
    rendered,
  ))
  .catch(console.log);
```
And it does not work (output file still has placeholders, that are not swapped with values)
I read README.md but I can't figure it out how to fill simple values (without loops, without graphql queries, etc)

**Comment by jjhbw** [comment]
You havent specified a custom delimiter, so the library is using the default delimiter (`+++`). You're using `[[` and `]]`. Feel free to reopen if this doesn't answer your question.

**Comment by gitowiec** [comment]
So when I open file `examples/example-node/swapi-brackets.docx` I see a lot of `[[` and `]]` custom delimiters but `index.js` in `example-node` folder does not specify it explicit. How come this works?

**Comment by jjhbw** [comment]
That example template shows an example of using custom delimiters. I don't think it works at all with `example-node/index.js`, as the code does not specify a custom delimiter. I've removed it as it may be confusing. See the README on how to use custom delimiters.
