### ISSUE TITLE
How to properly loop through table column?

### ISSUE THREAD

**Issue by sarantoo** [guigrpa/docx-templates#179]
Suppose I have data like this and number of columns (heads) varies:

```js
heads = [ 'value1', 'value2', 'value3' ]
data = [
  {
    item: "Item 1",
    cols: [ 1, 2, 3 ]
  },
  {
    item: "Item 2",
    cols: [ 4, 5, 6 ],
  }
]
```
What is expected:

Item | value1 | value2 | value3
----- | ------- | ------ | --
Item 1 | 1 | 2 | 3
Item 2 | 4 | 5 | 6

I've tried several ways, but the best one I can is below:

Item | {{FOR head IN heads}} {{ $head }} | {{END-FOR head}}
----- | ------- | ------ 
{{FOR row IN data}}
{{ $row.item }} | {{FOR col IN $row.cols }}{{ $col }}| {{END-FOR col}}
{{END-FOR row }}

Which produce:

Item | &nbsp; | value1 | value2 | value3 | &nbsp;
----- | --- | ------- | ------ | --- | ---
Item 1 | &nbsp; | 1 | 2 | 3 |  &nbsp;
Item 2 | &nbsp; | 4 | 5 | 6 |  &nbsp;

**Comment by jjhbw** [comment]
I think you're running into: https://github.com/guigrpa/docx-templates/issues/15

Dynamic column generation is not currently supported and is a much requested feature. Happy to look over a PR.

Feel free to reopen if this doesn't answer your question.
