### ISSUE TITLE
Raise an error when a FOR loop is not properly closed.

### ISSUE THREAD

**Issue by gitowiec** [guigrpa/docx-templates#180]
I can't fill in attached template. All I get is first 4 lines of the template with filled markers and then the rest is cut.
![image](https://user-images.githubusercontent.com/1553195/102773102-f8941680-4388-11eb-9227-011e48e94d29.png)

I'm attaching the template and the data I want to put in it.
```typescript
const data = {
        address: 'Długi Targ 200/12, Gdańsk',
        unitName: 'ACME Solutions',
        date: '18.12.2020',
        city: 'Gdańsk',
        nip: '1234567890',
        regon: '456456456',
        representatives: [
          {
            name: 'Osoba Pierwsza',
            contact: 'osoba.pierwsza@acmesolutions.pl',
          },
        ],
        paymentsFrequency: {
          taxYear: '2020',
          quarterly: true,
          choosing: true,
        },
        vatTaxpayerRegistration: {
          choosing: false,
          registeredTaxpayerExempt: true,
        },
      }

```
Template

[Prawne-oswiadczenie-PDOP-VAT.docx](https://github.com/guigrpa/docx-templates/files/5724100/Prawne-oswiadczenie-PDOP-VAT.docx)

More, when I remove this part of template:
```
+++FOR representative IN representatives+++
+++INS $representative.name+++ - +++INS $representative.contact+++
+++END-FOR representatives+++
```
I get an error that
```

Error: Error executing command 'taxYear'. ReferenceError: taxYear is not defined
    at new CommandExecutionError (node_modules/docx-templates/lib/errors.js:53:28)
    at Object.<anonymous> (node_modules/docx-templates/lib/jsSandbox.js:104:32)
    at step (node_modules/docx-templates/lib/jsSandbox.js:33:23)
    at Object.next (node_modules/docx-templates/lib/jsSandbox.js:14:53)
    at /home/user/workspace/project/packages/web-server/node_modules/docx-templates/lib/jsSandbox.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/docx-templates/lib/jsSandbox.js:4:12)
    at Object.runUserJsAndGetRaw (node_modules/docx-templates/lib/jsSandbox.js:54:12)
    at /home/user/workspace/project/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:478:50
    at step (node_modules/docx-templates/lib/processTemplate.js:33:23)
    at Object.next (node_modules/docx-templates/lib/processTemplate.js:14:53)
    at /home/user/workspace/project/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/docx-templates/lib/processTemplate.js:4:12)
    at processCmd (node_modules/docx-templates/lib/processTemplate.js:435:54)
    at /home/user/workspace/project/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:401:38
    at step (node_modules/docx-templates/lib/processTemplate.js:33:23)
    at Object.next (node_modules/docx-templates/lib/processTemplate.js:14:53)
    at /home/user/workspace/project/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/docx-templates/lib/processTemplate.js:4:12)
    at processText (node_modules/docx-templates/lib/processTemplate.js:370:66)
    at /home/user/workspace/project/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:325:42
    at step (node_modules/docx-templates/lib/processTemplate.js:33:23)
    at Object.next (node_modules/docx-templates/lib/processTemplate.js:14:53)
    at fulfilled (node_modules/docx-templates/lib/processTemplate.js:5:58)

```

It just ignores the declaration of ALIASes which is just before the usage of `taxYear`

```
+++ALIAS ch1 INS paymentsFrequency.monthly+++
+++ALIAS ch2 INS paymentsFrequency.quarterly+++
+++ALIAS chosenText INS paymentsFrequency.chosenText+++
+++ALIAS taxYear INS paymentsFrequency.taxYear+++
```

**Comment by jjhbw** [comment]
You are closing the FOR loop properly. You need to use `+++END-FOR representative +++` instead of `+++END-FOR representatives +++`. The rest of the template gets ignored.

I think this case can use a better error message, as an unclosed FOR loop is never intentional. I'll mark it as a potential enhancement.

**Comment by gitowiec** [comment]
Ok, thanks for finding my error. Strange, because I mechanically wrote `representatives`

**Comment by gitowiec** [comment]
And what about that ALIASes?

**Comment by jjhbw** [comment]
The ALIAS commands are below the end of the FOR loop, right? As the FOR-loop wasnt properly closed, the rest of the template was ignored.

**Comment by gitowiec** [comment]
You should read with understanding. I wrote "More, when I remove this part of template:". read againg my original post

**Comment by jjhbw** [comment]
Mind the attitude. Note that I'm helping you _for free_ with something that looks like _your job_. Unless you're working on something that processes invoices for charity, that means _i am helping you make money_.

Regarding your issue: see the[ docs on the ALIAS command](https://github.com/guigrpa/docx-templates#alias-and-alias-resolution-with-). You need to resolve the alias with `*`.

**Comment by jjhbw** [comment]
Keeping this issue open as the unclosed FOR-loop warning is a nice potential enhancement.

**Comment by gitowiec** [comment]
If you didn't have such an overgrown ego maybe you would see an asterisk in a *.docx file I shared with you to help remove bugs in this module.
Here is a screenshot to help you more, and this is you who should pay me.

![2020-12-22-16:03:41](https://user-images.githubusercontent.com/1553195/102902753-ab3ea480-446f-11eb-8f56-f580bbb6dcb5.png)

**Comment by jjhbw** [comment]
Again, this is free software. I'm not asking you to help me fix any kind of bug, and you're not obligated to use my work.

In your initial post you referred to `Error: Error executing command 'taxYear'. ReferenceError: taxYear is not defined`, right? There is no asterisk in your call to `+++taxYear+++`. Same for `+++chosenText+++` next to it. Are you referring to another template? I only have the one you sent in your earlier reply.

**Comment by jjhbw** [comment]
Closing this issue because a lot of its comments have apparently been deleted. A new issue for this problem has been created by someone else with a more elaborate explanation #322 .
