### ISSUE TITLE
Problem with font

### ISSUE THREAD

**Issue by majeeddl** [guigrpa/docx-templates#183]
The font is changed when I select a work document with custom font and font is selected "Calibri", How to set default font-family for template creator?

**Comment by jjhbw** [comment]
Can you post an example so I can replicate it?

**Comment by majeeddl** [comment]
@jjhbw : I have found my mistake, for applying custom font we should define parameter with that font such as "  {تست} " in persian font

**Comment by jjhbw** [comment]
Ah ok, that makes sense! Thanks for posting your solution!
