### ISSUE TITLE
Problem in table generated with HTML

### ISSUE THREAD

**Issue by FelipeBerrios** [guigrpa/docx-templates#184]
Hello,
I am using this library to generate a table, where each cell is made up of HTML elements. The problem is that the size of the generated cell is larger than it should be, since a blank space is generated at the end of each cell.

The code is the following:

![image](https://user-images.githubusercontent.com/7199448/103465084-50cb0100-4d17-11eb-9d29-7921c09e3b7c.png)

The table generated is the following:

![image](https://user-images.githubusercontent.com/7199448/103464988-d4d0b900-4d16-11eb-958b-ad4fe9a075da.png)

I even did a test where the body tag contains nothing:

![image](https://user-images.githubusercontent.com/7199448/103465106-81ab3600-4d17-11eb-9a1f-ba6048b93fad.png)

the result is the same:

![image](https://user-images.githubusercontent.com/7199448/103465114-91c31580-4d17-11eb-94df-3e608eb3c71d.png)

Hope you can help me please as I tried to style the body tag but apparently it is not supported.

Greetings and thanks for this great library.

**Comment by jjhbw** [comment]
Sorry for the late reply.

Hmmm this may be related to the fact that you're fitting a HTML document into each cell. Word may provision a minimum height for that or something... Out of interest, why do you need the HTML in each cell?
