### ISSUE TITLE
EXEC does not work

### ISSUE THREAD

**Issue by gitowiec** [guigrpa/docx-templates#186]
- A small reproducible example consisting of the code and .docx template you used.
```
+++EXEC
ch1 = ’X’;
+++
```

- A screenshot of the result you get and an explanation as to why this result is unexpected.

```
Error: Error executing command 'ch1 = ’X’;'. SyntaxError: Invalid or unexpected token
    at new CommandExecutionError (node_modules/docx-templates/lib/errors.js:53:28)
    at Object.<anonymous> (node_modules/docx-templates/lib/jsSandbox.js:104:32)
    at step (node_modules/docx-templates/lib/jsSandbox.js:33:23)
    at Object.next (node_modules/docx-templates/lib/jsSandbox.js:14:53)
```

Attached template:

[Prawne-oswiadczenie-PDOP-VAT.docx](https://github.com/guigrpa/docx-templates/files/5780442/Prawne-oswiadczenie-PDOP-VAT.docx)

**Comment by jjhbw** [comment]
Can you try with `fixSmartQuotes:true`? Because of:

> MS Word usually autocorrects JS string literal quotes with unicode 'smart' quotes ('curly' quotes). E.g. 'aubergine' -> ‘aubergine’. This causes an error when evaluating commands containing these smart quotes, as they are not valid JavaScript. This setting automatically replaces these smart quotes with normal JS-friendly quote characters.

**Comment by jjhbw** [comment]
Closing now to keep the tracker clear. Pretty sure this should solve it. Let me know if it doesn't!

**Comment by gitowiec** [comment]
It helped, thanks
