### ISSUE TITLE
base64 vs buffer of images performance

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#187]
Just a quick question, 

```
additionalJsContext: {
    tile: async (z, x, y, size = 3) => {
      const resp = await fetch(
        `http://tile.stamen.com/toner/${z}/${x}/${y}.png`
      );
      const buffer = resp.arrayBuffer
        ? await resp.arrayBuffer()
        : await resp.buffer();
      return { width: size, height: size, data: buffer, extension: '.png' };
    },
```

1. Here data is in buffer form, is there any performance issue if the data is in base64 format? 

2. So, I am downloading images from azure storage and image is in stream format. I am converting it to buffer and then to base64 String. Is this heavy on performance ? 

3. Does docx-template convert all the images to base64 behind the scene? 
Thanks

**Comment by jjhbw** [comment]
Docx files are just zip files with a lot of xmls and media files inside them.

If you extract one using e.g. the `unzip` utility you can see the image files. This means docx-templates will convert any image you provide to a file buffer under the hood before inserting it in the zip archive. Converting from Base64 will add an extra step to that, which comes with overhead (this happens somewhere in jszip, see [this code](https://github.com/guigrpa/docx-templates/blob/4ffd3ca669f856de7ed3e401d3b16a7400baaf11/src/zip.ts#L14-L15)). Hence, providing a raw Buffer may provide a minor performance benefit.

Be sure to let me know if this does not answer your question.
