### ISSUE TITLE
Image orientation wrong

### ISSUE THREAD

**Issue by trx222** [guigrpa/docx-templates#189]
Hi, thanks for the great lib - it helps me so much.

I have a problem with some images - the are inserted in a wrong orientation, and then the aspect ration is not correct of course. How can I fix it before i insert an image? I use following code:

insertImgFit - function in additionalJsContext:

```
var data=fs.readFileSync(filename);
var ext = path.extname(filename).toLowerCase();
[some calculation of width and height - no problem here]
return { width: bw, height: bh, data, extension: ext };
```

The image is inserted with the correct width and height - but 90 degrees rotated. I think I have to check somehow the EXIF Orientation flag an rotate the image - does someone know how this can be done? 

I am using the lib in nodejs, on mac and on windows.

**Comment by trx222** [comment]
I found a solution that I want to share - I used 'jpeg-autorotate':

```
const autorotate = require('jpeg-autorotate');

insertImgFit: async function(id, w, h) {
   var data2=fs.readFileSync(imgObj.img);
   var {buffer, orientation, dimensions, quality} = await autorotate.rotate(data2, {quality:99});
   var ext = path.extname(imgObj.img).toLowerCase();
   return { width: bw, height: bh, data:buffer, extension: ext };
}
```

the async/await was the key I was searching for ...

**Comment by jjhbw** [comment]
Thanks for posting your solution!
