### ISSUE TITLE
Replacing template images - Header/Footer

### ISSUE THREAD

**Issue by iainfreestone** [guigrpa/docx-templates#19]
Hi,

I am using the IMAGE command in the body of my document but it does not work when trying to insert an image into the "Header" of my template so I am still using the following for inserting a logo into the header of my document.

````
replaceImages: {
      'image1.png': getImageData(logo),
    },
````

I notice that this is now deprecated as of v2.4.0 and may be removed in future releases. Removal could cause issues unless the IMAGE command is working in the header/footer before it is it is removed.

Many Thanks

Iain

**Comment by guigrpa** [comment]
Thanks for reporting! This is just to tell you that I have little time these days to fix this, but the image replacement feature is not going away, for sure, until this issue is solved. I hope to address it in a couple of weeks or so…

**Comment by wingaard** [comment]
Hi,

When using the replaceImages function, is there anyway to set the size of the replaced image? For example I would like to replace an image with 100x100px with one that is 100x200px. When using it now it the replaced image gets the same size as the original. I have tried setting the orginal image with different size settings in the template (% etc) but the replaced image still gets the same size as the original.

Thanks in advance!

**Comment by guigrpa** [comment]
I'm afraid not, that's one of the limitations of the replace-images feature, which was just put in place quickly when the IMAGE command didn't exist yet.

**Comment by guigrpa** [comment]
Please check v2.4.1 and let me know if the problem re-appears

**Comment by wingaard** [comment]
I have tested the IMAGE command in header in v2.4.1 and can confirm that it works. Thanks a lot!

**Comment by iainfreestone** [comment]
Works great now. Many thanks
