### ISSUE TITLE
Docm support

### ISSUE THREAD

**Issue by brockfanning** [guigrpa/docx-templates#195]
Hello, I need to create Word docs from a template that is a docm (not docx) file. When I try with a particular docm file I get: `Error: Could not find main document (e.g. document.xml) in [Content_Types].xml`

If I use a docx file I don't get that problem, so I suspect that docm files are not supported. I was just wondering if anyone knew of a work-around for getting a docm file to work as a template. I will dive into the code and see what I can do, but also wanted to get feedback from the experts.

**Comment by jjhbw** [comment]
Hi @brockfanning ,

Interesting, I've never used docm files before. 

This library unzips the .docx file and tries to find the path to the `document.xml` file by reading `[Content_Types].xml`. I just checked, and the relevant line in `[Content_Types].xml` is slightly different in docm files.

.docx
```
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
```

.docm
```
<Override PartName="/word/document.xml" ContentType="application/vnd.ms-word.document.macroEnabled.main+xml"/>
```

So the first step of any attempt to extend this library with docm support would be to refactor the below function to work with docm-derived `[Content_Types].xml` files.
https://github.com/guigrpa/docx-templates/blob/10b6e16b1693edaa808a0ccc856159eaa460617b/src/main.ts#L409-L424

That would be step 1, I think.

I don't know whether there are other major differences in structure between the two file formats, so there may be other more serious blockers before docm can be supported.

**Comment by brockfanning** [comment]
Thanks @jjhbw - I gave that a try and it appears to work without any issues. The docm could be used as a template without errors, and the output file - so long as it is created with a docm extension - loads fine and the macros are intact. I just opened #196 in case it's helpful.

**Comment by jjhbw** [comment]
@brockfanning thanks for contributing! Looks great. I've merged your PR and added a commit on top to please the typechecker (743a55214b1337f1e27a9896b7c6e207f9b061bf) and another one with a test case (29af43002239fa2c4be05ed17abe867ed3a88873).

**Comment by brockfanning** [comment]
Great! 👍
