### ISSUE TITLE
Guidance on using fork

### ISSUE THREAD

**Issue by brockfanning** [guigrpa/docx-templates#198]
Hello, I'm interested in using a fork of this library as a dependency in a project but am running into difficulties. What I have tried:

* Pointing to the fork in the project's package.json. In this case, changing `"docx-templates": "^4.5.4",` to `"docx-templates": "brockfanning/docx-templates#docm-support",`.
  Result (on trying `npm install`): `sh: 1: yarn: not found` 

* Install Yarn globally: `npm install --global yarn`
  Result: `/bin/sh: 1: rimraf: not found`

* Install rimraf globally: `npm install --global rimraf`
  Result: `/bin/sh: 1: tsc: not found`

* Install tsc globally: `npm install --global tsc`
  Result:

```
error TS5023: Unknown compiler option 'esModuleInterop'.
error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.
error TS5023: Unknown compiler option 'strict'.
error TS5023: Unknown compiler option 'forceConsistentCasingInFileNames'.
```

Other things I've tried without any other apparent change:
* Copying tsconfig.json into my project
* Copying the entire devDevendencies block into my project's package.json
* Add `"postinstall": "cd ./node_modules/docx-templates && npm install and npm run compile"` to my project's package.json

I did also read through #4 but that most mostly over my head. Any advice is greatly appreciated!

**Comment by brockfanning** [comment]
I actually don't need this advice urgently anymore, since the PR was merged and released (thank you!). Maybe it would still be useful to someone in the future though?

**Comment by mathe42** [comment]
Add your build files to your versioncontrol. You use `yarn link` in all of my cases one of the two things was easy to use.

**Comment by mathe42** [comment]
(Also in other packages)

**Comment by jjhbw** [comment]
Hoped this helped a bit. Closing this issue for now as this is not directly related to the library.

**Comment by brockfanning** [comment]
Maybe that advice will make more sense to others - personally I did not understand. For me a list of terminal commands might be more helpful. But I agree the question is not specific to this library and I'm fine with dropping it.

**Comment by mathe42** [comment]
The thing is this is not something special about this package. And `npm link` and `yarn link` (see the coresponding docs) works in more than 90% of use cases (for all packages) even with monorepros and yarn workspaces. So there is no need for special explanaitions.
