### ISSUE TITLE
Dynamically render html

### ISSUE THREAD

**Issue by pawepaw** [guigrpa/docx-templates#199]
Hi,

I've got one more question, is it possible to dynamically render HTML? 

i.e sthn like that

```+++HTML HtmlContent+++```
Where HtmlContent is variable passed as data to rendering. I've tried a couple of variant's but none were working. 

```+++HTML `HtmlContent`+++``` ```+++HTML +++HtmlContent++++++``` etc

**Comment by pawepaw** [comment]
ok, I've managed to fix that. it should be

+++HTML ${HtmlContent}+++

**Comment by Ademking** [comment]
> I'm trying to do this with out success. My goal is to pass variables from the template to the html which will be rendered. @pawepaw can you provide more details?

![image](https://user-images.githubusercontent.com/12462188/134619898-f21d64cf-4b4c-4147-8e4d-c70f5ba656f8.png)
