### ISSUE TITLE
EXEC and strings

### ISSUE THREAD

**Issue by datenwort** [guigrpa/docx-templates#2]
Hey again,

maybe I do something wrong but I do not get an example running with exec and text values.
Here a litte example: 

```
+++EXEC
a = { b : “5”, c : “4”};
fail = (val) => val === false ? a.b : a.c;
+++
```

**Comment by guigrpa** [comment]
If you look closely, I think you have smart quotes around the numeric constants. That's probably why the code fails. Use straight quotes instead.

Tip: you can also use `+++! ... +++` as a shortcut for `+++EXEC ... +++`

**Comment by datenwort** [comment]
Unfortunately this does not solve it. I tried it with both types.
As I can see in the sandbox context the code is given to a variable which is quoted in 'a = { b : '5', c : '4'};
fail = (val) => val === false ? a.b : a.c;' and it seems that the eval process is in somekind not able to work with additional quotes. Neither " nor '

**Comment by guigrpa** [comment]
Hmmm, strange; doesn't happen at my side. Please check with the following example:
[test.docx](https://github.com/guigrpa/docx-templates/files/730969/test.docx)

**Comment by guigrpa** [comment]
The doc I sent to you should produce absolutely no output, since you're running the snippet with `EXEC`. What is the purpose of the `fail` function in your snippet, by the way?

**Comment by datenwort** [comment]
Yes it works...and now also in my example. The code was quite correct but not the quotation mark. For what reason it added `a = { b : ‘5’, c : ’4’};` instead of `a = { b : '5', c : '4'}; `

And to satisfy your curiosity ;) I use your library to create a word document out of a validation of a software and depending on the data injected in docx-template this function should return a word phrase. Yes I know I could do this also by using the if-else syntax, but due to the quotation mark issue nothing worked till now.
