### ISSUE TITLE
populate chart / diagram data

### ISSUE THREAD

**Issue by DeveloperOl** [guigrpa/docx-templates#202]
Hi everyone,
I am having trouble creating a bar chart with docx-templates.
In my template is a bar chart (lets say with three bars). The problem is that all numbers for the chart need to be inserted by docx-templates. The problem is that I can't use commands like +++= for the data as it is a string and not a number.

Is there any way to populate a chart without using raw XML code?

**Comment by jjhbw** [comment]
I'm sorry, I don't know the answer to that question... I'll leave it open in case someone with more experience with the .docx spec wants to comment.

**Comment by jjhbw** [comment]
I'm sorry I don't think this is supported at this time.
