### ISSUE TITLE
createReport does not work

### ISSUE THREAD

**Issue by zsjbsn** [guigrpa/docx-templates#203]
Hi everyone,
I can run a simple example with createReport  successfully in vue2.x.

```
import createReport from 'docx-templates';
import fs from 'fs';
const template = fs.readFileSync('xxx.docx');
createReport({
  template,
  data: {
    name: 'John',
    surname: 'Appleseed',
  }
}).then(() => {
    console.log(1);
  })
  .catch(() => {
    console.log(2);
  });
```

In electron, read xxx.docx as buffer successfully.But createReport does not work, and no error throw out(not console.log1 or 2). It confuses me for a long time. The version is 4.6.0.

**Comment by jjhbw** [comment]
I don't think this is an issue with docx-templates, but with your environment.

If i run the below in a node v12.20.0 shell, everything works fine.

```javascript
const fs = require('fs')
const {createReport} = require('docx-templates')

const template = fs.readFileSync('xxx.docx');
createReport({
  template,
  data: {
    name: 'John',
    surname: 'Appleseed',
  }
}).then(() => {
    console.log(1);
  })
  .catch(() => {
    console.log(2);
  });
```
