### ISSUE TITLE
Trouble inserting raw openxml 

### ISSUE THREAD

**Issue by qngdt** [guigrpa/docx-templates#204]
Suppose I have this openxml string
> <w:p><w:pPr><w:spacing w:lineRule=\"exact\"/></w:pPr><w:r><w:rPr/><w:t xml:space=\"preserve\">My sample HTML STRING</w:t></w:r></w:p>

Can I use this openxml string directly to generate docx file. Using `||` as `literalXmlDelimiter` in the documentation doesn't seem to work

**Comment by jjhbw** [comment]
Literal XML is always hard to get right, as it needs to comply with the spec.
Closing this for now unless you are super sure that your XML is valid and think this is a bug.
