### ISSUE TITLE
Docx is generating only half document.

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#205]
I am using docx-template and nodejs

It successfully generates the doc file. Just now it has started generating doc file with half pages. 
All the pages after page number 16 are missing. 

Please help

**Comment by DVGY** [comment]
Update: 
The issue I found was `+++INS $value ++%+` unfortunately this did not give me an error. Also all the page after this line were not included in the report

I changed above to   `+++INS $value +++` and it worked

**Comment by jjhbw** [comment]
Thanks for posting the solution! I think this is related to #180. I'll close this issue as it is very similar.
