### ISSUE TITLE
Multi-line Queries

### ISSUE THREAD

**Issue by IanWitham** [guigrpa/docx-templates#21]
Great work Guillermo! Just a couple of minor annoyances with multi-line queries.

Line breaks in a query don't retain white-space when sent to the query function, causing a syntax error in the database query engine.
E.g.
```
+++QUERY SELECT id
FROM records
USE KEY "myRecord::1234"
+++
```
becomes
```
SELECT idFROM recordsUSE KEY "myRecord::1234"
```
Expected behavior would be to either retain a newline character, or to replace with a single space.

The easy work-around is to add some explicit white-space at the beginning of each line, but I keep forgetting to do this after pasting a query.

I've also noticed that you must start the query on the same line as the QUERY tag, or it doesn't work.
e.g. this works
```
+++QUERY SELECT id
    FROM records
+++
```
this does not (it just resolves to null)
```
+++QUERY
   SELECT id
   FROM records
+++
```

**Comment by guigrpa** [comment]
In principle, the first issue you mentioned is fixed in v2.5.2. Regarding the second, I wasn't able to reproduce it; but maybe it was also fixed as a side effect ;). Could you please check? If needed, please reopen this issue.
