### ISSUE TITLE
HTML is not displayed on Max osx (pages, libreoffice)

### ISSUE THREAD

**Issue by mcieslakcc** [guigrpa/docx-templates#210]
Platform: Mac osx
Node version: 12.8.3
Tool used: Pages, Libreoffice
docx-templates version: 4.6.0

Hello, 
I tried to use HTML commad in my .docx using Pages on mac.
I pasted following code into .docx
```
+++HTML `
<meta charset="UTF-8">
<body>
  <p>
    <strong style="color: red;">This paragraph should be red and strong</strong>
  </p>
</body>
`+++
```

and after creating report I see that field which should be filled is empty. When I open the same document in microsoft office   text **This paragraph should be red and strong** is visible.

**Comment by jjhbw** [comment]
This may be related to #201 or #62 . In summary, HTML is only fully supported by MS Word, and the other editors have only limited or no support.

I'm sorry, but docx-templates can't help here... Feel free to reopen this issue if you disagree.
