### ISSUE TITLE
How to insert a table like docxtemplater

### ISSUE THREAD

**Issue by zackzergzeng** [guigrpa/docx-templates#211]
https://docxtemplater.com/demo/#table

**Comment by jjhbw** [comment]
See the README https://github.com/guigrpa/docx-templates#for-and-end-for and the example templates https://github.com/guigrpa/docx-templates/blob/c4356261c0d9bc220db9f30f955c8aaaa4dac377/src/__tests__/fixtures/for-row1.docx

docx-templates has nothing to do with docxtemplater.com

**Comment by RezaRahmati** [comment]
if template is like this
![image](https://user-images.githubusercontent.com/10086092/141230986-77f10175-3830-4b5d-8484-3004e7ce63f0.png)

it will result like this
![image](https://user-images.githubusercontent.com/10086092/141231050-9a9afde8-6526-48b4-9029-e46bb7654858.png)

**Comment by jjhbw** [comment]
Can you explain what is going wrong? Also, please post a reproducible example.

**Comment by RezaRahmati** [comment]
@jjhbw nothing is wrong, I added answer for the original question, so in case someone else came to this thread see it, (like me that I came and current answer was not clear to me)

**Comment by jjhbw** [comment]
Sorry I misread! I didn't notice I was commenting on a closed issue from the github app. Thanks for posting the solution!
