### ISSUE TITLE
BUG: Endless loop with object

### ISSUE THREAD

**Issue by amunhoz** [guigrpa/docx-templates#213]
I'm having a problem with a loop in an object.  The system stucks, using a lot of cpu and not finishing the job.
The problem does not occurs if "domains" is an array.

The information is:
```
 "domains": {
        "google.com.br": {
          "domain": "google.com.br",
          "info": {          
            "status": "published"
          },
          "ipv4": "142.250.219.35 - 172.217.29.131 - 172.217.8.3",
          "ipv6": "2800:3f0:4001:822::2003 - 2800:3f0:4001:812::2003 - 2607:f8b0:4004:82a::2003"
        },
       "google.com.brx": {
          "domain": "google.com.br",
          "info": {          
            "status": "published"
          },
          "ipv4": "142.250.219.35 - 172.217.29.131 - 172.217.8.3",
          "ipv6": "2800:3f0:4001:822::2003 - 2800:3f0:4001:812::2003 - 2607:f8b0:4004:82a::2003"
        }
      }
```

And the template is:
```
!!FOR nav IN domains!!
   !!=$nav.domain!! 
!!END-FOR nav!!
```

**Comment by jjhbw** [comment]
Good find! I think this is a bug. I encountered this myself as well. I'll take a look. Thanks for reporting.

**Comment by jjhbw** [comment]
Should be fixed in next release.

**Comment by daniskhabirov** [comment]
I get the error `ObjectCommandResultError` when call an object property:

[FOR breach IN breaches]
[INS $breach.number]
[END-FOR breach]

Result: ObjectCommandResultError: Result of command '$breach' is an object

**Comment by jjhbw** [comment]
@daniskhabirov The docs say `ObjectCommandResultError is thrown when the result of an `INS` command is an Object. This ensures you don't accidentally put `'[object Object]'` in your report.`

In other words; is it possible `$breach.number` is a javascript object rather than e.g. a string or a number?
