### ISSUE TITLE
Inserting an array of stings throws error

### ISSUE THREAD

**Issue by LexAckson** [guigrpa/docx-templates#214]
Template:
+++INS ['a','b','c'] +++

Output in version 4.6.0:
a,b,c
Output in version 4.6.2:
Command failed! "['a', 'b', 'c']" Result of command '['a', 'b', 'c']' is an object

node v10.16.3, chrome v93

**Comment by jjhbw** [comment]
I introduced this behaviour in 4.6.1 on purpose to avoid objects as the result of INS commands. This would result in `'[object Object]'` strings in your report, which are practically always a mistake. 

I did not consider your use case well enough, though. I personally would always use `[1,2,3].join(', ')` instead... However, come to think of it it is pretty reasonable to expect this to just work.

I will make an exception for arrays.

**Comment by jjhbw** [comment]
Fixed in https://github.com/guigrpa/docx-templates/releases/tag/v4.6.3
