### ISSUE TITLE
Error everytime "cmdDelimiter: ['{', '}']" defined

### ISSUE THREAD

**Issue by weilies** [guigrpa/docx-templates#216]
I am running into a situation. 

1. If cmdDelimiter not defined, the docx is generated, but {variable} still remain the same.
2. If cmdDelimiter: ['{', '}'] defined, it error out (as following)

> Error: Uncaught (in promise): Error: Error executing command 'name'. TypeError: vm_1.default.Script is not a constructor
> Error: Error executing command 'name'. TypeError: vm_1.default.Script is not a constructor

Here is the [project](https://stackblitz.com/edit/ng-docx-templates-g1nj3?file=src%2Fapp%2Fapp.component.ts), I am running an angular project, angular ver 11++. [package.json](https://stackblitz.com/edit/ng-docx-templates-g1nj3?file=package.json), [tsconfig.json](https://stackblitz.com/edit/ng-docx-templates-g1nj3?file=tsconfig.json) details attached.

Really appreciate for any helps. I am almost there, from tons of runtime errors till now i can see the doc. :D

**Comment by KAVA-Leigh** [comment]
I would highly suggest using a different delimiter, may not be the issue in this case- however see #102

**Comment by weilies** [comment]
i think it's not about the "{" pattern, i changed my template and code to reference "{{" (double curly brackets), i still get the same error. [same project](https://stackblitz.com/edit/ng-docx-templates-g1nj3?file=src%2Fapp%2Fapp.component.tsl)

**Comment by jjhbw** [comment]
The vm package doesnt seem imported in your environment. Try disabling the
sandbox ('nosandBox:true').

**Comment by weilies** [comment]
Thanks for the helps!!! @jjhbw Love u!!

**Comment by jjhbw** [comment]
No problem 👍

Feel free to open a new issue if you have a question.

**Comment by weilies** [comment]
Yes. Thanks Jurriaan!

**Comment by WrightLiam** [comment]
Sorry to bother, but would you happen to have any other recommendations for someone running into this issue? 

I seem to be getting this same error using the default delimiters +++, setting custom delimiters doesn't seem to make a change, and adding "nosandBox:true" to the createReport function doesn't make any apparent difference.

Do you have any thoughts off hand or would you need to see the project first?

**Comment by jjhbw** [comment]
Are you using an Angular toolchain? They tend to do only barebones polyfilling/importing of dependencies. Any dependency import issues you may have (like vm) likely stem from there.

I'm going to need a reproducible example regardless, i'm afraid.
