### ISSUE TITLE
IMAGE commands in the document body are ignored when a Shape/image is already present in header or footer

### ISSUE THREAD

**Issue by jjhbw** [guigrpa/docx-templates#217]
Sure ! Here is a very simple template that is failing. I'm using the method injectSvg() that is in the documentation :
[7078ebf0-16fe-68d6-0e45-e78a25feb224.docx](https://github.com/guigrpa/docx-templates/files/6732060/7078ebf0-16fe-68d6-0e45-e78a25feb224.docx)

```typescript
createReport({
    template: templateFile,
    data: {
    },
    noSandbox: true,
    cmdDelimiter: ['{{', '}}'],
    additionalJsContext: {
        injectSvg: () => {
            const svg_data = Buffer.from(...., 'utf-8');
            return { width: 6, height: 6, data: svg_data, extension: '.svg' };
        }
    }
})
```
(Just replace the `Buffer.from(...)` by the one that is in the documentation)

And the generated document :
[fail.docx](https://github.com/guigrpa/docx-templates/files/6731795/fail.docx)

_Originally posted by @matcobat in https://github.com/guigrpa/docx-templates/issues/144#issuecomment-870393351_

**Comment by JoshuaTruscott** [comment]
I'm having the same issue

**Comment by JoshuaTruscott** [comment]
Just to clarify, in my case I'm adding 2 images, a png in the header and a jpg in the body using IMAGE in the same manner as above. The png in the header renders but the jpg in the body doesn't.

**Comment by jjhbw** [comment]
Thanks for clarifying. I've reproduced it. I also noticed that if you put 4 <<IMAGE>> commands in your repro template, only 3 images get rendered.

Experimenting with candidate fixes now.

**Comment by jjhbw** [comment]
Should be fixed in https://github.com/guigrpa/docx-templates/releases/tag/v4.6.4.

GH Actions should be publishing it to NPM right now. Let me know if you encounter anything weird. Thanks for reporting!

**Comment by matcobat** [comment]
Many thanks ! It's working like a charm now !
