### ISSUE TITLE
Insert Image Problem

### ISSUE THREAD

**Issue by Bounguicha** [guigrpa/docx-templates#219]
When i insert an image this error appears : "createQrImage is note defined" because of the function createQrImage in the object additionalJsContext 
Any solution please ?

**Comment by jjhbw** [comment]
Please post your template and createReport invocation so i can reproduce the problem.

**Comment by Bounguicha** [comment]
i have an object called 'person' who have the image url called imageUrl,

Code on the docs : +++IMAGE qrCode(person .imageUrl)+++ 

code on js :   const file = await createReport({
    template,
    output: 'buffer',
    data:JSON.parse(data),
    additionalJsContext: {
          qrCode: url => {
              const dataUrl = createQrImage(url, { size: 500 });
              const data = dataUrl.slice('data:image/jpg;base64,'.length);
              return { width: 6, height: 6, data, extension: '.jpg' };
          },
      }
  });

**Comment by jjhbw** [comment]
`createQrImage` is not defined in the sandbox that the template is being executed in. One option is to expose `createQrImage` through `additionalJsContext` as well.

This should fix it. Feel free to reopen this issue or mention me (@jjhbw) in a reply if it doesn't.

**Comment by Bounguicha** [comment]
@jjhbw  Can you please explain with more details or correct my code please

**Comment by Bounguicha** [comment]
createQrImage is a predefined function , it supposed to be defined automatically because it is included in the docx template module @jjhbw

**Comment by mathe42** [comment]
No It is just a example! You have to implement / get this function on your own.

**Comment by Bounguicha** [comment]
@mathe42 do you have any solution ?

**Comment by jjhbw** [comment]
What @mathe42 posted is correct. The `createQrImage` is just an example. Sorry if that wasn't clear. See https://github.com/guigrpa/docx-templates/blob/94db693c143815fbb1f6da7366944ffc0d1d232a/examples/example-webpack/client/index.js for a full working example of how to use QR codes.

**Comment by Bounguicha** [comment]
@jjhbw i want to implement a jpg image, can you please give me the function or a solution please its not important to use a QR code

**Comment by jjhbw** [comment]
@Bounguicha you need to look into that yourself, i'm afraid. You want to convert a JPG image from some source into base64 string. This is easy, but highly dependent on your use case. This is not a docx-templates specific question.

**Comment by Bounguicha** [comment]
@jjhbw i just want to implement a simple jpg image in a my docs template , forget about the converting into a base64

**Comment by jjhbw** [comment]
@Bounguicha an `+++IMAGE +++` command needs to return an object shaped like this `{ width: 6, height: 6, data, extension: '.gif' };`

`data` is either an ArrayBuffer or a base64 string with the image data. See the README.

You can import it with something like `const data = fs.readFileSync('image.jpg')` if you are working in Nodejs.

This is not specific to the docx-templates library and all documentation is present to guide you through the parts that are specific to the library. You can refer to the examples in this repository for inspiration. Please stop mentioning me in this issue unless you are sure your problem is related to this library.
