### ISSUE TITLE
Feature request - support for different formatting in same tag

### ISSUE THREAD

**Issue by jsve** [guigrpa/docx-templates#22]
Hi,

It would be really helpful to be able to add highlighting and/or describe different formatting options within the same template tag. What i mean is pretty much the HTML equivalent of `<span>` and `<h1>`, `<h2>`.

Example:
I put this in the template document:
`{{Introduction}}`

and this as data:
```
'introduction': [
   '<h1>Introduction</h1>',
   '<h2>Purpose</h2>'
   '<p>This is the <span class='highlight'>purpose</span> of this document</p>'
]
```

or maybe this:
```
'introduction': [
   { 'content': 'Introduction',
     'styling': 'h1'   
   },
   { 'content': 'Purpose',
     'styling': 'h2'
    },
   { 'content': This is the __purpose__ of this document',
     'styling': 'p',
     'span': 'highlight'
    }
]
```

**Comment by guigrpa** [comment]
That's probably too much additional complexity for this library; maybe you would be better served by  an HTML-to-Word converter? Pandoc?

You may also be able to achieve part of what you need, e.g. conditional formatting depending on the query data, by including it in IF commands, e.g.

```
+++IF person.name === 'John'+++
(text in red)
+++END-IF+++
+++IF person.name !== 'John'+++
(text in blue)
+++END-IF+++
```
