### ISSUE TITLE
Unwanted spaces added automattically in docx format

### ISSUE THREAD

**Issue by Bounguicha** [guigrpa/docx-templates#225]
Hello, there are spaces added automatically in the docx when I use the +++FOR +++ loop

**Comment by Bounguicha** [comment]
> Hello, there are spaces added automatically in the docx when I use the +++FOR +++ loop

**Comment by Bounguicha** [comment]
Hello, there are spaces added automatically in the docx when I use the +++FOR +++ loop

**Comment by jjhbw** [comment]
Please post a reproducible example.

**Comment by Bounguicha** [comment]
Hello Sorry for the late Reply, 
the problem is that if there is a +++ if +++ in the +++ FOR +++ loop
many  unwanted spaces added automatically.

here is the data
      person: {
        pro_exp: [
          {
            professional_experience_code: '0000'
          }
        ],
        project: [
          {
            start_date: '20-8-2020',
            end_date: '20-10-2020',
            professional_experience_code: '0000',
            project_title: 'Project 1',
          },
          {
            start_date: '20-8-2020',
            end_date: '20-10-2020',
            professional_experience_code: '0000',
            project_title: 'Project 2',
          },
          {
            start_date: '20-8-2020',
            end_date: '20-10-2020',
            professional_experience_code: '0000',
            project_title: 'Project 3',
          },
          {
            start_date: '20-8-2020',
            end_date: '20-10-2020',
            professional_experience_code: '0000',
            project_title: 'Project 4',
          },
        ]
  };

and here is  the code found in the docx
+++FOR proExp IN person.pro_exp+++
+++FOR project IN person.project+++
+++IF $proExp.professional_experience_code === $project.professional_experience_code +++
+++INS $project.start_date+++ - +++INS $project.end_date+++:+++INS $project.project_title+++
+++END-IF+++
+++END-FOR+++



I hope you understand my problem and thank you

**Comment by Bounguicha** [comment]
@jjhbw

**Comment by Bounguicha** [comment]
@jjhbw

**Comment by mathe42** [comment]
> Please post a reproducible example.

So a .docx file with the template  and a js snippet and the .docx file after executing the js snippet.

And please don't just randomly tag someone. This will not help you get faster resposes (in most cases)
