### ISSUE TITLE
Is it possible to update generated document?

### ISSUE THREAD

**Issue by ni3galave** [guigrpa/docx-templates#226]
I require to update a document that is already created using create report function with the help of a template.
Now, I want to add some extra sections to the existing generated document and don't want to repeat createReport process because of the large document size.

Any way to achieve this?

**Comment by jjhbw** [comment]
No i'm afraid that is not possible, and out of this library's scope. If you have performance issues with large templates, you can consider disabling the sandbox mode. Make sure you understand the security implications of this first (it is basically only sensible if your templates are as trusted as the rest of your codebase). See the README for details.

**Comment by ni3galave** [comment]
Thanks for the confirmation!
