### ISSUE TITLE
Invalid variable for image name in template

### ISSUE THREAD

**Issue by changhaojun** [guigrpa/docx-templates#227]
Invalid variable for image name in template, such as  +++ test () +++
- When test is a variable traversed through a loop, +++ test () +++ is invalid

**Comment by jjhbw** [comment]
Can you post a minimal reproducible example? A Word template and a createReport invocation.

**Comment by changhaojun** [comment]
Hello, jjhbw
here is the data:
const alert = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAYTSURBVGhDzVj7bxRVFJ5/i0cBXzxUKFTQGAhGYwwJ/cXfNBpN/IEiiC2FFtCuVgJoffAwPKJGqrHEiIhE1JBCxPoA6c7MPtp9tbt7PN+9c2fuzt7dmdk2xpN8Ofeee853vr1zd2Z2LVqIVWs0/+sdKp74jvKvnCF3e4qcdfvJXrGH0steF95eOyDiWC+9f1nko24h1pHo6u82zQ5+SW7PMKWX7pYCgaWeZ4h4C6AO9eDpxBKJrv6WpvxLp+QOesKmIUSJZI95lGgF8OSYD7xJLJboenGOZg9cpDQu+5I+bzdl4+mlfZ4IxOU8rmgfzFtgfvSJY5Giqzfvkbt1RJDbfiMcBa1paI5jEqzFB/qgX5S1FV2ZuEn2Q/0eqdpRhVbzcDwZHO6Hvu2spejy57/I4yDIeOfEcQjOLvw0HxURx1x5sY7cBYD7on8rM4qufMM7vGKvPLsggWch8u4giZVXYuVcik98pg1Af+gwWZPoeT5T8khAMJpLCMGhOfz0EjQxrTULCaDW2+dBB/SErUE0vr2ZbSkukM2loD3CTy/RYryTmMs47hjIU+vSLxbw5QzfVRpEFw6O+8nytiZ3zb/3skB56QElNIip3Q5yFgHMhdutbr7o6m2b7FVvBA3Z28vk4zjNHnGx5sWCNTkO1iXwQfUr0ADkmOKtsHIvzWsPIF907uXTXsNAjD4XIperNXgNy4MPYXNO8Z1LNH87TYXUhIgtBqBPmRBd/cMRnwbNOwXEZntPUPn8dUGsDPPMzuNi3ReBGt2HY6Z11gedMCG6MDxOdhdfYiaGR7LdJYXo8bBXDZzuIZq7dEsQmqxer1OF1+0NB/2aTjA7NC74LLwmulsOUxpiICQC4Rxn4xDvgCvIogx5djcL1zkgKObY2XyYSWpkzd+4Kx8k3qIvyhuruA4/xr7yw5QnKZ4h3xeTENBZvfEPWaUPr5DTtVcAXzR4KRa+MR5G/oWTuPaenJjG+ahTG5IUxbHvyZp57Sw52GkGPo0YQ5QXg1efUsUUKl9NekqSWeXrSZ9TbU7D2ARvHXqt7LNHyVnJ92cdSPDGWEvzHF7Pc1bto9r0jCcjmVXv5YM+CQG9lrtpWD5UdPDtRY0dPa7BWT1A9ULFk5HMUIf3CsGlbUQcQK+F91ebd82+jwEvwAn+2AQWvWaAKOYvjSbjOnu1JzohoNdy7n/TuBiJhe401xt5o8Cba4li7HIS4IOu2b+wneZ6wWPibwMcS8vtOSSLE8B5gLF2YaJRDx4TfztAr5XbcZyL+xPDXT9E9cq8pyKZoQ71Jt4oZHcc4/t03wUZeLA5oQH6Oo9ndp33JHRmqA9z+mMTvPXZXRfIKp/8UQZiwIbny5p/9VOq5Ute+84M9eABn+CNidInV/ndY/Ie374G+VYyEAmbUTpzTby1LYaBB3zgNfVrAuvEb0aLanXKPjUqha/mLwd8u3H3ISqfukblc9cFSmd/6ngMHvAZ+xjG2e2jVMdbHj4xfmn4CQngrg3FeJ595j1+PzhHs/u+EB5zxPW8prqYKKYuiSskRNf+zlKGv80gE1h3IPD62LSuxQojE3zNBW9gPEc8Tr3vDevQV/0rIyj934izuz8LCjrF+mEqfXzVf1LCY464MT8BoE+ZL7r6p0suny/34YPx8QhfnVDMge85Qtmnjwov5mEY6tqCdem/jnzRsOLot+Q+yoQgbQeVo+dG1Zlyo2oAzoEu3RpE18tzlOv9QJL9T5DrHWNdjU/eBtGw6pRDmSdT8hy2wgY+RrpPipj10AE9YWsSDZu7MkWZzW9JUhO6Dzf6pIhRj/7QYTKjaFhl4ha5EA7i/xrcF/1bWUvRsDn+uZ/dNkruRibSselIo0+KNvWZre+Kvu2srWgYzlTu+Y/49sW7jiY6TLE4aMGFPtWp6D9+IkUL4/ff4rHLlHl8RDZcZIAX/OgTx+KJ9gyP+0L/RW6SokzP25R5jAEfHptgymUe8IE3iSUSrax2Jyt2JrdzjDJbRqSIuOD8PNehvnY3mVhlHYn2jV9r8Wd8+dzPVBgcp5kXT1PuueOU5S9T5omU8JgjjnXkIR91nRvRv9y0+ZeVwccXAAAAAElFTkSuQmCC"
const search = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAgISURBVGhD1Zn5UlNJGMXzImr5Em5Vvoj6KC7/OTUyLsyIirjhhijLsEZIJEBIICtZyUISIIRVSNx3PdOnZzrV3FzgOsiU01XHGy6Ivz739Pd9ibaPHz/i/fv3+PDhA/iaV4r33r17J69v376t6tWrV1IvXrzA+vo6nj9/jtXVVXn98uUL/otlU4BGYCWC6yL469ev8fLlS1QqFQm7tLSEQqEgN/NfgEtoHdYIrYOr1wR/8+aNBKfbi4uLyGazchOfP3/edfCq05tJARulHC+Xy9LpVCqFtbU1Cbzb4FWnFaDxqgAp9bW6R2i6S+ipqSmsrKxUgT99+iRf78aqcVrfwFZSEeGBJHQikZAx4d9V4LwS/kcvmw6sZAapSzmvQ8fjcSwsLMj7/B264z8afAM0gcygFaRRhFbxIDSdVt/bTXAJbYRkVnWp2qzfIzCvhF5eXpaZJry+KUZtN8BtRmBqZmYG09PTNcrlclJ8rTbBePAAsuTxPus1f0Z9nc/nMTs7i2KxiFKpJDez02XqtO6Wmeiycpq1mg1mfn4e6XQakUgEwWAQPp8PExMTVfn9fnk/mUxK53eyTJ2mtoI1QrNWs5XzINJV5TadzmQycjOEpVjPadROlmWnjcAKmjFRLZ3NRc0ijAyzzsPJp6BvhlnfydrgtBkstRmwkgJnvpW4CbZ4boSb4AaYaWZ7pwfSRqjvcZfSgRW0Lm5AbULB8wnQfVaYHwJtFE88s7idmNXtxLzrrhP8h0ObOUsZ3bXqsILVo8LavZO1AdoqLGWEJShdZQyYX1VJ2CnHx8fhcrnw7NkzuN1u+SR34nYV2iqwDquA9ZKnGhPr9fDwsIT1eDyyVhN+ZGQEfX196O7ulhH7+vXrPyjWl80MlrICTHf52OksYdnKOe0RzuFwwDnkwpDbA+eoB45hNxyuEQw+G8Kgw4mhoSEJTue/Ny410FZgdWDWYdbeaDQqOx4henp78dTlxkggAk84Dk8oijF/GG5fEF5/CBOBEBwCvq+/Hz09PdL973F8A7SCVNXDrBoosbtNTk7KRz84OIiBgQGMjY2hrb0dXY4RuAIxjARjGA1GMeILwx+dwkQ4JuBDGPMF4AtNwu0dlxvs6OiQT8jqktC6q0pm7urVgRlmh6PDzOvo6Ci6urpQ39SMc413UHftNs5duYlfL1/HL/VXEUpmEcsWEIgmJbh7wg9/OIKAgO8SMWl9/FieLSvLFHorYIqxYGtmhjkI8cAxo509fRiN5zA+VYAvNYNAegZBoVAqj+mFVUzPLyORm/0bXETFIxzPFmbR22/H4ydPZKWxsmqgtwNm/aXLjBDjQZdZIbpFNl3+COKlMpKLFaSXKsgITS9XkBcqLJdRWFqX4HHhOKMyOu5HMpODT2ScTjMqVpaNUFZgKVWLefiYa7pMaKeov21tbfBlioiVKkgsVDClgy+VBbiAluBrSM+WEEqk5cGMJtOIpzJoefQId+/ds1RJbN8DrCoGo8FHSeBAICAPIaGDhWVEBXRcQCvw1GJZgJer4Hnhdla4HUnn4QlGMCmgE+lptLS24npTk6UJsAaagCxhxmqhxFNOh9ndelnanj6V11bxjwbyS4gIaILHREwSC2UBXkZaA88RurSCaHYGXhEROh5JZnD/4UM0NjbKT7q2WzIeOrCZu0rMM+eHubk5WTXYRFibHU6nfLzeZB7h+Qom58sCvCzzLcGFUovryAhlBXR6fhWR7Kys4SEB7A1OovnuXdy8dQvfvn37B23zVYXeDliH5kwci8UkNOMxLJqDrM8DomEEUuj3TwklYfclYJ+ICUURm1utgk8VVxBKF+AOxRBMZNDzdBC3bt9Gr2jvVpbNKqwSM81hns2FmaYiwnVC32luxq0/HWjsFGofwLU2O64+7sXVR90I5heF4wK4tIbYzCJ8yRyGA1HpNvN84eJFFMQoYGXZCGUVWEGzerBj0mWv14twOAyniMgDkcuHT9rhK6wiWCwjXFwXUVlHVChWWkec17kVBLNFjEXScI6H0dlrxzWR5fsPHlh+w1t12gowxZLHQZ4DEnNNaMaEU11HR6d8zM0trfBmFhAS0BJcKFJcw+Ss2ExuAZ5EDg5fRMTCgaYbN3C5oUG+o7G6pNNGsXqodydmMwg7ISE5a7Dcceix2+1yBqFjPFB/CJAn/U6MJmfgF87788sYz5QwHMmgz+VBa1u7hD1/4QIaxJUTX2dnp6VWXgOtO0oxDkbxMHIc5ZDPEsjPOLgBus5yyFmCjaLhyhXU/XYel/64jIbGJqHrErT+999x8dIlGad5cT5ui6dz9OhRnDhxAidPnpTvWbdaVWg9AroUvC4dnDFRtZsTnxr4OY/wCbA9031u4p4QS6Nd1HY2J/4uNhNWov379+PIkSOWwG1moJQRlDI6zrdWPJTqDUAoJGZlAUxwOq/ECZDik2BdZ8mkUQRWc/QjsZl9+/ZVwU+dOrUpeA20GSxlBKboNsF5iAjCs6DmbMLRfYqveY9PRP03B98jGgd/dlWCHz58eEtwGY9/C6ykPtOg64TnnK0+EqPUB5PspKzx/FRrs85H8L179+LQoUMS/PTp0zXgVaetwlI6sC4Fz6zTfW5CiV/zPr+/3SSngx8/fhxnzpzZAG6aabMNUGYbUDLbhC5uSL22Mn4y4wQ/ePBgDbhN/vmTLoLv2bNHgh87dgz19fXy/k8NzdXS0iLBDxw4gLq6Onnvp4fmYrc9e/asjBbX/wJ64wL+AmRMjN0/4942AAAAAElFTkSuQmCC"

createReport({
	data: {
		list: ["alert", "search"]
	},
	additionalJsContext: {
		alert: () => {
			const data = alert.slice('data:image/png;base64,'.length)
			return { width: 17, height: 7, data, extension: '.png' }
		},
		search: () => {
			const data = search.slice('data:image/png;base64,'.length)
			return { width: 17, height: 7, data, extension: '.png' }
		}
	}
})

and here is the code found in the docx:
+++FOR item IN  list+++
+++IMAGE $item()+++
+++END-FOR ietm+++

I hope you can understand my question. Thank you

**Comment by jjhbw** [comment]
You seem to be iterating over an array of strings `["alert", "search"]`, not functions.

You seem to want this (so without the FOR loop):
```
+++IMAGE alert()+++
+++IMAGE search()+++
```

**Comment by changhaojun** [comment]
additionalJsContext: {
		alert: () => {
			const data = alert.slice('data:image/png;base64,'.length)
			return { width: 17, height: 7, data, extension: '.png' }
		},
		search: () => {
			const data = search.slice('data:image/png;base64,'.length)
			return { width: 17, height: 7, data, extension: '.png' }
		}
	}

The above two methods are obtained through traversal. For your convenience, the data is specially written as known

**Comment by changhaojun** [comment]
Does the image method name in the template support variables? If so, how to write? thank you

**Comment by jjhbw** [comment]
@changhaojun something like this? https://github.com/guigrpa/docx-templates/blob/f6173b706a95924bddc31351cdcf86960f5f8525/src/__tests__/templating.test.ts#L692-L711

You can find other examples in the `__tests__` directory.
