### ISSUE TITLE
change build output for for example direct browser support

### ISSUE THREAD

**Issue by mathe42** [guigrpa/docx-templates#231]
I think it would be nice to provide a dist file wich runs directly in browser from for example `https://unpkg.com/docx-templates@4.7.0?module`. unpkg is cool as it rewrites imports to modules with real urls.

If interessted I would create a PR adds some build scripts to add a esm output in the next days.

This would be completely seperated or can be added in the package.json module field.

**Comment by jjhbw** [comment]
That'd be great. I'm not really familiar with that space, and every time I have to work on toolchain stuff I feel like throwing my computer out of the window.

We had some problems before in creating a 'pure' browser build that is ready to use, as some deps require pretty advanced polyfills. Maybe related: https://github.com/guigrpa/docx-templates/issues/135.

**Comment by jjhbw** [comment]
Implemented in 3d6c1a8c5f33868c8f40e9996a2fa0db0889f86a
