### ISSUE TITLE
Adding colors and fonts  dynamically 

### ISSUE THREAD

**Issue by Bounguicha** [guigrpa/docx-templates#234]
Hello, Can i add colors or fonts dynamically in the docx by adding their codes in the JS file ?

**Comment by jjhbw** [comment]
You can look into directly inserting XML, see the `literalXmlDelimiter`.

You'll need to find the correct XML for the things you want to do in the docx reference http://officeopenxml.com/WPtext.php

**Comment by Bounguicha** [comment]
@jjhbw Hello can i use XML on libraOffice or google docs ?

**Comment by davidjb** [comment]
As an example, setting the text color can be done with the following literal XML and standard delimiters:

```xml
||<w:rPr><w:color w:val="00FF00"/></w:rPr>||
```

This string can either be attached to your `data` object and referred to directly in your template (e.g. `{{ validColor }}` if set as the `validColor` property), or else returned as part of a result of an `additionalJsContext` function (which could, for example, take arguments to make the color change based on other variables).
