### ISSUE TITLE
Table is not populating 

### ISSUE THREAD

**Issue by purusingh** [guigrpa/docx-templates#236]
I am trying to create table on worddocument and it is not woking

<code>
const { createReport} = require('docx-templates');
const fs = require('fs');

var template = fs.readFileSync('./23.docx');
const data = require('./data.json');
createReport({
  template,
  cmdDelimiter: '+++',
  data: data
}).then(res => {
  fs.writeFileSync('report.docx', res);
})
</code>

<data>

{
    "name": "Purushottam Singh",
    "employees": [
      {
        "firstName": "Derek Clark",
        "lastName": "Marketing director"
      },
      {
        "firstName": "Xue Li",
        "lastName": "Financial director"
      }
    ]
}
</data>

<template>

Here is table
+++FOR employee IN employees+++
--
+++= $employee.firstName+++ | 55
+++ END-FOR employee++

</template>

**Comment by jjhbw** [comment]
Your example is messy. Please provide an actual template with executable code.

This functionality works just fine in all cases I could think of, so please take some extra care in creating a reproducible example of your problem.
