### ISSUE TITLE
Can i  set XML code with literalXmlDelimiter using libraOffice or google docs ?

### ISSUE THREAD

**Issue by Bounguicha** [guigrpa/docx-templates#237]
When reporting a **bug**, please provide:
- A small reproducible example consisting of the code and .docx template you used.
- A screenshot of the result you get and an explanation as to why this result is unexpected.
- Information about your compiler toolchain version (e.g. Angular, Webpack, etc.).
- Information about your runtime environment (which browser, Electron, or NodeJS version).

**Comment by jjhbw** [comment]
You're going to have to test this on a case-by-base basis. Google Docs and LibreOffice interpret the docx specification in subtly different ways. Nothing that this library can do about that.
