### ISSUE TITLE
listCommands not picking up variables e.g. +++INS variablename+++ when it is located in the header and footer

### ISSUE THREAD

**Issue by samibarasi** [guigrpa/docx-templates#239]
When using the listCommand function I don't get the expected variables listed that are defined in the footer and header portion of the file. 
![Bildschirmfoto 2021-09-26 um 12 06 34](https://user-images.githubusercontent.com/81765912/134803500-97e479a9-c939-4d46-a8c4-8b4a87b36beb.png)
![Bildschirmfoto 2021-09-26 um 12 08 08](https://user-images.githubusercontent.com/81765912/134803497-f8d4403f-51f0-42b8-9ef7-97e97459e59f.png)

I have to workaround this issue with setting an ALIAS in the content area for every variable set in the header or footer to get them appear in the list of variables.
![Bildschirmfoto 2021-09-26 um 13 56 25](https://user-images.githubusercontent.com/81765912/134807076-4756bdbe-5001-4d9b-9656-7a6cb395db05.png)
![Bildschirmfoto 2021-09-26 um 14 04 56](https://user-images.githubusercontent.com/81765912/134807128-9dc03324-d9e6-468d-b0d3-031b1e7e5384.png)

**Comment by jjhbw** [comment]
Thanks for reporting. This is indeed a bug. The `listCommands` function only looks in the main XML file, not the ones that cover the header and footer.
