### ISSUE TITLE
Text Watermarks

### ISSUE THREAD

**Issue by iainfreestone** [guigrpa/docx-templates#24]
Hi,

Is there any way to add a Text watermark? I have tried adding the literal XML for the watermark and I get an error in document.xml which I think is due to the watermark being located in one of the header.xml files.

```
<v:shape id="PowerPlusWaterMarkObject200378111" stroked="f" fillcolor="silver" o:allowincell="f" style="position:absolute;margin-left:0;margin-top:0;width:397.65pt;height:238.6pt;rotation:315;z-index:-251657216;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin" type="#_x0000_t136" o:spid="_x0000_s2049">

<v:fill opacity=".5"/>

<v:textpath style="font-family:"Calibri";font-size:1pt" string="DRAFT"/>

<w10:wrap anchory="margin" anchorx="margin"/>

</v:shape>
```

Also if I set a watermark manually in Word in my template the generated document errors on opening.

Any help would be greatly appeciated.

Thanks

**Comment by guigrpa** [comment]
Thanks for the reporting, I'll look into it!

**Comment by guigrpa** [comment]
Fixed in v2.5.2. Please re-open if needed!

**Comment by GiordanoArman** [comment]
@guigrpa would it be possible to allow setting a watermark from the library, without setting it directly in the word template?

**Comment by mathe42** [comment]
I don't think that this is possible. For those special use cases you can create your own code:

1. filledDoc.docx -> unzip (maybe only in memory not in filesystem)
2. Change the corresponding file (I think as of @iainfreestone this should be located in a  header.xml file
3. create zip all into a new file filledDocWithWatermark.docx

Hope this helps.

**Comment by ThierryMangin** [comment]
Hello,
I am reopening this post to complete the request. Is it possible to act on the watermark with js code?
For example by testing a variable to display the watermark or not.
