### ISSUE TITLE
HTML Images not working on Word - Office 2013

### ISSUE THREAD

**Issue by Ademking** [guigrpa/docx-templates#241]
Images in Office 2013 are not showing properly. 
(The same file works on Office 2016 +)

My template is using HTML code
Example: 
```html
<!DOCTYPE HTML>
<html>
<body>
<div>
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
</div>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/12462188/134999654-99a06f55-3407-42d1-a8f1-044f8a1b2c28.png)

Any idea how to fix this issue?

* Runtime environment; NodeJs
* Version: 4.8.0

**Comment by jjhbw** [comment]
Looks like a correctly formatted base64 dataURI and HTML to me. The fact that it _does_ work in Office 2016 suggests that this is an MS Office issue, and not something we can solve. You can try searching the internet to see if HTML like this is even supported in Office 2013.
