### ISSUE TITLE
Question: Dynamic image size

### ISSUE THREAD

**Issue by mdsjs** [guigrpa/docx-templates#243]
Thanks for great library!
I just confuse when implement display image, the example/option should be put value for option width & height. 
Any clue how to display actual/real width & height image?

Thanks!

**Comment by jjhbw** [comment]
Not sure I understand your question. How to specify image dimensions is described here: https://github.com/guigrpa/docx-templates#image

What exactly is unclear?

**Comment by mdsjs** [comment]
hi @jjhbw , thanks for the reply.
Yes, i saw the example and mention about this:

> The JS snippet must return an image object or a Promise of an image object, containing width and height

So there is possible if i don't set any value for width and height? so whatever image size it will responsive added

**Comment by jjhbw** [comment]
No, docx-templates cannot render the docx documents the way that e.g. MS Word or LibreOffice can. Hence, it can never know how big an image needs to be to fill the available space.

I may be wrong, though. If you can find the corresponding XML tags in the docx spec to insert an image with responsive dimensions i'll be happy to look into it.

**Comment by mdsjs** [comment]
ah ok, thanks for the explanation. Cheers
