### ISSUE TITLE
Rendering image with html unexpected token for auto generated tag.

### ISSUE THREAD

**Issue by apsisx** [guigrpa/docx-templates#245]
Hello, I have an issue for parsing img tag from server.
I created array for image like `<img src="' + canvas.toDataURL('image/png')+ '" />` in node.js backend.
This gives me base64 src url. 
The tag is like 
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA....."/>`

I used in template like
<code> +++FOR item IN $question.isCreatedData +++
+++HTML
< html>
< head>
<metacharset="UTF-8">
< /head>
< body>
+++IMAGE $item.canvas+++ 
< /body>
< /html>
  +++
+++END-FOR item +++
</code>
When I insert in loop url, it gives me the error unexpected token like 
<code> command: '</body> </html> `',
    err: Error: SyntaxError: Unexpected token '<'</code>

**Comment by jjhbw** [comment]
You are feeding HTML to the `IMAGE` command. The `IMAGE` command only accepts javascript objects structured like 

```{ width: 6, height: 6, data: 'image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA.....', extension: '.gif' }```

See https://github.com/guigrpa/docx-templates#image.
