### ISSUE TITLE
Header/Footer images messing up the page itself

### ISSUE THREAD

**Issue by ItamarShDev** [guigrpa/docx-templates#25]
When using a Header with images and adding images in the page itself -> the first image in the page layout will be identical to the header image.

When using a Footer with images and adding images in the page itself -> all the images in the page are replaced with the footer images.

**Comment by guigrpa** [comment]
Could you share why this has been closed?

**Comment by ItamarShDev** [comment]
Actually closed it my mistake

**Comment by ItamarShDev** [comment]
@guigrpa notice that I have updated the issue to the real bug

**Comment by guigrpa** [comment]
Thanks for reporting the bug!

**Comment by guigrpa** [comment]
Shipped in v2.5.1
