### ISSUE TITLE
for iterator in a table creating empty column

### ISSUE THREAD

**Issue by fernandomoraes** [guigrpa/docx-templates#250]
What I am doing wrong?

![image](https://user-images.githubusercontent.com/2366763/146482989-d00275f5-a247-4279-a558-0866c6853738.png)

is resulting in:

![image](https://user-images.githubusercontent.com/2366763/146483063-6def3912-0018-4f35-b31f-512a9149c47e.png)

**Comment by fernandomoraes** [comment]
Solved:
![image](https://user-images.githubusercontent.com/2366763/146484898-44758d00-320e-45f4-be99-c987cc628a30.png)

**Comment by jjhbw** [comment]
Thanks for posting the solution!
