### ISSUE TITLE
Error anytime the delimiter is found within a file.

### ISSUE THREAD

**Issue by WrightLiam** [guigrpa/docx-templates#251]
I am running into an issue similar to that defined in item #216.

To give a brief summary, it looks like every time the createReport function finds a delimiter it tries to run it as a function. ie:
ERROR Error: Uncaught (in promise): Error: Error executing command 'OFFENSEDATES': OFFENSEDATES is not defined
Error: Error executing command 'OFFENSEDATES': OFFENSEDATES is not define

As a note I made some modifications to the TSCONFIG file and manually installed vm and stream to get it working. And as you deduced in your earlier question I am using Angular

I've created a streamlined version for you to check out on stackblitz through the below link. For ease of access I've added in the word file as an array directly into the app.component.ts file though I have confirmed it works when the program fails to find any delimiters. 

There is a commented line in the createReport function where it changes the delimiter from the default +++ to a custom delimiter that is absent from the word file.

https://stackblitz.com/edit/angular-ivy-x5bmbj?file=src%2Fapp%2Fapp.component.ts

Thanks in advance for your time and any help/direction you can provide.

**Comment by jjhbw** [comment]
Thanks for the detailed example.

> createReport function finds a delimiter it tries to run it as a function
No it executes the 'command' between the delimiters from within a Promise. It interprets everything between the delimiters as JS code and executes it. Eyeballing your example, I see `OFFENSEDATES` is not injected into the VM. I only see `offenseDates`, which is not the same. Capitalisation matters in variable names, just like when you are writing plain javascript.

Let me know if this solves your issue.

**Comment by WrightLiam** [comment]
Well I'll be damned, you're right that was it.

That was the first thing I tried to test when I first started getting the bug and I thought I had the same casing on both in my original tests but I clearly must have made a mistake. 

I both apologize for wasting your time with such a silly mistake and also thank you for pointing it out!

**Comment by jjhbw** [comment]
No problem at all, happy to help 👍
