### ISSUE TITLE
Is it possible to convert docx file to pdf?

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#252]
Is it possible to convert docx file to pdf ? If not how can it be done ?
Thanks

**Comment by KAVA-Leigh** [comment]
> Is it possible to convert docx file to pdf ? If not how can it be done ?
> 
> Thanks

I'm not affiliated with the project, but have been using docx-templates for quite a while.

There is no functionality for conversion in place, so you will need to either use
- An open source library (I have reviewed & tested a huge number & they generally don't render complex documents correctly - for basic invoice templates etc, they are likely fine)
- I would suggested taking a look at Cloudmersive. It isn't open source & is a paid service, but there is a free tier & they have a huge library of API's for a whole number of tasks.

**Comment by mathe42** [comment]
Have a Look at https://www.npmjs.com/package/@ec-nordbund/docx-templates-to-pdf wich uses gotenberg (Install that via dicker) See https://github.com/gotenberg/gotenberg

**Comment by jjhbw** [comment]
Thanks for your answers @KAVA-Leigh and @mathe42 !

Docx-templates is concerned with creating docx files. To turn docx files into PDF files you need a docx reader like Microsoft Word or LibreOffice.
