### ISSUE TITLE
insert references

### ISSUE THREAD

**Issue by DeveloperOl** [guigrpa/docx-templates#257]
Hi @all, thanks for this awesome software.
I was wondering if it is possible to create a dynamic reference inside the document with a custom text. For example a reference to a headline, which directs to the underlying headline when clicked.
Is it possible to this in the current state?

**Comment by jjhbw** [comment]
I'm not really a Word power user so i'm not sure exactly which functionality you mean.

You can try by wrapping the reference you want in an IF statement to conditionally render it.

**Comment by DeveloperOl** [comment]
Sorry maybe that was not clearly stated. I mean the cross-reference function in word. A cross reference is like a link in the same document, e.g. to a headline.
So in a text blob I can have a link "click ->here<-" and when clicked it directs to a chapter in the same document, not an external address.

**Comment by jjhbw** [comment]
There is no convenience command to inject such a link.

You can take a look at injecting raw, dynamically generated (i.e. in JS) XML literals into your template. See README on how to do that. You'd have to find out yourself how the XML for the links you want looks, though.

Alternatively, you can try something like the below in your template.
```
+++IF condition_a+++
<another link in Word to e.g. headline 2>
+++END-IF+++

+++IF condition_b+++
<another link in Word to e.g. headline 5>
+++END-IF+++
```

Does that answer your question?

**Comment by DeveloperOl** [comment]
@jjhbw I will have a look into the XML documentation. Is there a good reference/documentation for the literal XML? The readme is really quite on that topic

**Comment by jjhbw** [comment]
Yes the README doesn't cover it because it is out of scope of this library. The docx spec is simply too large to make abstractions for everything, see http://officeopenxml.com/anatomyofOOXML.php

**Comment by jjhbw** [comment]
Hope this helped. If not, feel free to reopen.

**Comment by jjhbw** [comment]
Thanks for posting your solution, much appreciated!
