### ISSUE TITLE
Use nested data problem

### ISSUE THREAD

**Issue by AlexandrKravchenko** [guigrpa/docx-templates#258]
Is it possible to process my keys in moment? Need this for process nested data.
I have template vars like this: 
```
{user}
{user.name}
{user.age}
```
And data:
```
user: {
 name: 'Alex',
 age: 23,
 country: 'Ukraine'
}
```
And want result:
```
Alex, 23, Ukraine
Alex
23
```
I see three interesting features to resolve issue:
**first:** add .toString method to object (user), that call when  use {user} key in template (if object has toString, than ObjectCommandResultError not appear)
**second:** add functions aliases, that calls additionalJsContext functions. like if i put {{{user}}}, than i get result of additionalJsContext.getByKey(key)
**third:** if typeof data === 'function', that function receive 'key' parameter, and than can process it async and return result

At this moment i use this construction, but its to scared :DD.
Template:
```
{v(`user`)}
{v(`user.name`)}
{v(`user.age`)}
```
Code:
```
additionalJsContext: {
      v: async key => {
          let fieldValue = calculateFieldValue(key, documentData)
          return fieldValue
      },
  },
```
**And again as conclusion of 2 global problems:**
- i cant use object string representation and object nested fields at one time.
- i must to know about all fields in template before render it. But i want to get needed data in moment, where i get key, and then put it into template

**Comment by jjhbw** [comment]
To see if I understand your question correctly, you have this data
```js
user: {
 name: 'Alex',
 age: 23,
 country: 'Ukraine'
}
```
And you want this command in your template
```
{user}
```

To result in 
```
Alex, 23, Ukraine
```
Is that correct?

Assuming I understood correctly:

That isn't supported, because there isn't a single agreed-upon way to serialise an Object to a string.

You want it to look like result of `Object.values(user).join(', ')`, so I suggest you just use this.

Let me know if I misunderstood anything.

**Comment by AlexandrKravchenko** [comment]
> 

No, join() is not allowed. I use {user} as example for reproduce similiar task. My real problem - is ability to process each template keys directly before inserting.

**Comment by jjhbw** [comment]
You can use the `listCommands()` function to list all commands in a template. See https://github.com/guigrpa/docx-templates#inspecting-templates

Is that what you mean?

Note that template commands can contain a JS code snippet of which the result will be inserted into the rendered report.

Putting the below inside your template 
```
{Object.values(user).join(', ')}
```
will produce 
```
Alex, 23, Ukraine
```

**Comment by AlexandrKravchenko** [comment]
> You can use the `listCommands()` function to list all commands in a template. See https://github.com/guigrpa/docx-templates#inspecting-templates
> 
> Is that what you mean?
> 
> Note that template commands can contain a JS code snippet of which the result will be inserted into the rendered report.
> 
> Putting the below inside your template
> 
> ```
> {Object.values(user).join(', ')}
> ```
> 
> will produce
> 
> ```
> Alex, 23, Ukraine
> ```

Yes, when i use listCommands(), i get it, but i cant process it step by step inserting data.. :)

**Comment by jjhbw** [comment]
Template commands can contain arbitrary JS code, meaning they are _very_ flexible. I still don't understand what exactly it is that you want to do that isn't possible yet.

**Comment by mathe42** [comment]
I'm also not shure what you want to do but with a Proxy you might be able to accive what you want - as you want to transform your data on the fly. But I would think transforming it before calling createReport is much simpler.

**Comment by jjhbw** [comment]
Hope this helped. If not, feel free to reopen.
