### ISSUE TITLE
JavaScript proxy in additional context

### ISSUE THREAD

**Issue by jcalfee** [guigrpa/docx-templates#260]
Is it possible for additionalJsContext to capture a generic getter or setter from a proxy?

I'm providing:
```js
const additionalJsContext = new Proxy({}, {
  set(obj, prop, value) {
    debug('set', {prop, value})
    obj[prop] = value
    return true
  },

  get(obj, prop) {
    const value = obj[prop]
    debug('get', {prop, value})
    return value === undefined ? null : value
  }
})
```

Then merge is used in this example [[ref](https://github.com/guigrpa/docx-templates/blob/28496607960efab8619ca006256d1d50fe5c0c7e/src/jsSandbox.ts#L21-L29)]:
```js
  const sandbox: { [ind: string]: any } = merge(
    ctx.jsSandbox || {},
    {
      __code__: code,
      __result__: undefined,
    },
    data,
    ctx.options.additionalJsContext
  );
```

The generic "get" and "set" are not being merged into the sandbox object.  If I put static properties in the 1st argument to Proxy it works or if I test my proxy alone `additionalJsContext.anyprop === null` it works.  I'm not concerned about Proxy immutability, I can handle that with the `set`.

I'm have asked on the timm project too: https://github.com/guigrpa/timm/issues/52

This may be better handled here.  Looks like using `data` instead will not help either.  I'm also after the async support in additionalJsContext.  Also, if you have a suggestion I don't mind forking making changes and testing.  I anticipate that I'm going to need to do this anyways.

**Comment by mathe42** [comment]
Just looked at the timm code and a work around should be:

```js
const additionalJsContext = {
  key: new Proxy({}, {
    set(obj, prop, value) {
      debug('set', {prop, value})
      obj[prop] = value
      return true
    },
  
    get(obj, prop) {
      const value = obj[prop]
      debug('get', {prop, value})
      return value === undefined ? null : value
    }
  })
}
```

Where the key is not present in data. (and is not __code__ nor __result__)

**Comment by mathe42** [comment]
I might have a solution for that... But that will not work in IE.

**Comment by mathe42** [comment]
OK I wrote some prototype code:

Let oldMerge be the current merge function and replace it with this new one. Did not test this code in any way so expect bugs!

```ts
const supportsProxy = 'Proxy' in window

let oldMerge: (...args: any[]) => any


function merge(...objects: any[]): any {
  if(objects.length === 1) return objects[0]

  if(!supportsProxy) return oldMerge(...objects)
  // Even if non root objects are Proxies run proxy version as this makes it posible to have proxies as values.

  return new Proxy({}, {
    // Not needed Traps
    // apply?(target: T, thisArg: any, argArray: any[]): any;
    // construct?(target: T, argArray: any[], newTarget: Function): object;
    // getPrototypeOf?(target: T): object | null;

    get(_, key) {
      const obj = objects.filter(v=>v instanceof Proxy || key in v)

      if(!obj.some(v=>v instanceof Proxy)) return oldMerge(...obj)

      return merge(...obj)
    },
    getOwnPropertyDescriptor(_, p: string | symbol) {
      const obj = objects.filter(v=>p in v)

      if(obj.length !== 1) return

      return Reflect.getOwnPropertyDescriptor(obj, p)
    },
    has(_, p: string | symbol) {
      return objects.some(v=>Reflect.has(v, p))
    },
    ownKeys() {
      return objects.flatMap(v => Reflect.ownKeys(v))
    },
    set(_, p: string | symbol, value: any) {
      const obj = objects.filter(v=>v instanceof Proxy || p in v)

      for (let i = 0; i < obj.length; i++) {
        const r = Reflect.set(obj[i], p, value, obj[i])
        
        if(r) return true
      }

      return false
    }
    // Did not thought about these traps that are some quite specific use cases... What will delete do? delete it from all current objects?
    // isExtensible?(target: T): boolean;
    // preventExtensions?(target: T): boolean;
    // setPrototypeOf?(target: T, v: object | null): boolean;
    // defineProperty?(target: T, p: string | symbol, attributes: PropertyDescriptor): boolean;
    // deleteProperty?(target: T, p: string | symbol): boolean;
  })
}

```

**Comment by jcalfee** [comment]
Wrapping it in a key works.  That opens up the option to report missing keys in the template or run more dynamic async code.  So that is a really good work around.  Of course means the prefix will need to be used in the templates.

> What will delete do? delete it from all current objects?

In the original `merge` returns an immutable object 

That new proxy looks interesting.  I did this:

```js
function oldMerge(...args: any[]): any {
  return merge(args)
}

function proxyMerge(...objects: any[]): any {
 //...
```
And adjusted the recursive call in "get" and plugged in `proxyMerge`..

There is an error here:
```
              var obj = objects.filter(function (v) { return v instanceof Proxy || key in v; });
                                                               ^
```
> TypeError: Function has non-object prototype 'undefined' in instanceof check

Accounting for undefined did not work:
```
             var obj = objects.filter(function (v) { return (v === undefined ? false : v instanceof Proxy || key in v); });
                                                                                          ^
```

**Comment by mathe42** [comment]
> And adjusted the recursive call in "get" and plugged in `proxyMerge`..

That is not needed (and will break). 

The error should be gone with that change and if not replace `v instanceof Proxy` with `(typeof v === 'object' && v instanceof Proxy)`.

**Comment by jcalfee** [comment]
Yea, I realized recursion didn't make since.  I'm still not sure what get should contain though.

**Comment by mathe42** [comment]
maybe
```ts
    get(_, key) {
      const obj = objects.filter(v=>v instanceof Proxy || key in v)
 
     if(obj.length === 0) return
     if(obj.lenght===1) return Reflect.get(obj[0], key, obj[0])

     // Dont have to deal with Proxy
     if(!obj.some(v=>v instanceof Proxy)) return oldMerge(...obj.map(v=>Reflect.get(v, key, v)))

    // there is a proxy so get them all and merge them (this allows Proxies to return Proxies or objects with values with proxies)
      return merge(...obj.map(v=>Reflect.get(v, key, v)))
    },

```

**Comment by jcalfee** [comment]
I tested `v.__isProxy !== undefined` [ref](https://stackoverflow.com/a/37198132) and it works when I replace the two `v instanceof Proxy` checks .  It errors `err: Error: TypeError: eval is not a function`.  Probably this line:
https://github.com/guigrpa/docx-templates/blob/28496607960efab8619ca006256d1d50fe5c0c7e/src/jsSandbox.ts#L49

**Comment by jjhbw** [comment]
Closing this because it seems resolved.
