### ISSUE TITLE
HTML content can't custom line-height

### ISSUE THREAD

**Issue by bigNeoneo** [guigrpa/docx-templates#261]
Thanks for your excellent project, but I ran into a problem. +++HTML `<body><ol style="line-height:50%;"><li>blah  blah..</li></ol></body>`+++   that just not work, the docx content's line-height is 1.0

**Comment by jjhbw** [comment]
You can check that the correct `line-height` style is injected in your document by unzipping the resulting `docx` file and doing a string search. 

If the HTML looks the way you would expect inside the document, then it is a problem with how your docx renderer (Microsoft Word?) interprets the HTML, not with this library.

**Comment by jjhbw** [comment]
In short; i'm afraid I can't help you with questions about how MS Word or libreoffice or google docs interprets embedded HTML.

Be sure to let me know if this doesn't answer your question!

**Comment by bigNeoneo** [comment]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/25142504/155642984-eea02f7b-21b1-473c-8bc7-f57832f8133d.png">
![image](https://user-images.githubusercontent.com/25142504/155643350-40d1e8e4-e3ea-46a9-be0e-7763e696eae9.png)
As you can see, the HTML looks good but the out docx's unziped xml not the correct height I want.

**Comment by jjhbw** [comment]
Can you post a reproducible example? The XML in the screenshot does not contain any valid HTML. The `<w:altChunk/>` element is empty.
