### ISSUE TITLE
Document unreadable when adding HTML to Header or Footer

### ISSUE THREAD

**Issue by pp-copenheaven** [guigrpa/docx-templates#263]
In this example i add HTML to a Header, body and Footer. Only the one in the body is shown. 

template file: 
https://filebin.net/ixb8zs4j5i1e0xvk

Tested using the HTML example from the examples

const template = fs.readFileSync('test.docx');
const buffer = await createReport({
  template,
  cmdDelimiter: ['{', '}'],
});

fs.writeFileSync('final.docx', buffer);

**Comment by jjhbw** [comment]
Are you sure that's supposed to be possible? HTML in the header of the image sounds pretty high-end. Maybe you can find something about that here http://officeopenxml.com/anatomyofOOXML.php

Note that this library is limited to the possibilities of the .docx file format and its interpreters (MS Word and the like).

**Comment by pp-copenheaven** [comment]
Thanks for replying, I was looking for a way to give some customization options programmatically by inserting some HTML and CSS from an application, but it does look more of a hack that anything else, but I gave it a shot.  The library is amazing as it is ofc and i appreciate all your work :)

Thanks for the link, I'll take a look
