### ISSUE TITLE
How to loop through JSON array with no parent object?

### ISSUE THREAD

**Issue by antipopp** [guigrpa/docx-templates#271]
How can you loop a JSON array without a parent object? Something like:
```json
[
  {
    "name": "john",
    "job": "plumber"
  },
  {
    "name": "kate",
    "job": "electrician"
  }
]
```

What should I use in the template?
```
+++FOR item IN ????+++
+++INS $item.name+++
+++END-FOR item+++
```

**Comment by antipopp** [comment]
It's a solution (and it's the one I'm currently using), but I was thinking to pass just the array to the data field (`data: [...]`), so I was wondering if there was some "data" alias/keyword to access the array.

This is because I'm building the JSON on a Go backend, where you generate the JSON by just building an array of objects with no parent prop. To add the "companies" prop I must make throwaway struct (object) to just name it.

**Comment by jjhbw** [comment]
That is not possible; the values of the `data` object are injected as globals in the VM scope when rendering the template, so they can be referenced from the JS in the template. You can't expose an unwrapped array like this; how would you reference its elements from the template scope? Every top-level global needs a name.

The solution you're currently using is the only supported way. Hope this helped.
