### ISSUE TITLE
Feature request/Question - Reorder part of DOCX

### ISSUE THREAD

**Issue by RoXuS** [guigrpa/docx-templates#272]
Thx for this awesome module!

We would like have some configured "part" inside the docx, something like:
```
+++PART 1+++
// Some text and templating...
+++ENDOF PART 1+++

+++PART 2+++
// Some text and templating...
+++ENDOF PART 2+++
...
// Some other parts
```
Then when we generate the docx we would like to reorder the parts, sometime PART 2 before PART 1 sometime no.

Currently, is there a way to do that?

**Comment by jjhbw** [comment]
No I'm afraid that that's not possible. The library is designed as such that you expose data and possibly functions to the template and write JS in the template to render the document.

Templates can contain pretty much arbitrary JS, so what you want is probably not that far away using some EXEC and IF statements.

**Comment by mathe42** [comment]
Workaround:
1. add the wanted Order in a "parts" fields in Data so 
```ts
createReport({
  //...
  data: {
    //...
    parts: [2,1,3]
    //...
  }
  //...
})
```

2. In template do something linke
```txt
+++FOR partID IN parts+++
+++IF parts == 0+++
 Some text and templating...
+++END-IF++
+++IF parts == 1+++
 Some text and templating...
+++END-IF++
...
+++END-FOR partID+++
```

**Comment by RoCat** [comment]
Thanks for the workaround, that seems to perfectly fit our needs

**Comment by RoXuS** [comment]
Great thx, that seems ok!
