### ISSUE TITLE
Include custom document properties in parsing

### ISSUE THREAD

**Issue by DeveloperOl** [guigrpa/docx-templates#273]
Hi, I was wondering if it is possible to include the custom properties file of a word document (stored in docProps/custom.xml)
It would be great to be able to generate these values dynamically as well.
Maybe you can give me some opinions on that topic.

**Comment by jjhbw** [comment]
Not at the moment. Im not really familiar with the purpose of that file. Inserting arbitrary metadata is best done outside of docx-templates. The purpose of this library is purely the templating part by writing JS inside Word file templates.

**Comment by DeveloperOl** [comment]
The file can be used to create custom fields, which can be included in multiple positions in the document. At the moment if you store a placeholder in the custom property it behaves very inconsistent.
If you do so, and store for example +++ test +++ in the document property it gets replaced in the word file when generated. But if you select the text and update the field (F9), it changes back to +++ test +++.

**Comment by DeveloperOl** [comment]
This feature would be useful for creating a value, which is used in multiple locations, but needs to be changed later. For example after changing the word manually, change the creation date mentioned somewhere in the doc.

**Comment by jjhbw** [comment]
This sounds like generic metadata manipulation. That is out of scope of this library. I dont think you need templating functionality for that right? This seems like something you change in the file after generating the report.

It should be relatively simple to build, but has nothing to do with templating functionality and I prefer this library to remain a sharp tool that does one thing well.
