### ISSUE TITLE
Embed multiple images in 1 documents

### ISSUE THREAD

**Issue by PhuocHoangMinhNguyen** [guigrpa/docx-templates#276]
I am working on Node to create a document with multiple images for the same attributes. For example:
- image: [{ image1_object }, { image2_object }], or
- image: { image1: {}, image2: {}}

Can you please give some hints on how to accomplish this? I have spent time looking at the documentation but it doesn't help.

**Comment by jjhbw** [comment]
What do you mean 'for the same attributes?' What have you tried? Can you give a more complete example of what you are trying to achieve? Ideally by showing me the desired result document.

**Comment by PhuocHoangMinhNguyen** [comment]
@jjhbw Thanks for your reply. Luckily I have found the solution for my use case with the help of "additionalJsContext". I think I will close this issue since it is not an actual issue with the package.
It is a great package btw !

**Comment by jjhbw** [comment]
Thanks for posting the solution and closing. Let me know if you have any other questions.
