### ISSUE TITLE
Special characters like in docx template

### ISSUE THREAD

**Issue by JonRC** [guigrpa/docx-templates#280]
- When I use a docx with a `?` character as template, it throws an error.

Erro: `Error executing command 'name?': SyntaxError: Unexpected end of input`

DOCX file: "your name is {name?}"

![image](https://user-images.githubusercontent.com/61638433/182244924-23629933-daa6-4eb7-8d10-358774064687.png)

CODE:
```JS
createReport({template, data: {name: "Jonathan"}})
```

- running on NodeJs 16.16.0 - Ubuntu

How can I use `?` and other special characters in a docx template?

**Comment by mathe42** [comment]
Why do you want a `?`. 

`name?` is not valid JavaScript so the error is expected...

**Comment by JonRC** [comment]
Becouse users will create the templates. They need to write a question to be replaced.
For exemple, I have a user that want to use `{what is your name?}`

I'm wondering if I can disable the javascript feature and just use the replament feature.

**Comment by mathe42** [comment]
That is not possible. All between {...} has to be valid JS.

I never had user-provided templates. But you can create a list of valid fields where you can document the complete stuff...


Basicly what you need is a preprocessor-feature where you get the content between {...} and return valid JS code. (would be a hook into it here https://github.com/guigrpa/docx-templates/blob/master/src/processTemplate.ts#L476 )

I strongly sugest not to do this. But if you need it that would be your entry-point into implementing it.

**Comment by JonRC** [comment]
Greate.
I noticed that the Typescript Types doesn't have this key in `UserOptions`.
Is there a way to get the `processor` type?

![image](https://user-images.githubusercontent.com/61638433/182248129-24a96949-96eb-4351-99a5-f64f0ffb09ba.png)

**Comment by jjhbw** [comment]
Thanks for replying @mathe42 ! Closing this because it seems answered.
