### ISSUE TITLE
INS command doesn't work in header

### ISSUE THREAD

**Issue by hadestructhor** [guigrpa/docx-templates#281]
When reporting a **bug**, please provide:
- A small reproducible example consisting of the code and .docx template you used.
- A screenshot of the result you get and an explanation as to why this result is unexpected.
- Information about your compiler toolchain version (e.g. Angular, Webpack, etc.).
- Information about your runtime environment (which browser, Electron, or NodeJS version).

I have the following header in my template document with the same command at the end of the same page : 
![image](https://user-images.githubusercontent.com/60148800/186691706-98b35d85-7461-43f6-bc79-08bffb7b8053.png)

I get the following as a result for the header when downloading : 
![image](https://user-images.githubusercontent.com/60148800/186691836-088b3758-fddd-4850-a22b-b740095995d0.png)

Is it not a feature to work with the header/footer of a document or am I doing something wrong here ?

**Comment by jjhbw** [comment]
That should just work. I wrote an extra test for this just to be sure. Can you check what you are doing differently from this test https://github.com/guigrpa/docx-templates/blob/946cdad1feff1c4756d1585afa953ba8279db1ec/src/__tests__/templating.test.ts#L1187 that uses this template https://github.com/guigrpa/docx-templates/blob/946cdad1feff1c4756d1585afa953ba8279db1ec/src/__tests__/fixtures/insertInHeaderAndFooter.docx and report back?

**Comment by jjhbw** [comment]
Great to hear that it has been resolved. Thanks for posting the solution. 👍
