### ISSUE TITLE
Image won't display.  Why?

### ISSUE THREAD

**Issue by billmcknight1953** [guigrpa/docx-templates#282]
I have a Word template with the following Image tag:
`{IMAGE injectImage(analyses[0].images[0].data)}`

The associated function that creates the report from the report data looks like this.
```
const report = await Docx({
      template,
      data: reportData,
      noSandbox: true,
      cmdDelimiter: ['{', '}'],
      additionalJsContext: {
        injectImage: (dataUrl: string) => {
          const data = dataUrl.slice('data:image/jpeg;base64,'.length);
          return { width: 15, height: 10, data, extension: '.jpg' };
        }
      }
    });
```
As you can see, the data submitted to the **injectImage** function is the full base64 string of the image.  

But no image is injected into the resulting Word doc, and no error is thrown.  What might be wrong with this approach? 
I should add that I can console.log and see the dataUrl both before and after it is sliced, so I know it is actually there.  And for what it is worth, other INS template items are being injected, so I know that the program can inject data in other ways.

**Comment by jjhbw** [comment]
Can you post your template and ideally a fully reproducible example?

**Comment by billmcknight1953** [comment]
I am closing this.  I went back to basics to test against a much simpler template and was able to get an image to display.  Apparently, the issue might have been the formatting (spacing) or placement of the Image tag in the template.
