### ISSUE TITLE
HTML injection for templates not displaying

### ISSUE THREAD

**Issue by jschilmo** [guigrpa/docx-templates#292]
I was running into an issue locally with a template I'm using not displaying anything wrapped in "+++HTML \`" and so I looked to one of the SWAPI examples for reference, however even the examples are not generating correctly.

Example:
- Template: https://github.com/guigrpa/docx-templates/blob/master/examples/example-node/swapi-html.docx
- Report: https://github.com/guigrpa/docx-templates/blob/master/examples/example-node/swapi-html_report.docx

The report has no content where the html tags are being used as far as I can tell:
<img width="1684" alt="Screen Shot 2023-01-17 at 1 15 37 PM" src="https://user-images.githubusercontent.com/18448353/212992386-babc91db-4b3d-435d-9fda-a33543955ce8.png">

**Comment by jschilmo** [comment]
Update on this issue: 

The above screenshot was taken using google docs, that medium as well as several others (pages, embedded preview in slack) don't correctly display for some reason.

The weird thing is that you can get the html formatting to show in those applications if you jump through hoops.

If you download the above resource `swapi-html_report` and open it in word where it is formatted correctly, then make any change to the document at all and save it (new line at the end of a file or a random space), the document becomes formatted correctly even in google docs and pages.

**Comment by martijn10kb** [comment]
It's because of altchunks. docx-templates renders html with somehting as an altchunk component. Which is only supported by word (as far as I know).
If you open it with word and save as, it will not save it as altchunks but with xml as it is supposed.

Lost a day of work in this aswel last friday :)

**Comment by jjhbw** [comment]
Thanks @martijn10kb, it took me a while to figure out this limitation as well. I added it to the docs c1d3b9206e768662a6e76a46d462a5ec45932a9a.

**Comment by jjhbw** [comment]
See also the pinned issue https://github.com/guigrpa/docx-templates/issues/201#issuecomment-1352768073.

**Comment by jjhbw** [comment]
@martijn10kb Yes, I think that would indeed be the gist of his suggestion. I haven't tested it myself, though.

**Comment by martijn10kb** [comment]
@jjhbw Ahh and then add the resulting XML with the functionality this PR: https://github.com/guigrpa/docx-templates/pull/223.
Only thing to do then is translate my HTML to XML 🤔.
Would you think that would be a nice add-on to this module? Or would you rather have that people figure out for themselves all the caveats of their HTML?

**Comment by jjhbw** [comment]
I don't think increasing the scope of this library is the right move. I recommend simply using [html-to-docx](https://www.npmjs.com/package/html-to-docx) separately and feeding the result into your template using docx-templates' literal XML functionality. AFAIK you don't need PR #223 for that, but let me know if I'm mistaken.

**Comment by jjhbw** [comment]
@martijn10kb i'm not sure I understand the problem. Are you running into https://github.com/guigrpa/docx-templates/issues/16#issuecomment-392001823 ? 

Sorry if i'm giving you the impression that I'm slowing things down, but as that PR has zero tests to accompany it and I will be the person who has to solve the extra issues that will inevitably pop up I'm reluctant to merge it outright. It seems docx-templates can already insert XML, so I would like to know first why it does not suffice for your use case.

**Comment by martijn10kb** [comment]
@jjhbw Oohh I didn't know about that you could insert XML like this. Have been searching for this quite a while :/. Dont understand why I didn't found it yesterday/lastweek. But this seems to work for me! :)
Thanks for pointing out https://github.com/guigrpa/docx-templates/issues/16#issuecomment-392001823

No worries about the PR I fully understand why you dont want to get it merged without any tests..

Anyway could it be a nice addition for the README to include how someone would insert XML into a document? :)

**Comment by jjhbw** [comment]
@martijn10kb Excellent, good to hear that. Yes, you're right. It seems the README doesn't actually explain literal XML at all... I'll add it, thanks!

**Comment by martijn10kb** [comment]
@jjhbw Thank you very much! :D 👍
