### ISSUE TITLE
Sometimes the image is displayed in an egg shape

### ISSUE THREAD

**Issue by Vitomir2** [guigrpa/docx-templates#301]
Hi community :)

I want to export some charts from vue.js to word document and I am doing it in my node.js API currently. However, the strange thing is that sometimes the chart looks like egg, but sometimes do not. It seems like that the issue comes from the screen resolution, because when I have width less than 1920px, then the chart looks fine. However, if I have more than that, it is displayed with an egg shape. I noticed this when export it from my PC Monitor with/without the Developer tools opened. Here is example on how it looks like when I export it when the browser is with opened Developer Tools (width less than 1920px):
![image](https://user-images.githubusercontent.com/25567145/225607472-6404b442-ea1f-4af7-b26f-18160f8a4ecb.png)

And here is when exported without the Developer tools opened (maybe 2560px width):
![image](https://user-images.githubusercontent.com/25567145/225607661-fa104862-0341-4f94-9828-cf1b473e305e.png)

Both charts looks the same in the application, only when they are exported in the word file the shape is changing. I am not sure if the problem is here or maybe somewhere in the html canvas conversion to base64. I am using vue-echarts (the lib is based on Apache Echarts) and there is pre-built method getDataURL that returns the html canvas element into an base64 string image. Here is the code for the front-end request:
```js
const chartsData = this.generateChartDataForAPI()

const answersReq = await this.axios({
	method: 'post',
	url: '/pollAnswers/chart/word',
	data: {
		clientId: this.clientId,
		pollId: this.selectedPollId,
		chartsData,
		startDate: this.dateRange[0],
		endDate: this.dateRange[1]
	},
	responseType: 'arraybuffer'
})

if (answersReq.data) {
	downloadURL(answersReq.data, 'report.docx')
}

generateChartDataForAPI() {
	let chartsData = []

	if (this.$refs.answersChart && this.$refs.answersChart.length != 0) {
		for (const answersChart of this.$refs.answersChart) {
			const option = answersChart.getOption()

			console.log('window pixel ratio: ', window.devicePixelRatio)
			console.log('pixel ratio: ', window.devicePixelRatio || 1)
			if (option && option.title[0] && option.title[0].subtext) {
				chartsData.push({
					question: option.title[0].subtext,
					imageSrc: answersChart.getDataURL({
						type: 'jpeg',
						pixelRatio: window.devicePixelRatio || 1,
						backgroundColor: '#fff'
					})
				})
			}
		}
	}

	return chartsData
}
```

Here is the API method that creates the document:
```js
const CreateChartReport = async (datePeriod, clientName, devices, totalAnswers, chartsData, extension) => {
    const wordTemplate = await s3GetFile(process.env.S3_BUCKET_UPLOADS, process.env.REPORTS_TEMPLATE_PATH)
    const template = wordTemplate.Body

    const buffer = await createReport({
        cmdDelimiter: ['*', '*'],
        template,
        additionalJsContext: {
            datePeriod,
            clientName,
            devices,
            totalAnswers,
            chartsData,
            chart: (imageSrc) => {
                const data = imageSrc.slice('data:image/jpeg;base64,'.length)
                return { width: 20, height: 14, data, extension }
            }
        }
    })

    return Buffer.from(buffer)
}
```

I can easily fix the egg shape using the `width` and `height` when creating the report. However, then it might look in bad shape, too, as follows:
![image](https://user-images.githubusercontent.com/25567145/225610218-b8c0c58f-1d4f-4d6c-8eb0-51a4c7e18736.png)

**Comment by jjhbw** [comment]
Does the aspect ratio of the image you are injecting match the aspect ratio you are specifying for its on-page dimensions with `return { width: 20, height: 14, data, extension }`? In other words; does the pixel aspect ratio of the image match the on-page aspect ratio you specified (i.e. 20/14)?

**Comment by jjhbw** [comment]
Closing because it does not seem like a bug to me. Let me know if you disagree.

**Comment by Vitomir2** [comment]
> Does the aspect ratio of the image you are injecting match the aspect ratio you are specifying for its on-page dimensions with `return { width: 20, height: 14, data, extension }`? In other words; does the pixel aspect ratio of the image match the on-page aspect ratio you specified (i.e. 20/14)?

Hi @jjhbw,

Apologize for the late reply, but for some reason I have missed your comment from Mar 21.

Do you mean that I have to set the same width and height as the front-end?

BR,
Vitomir

**Comment by jjhbw** [comment]
@Vitomir2 Not sure what you mean with 'front-end', but the aspect ratio of the image needs to match the aspect ratio that you provide (i.e. `width: 20, height: 14` in your case).

**Comment by Vitomir2** [comment]
> 

@jjhbw so, the imageSrc should be also with `width: 20, height: 14` ?

**Comment by jjhbw** [comment]
@Vitomir2 sort of: it should have the same aspect ratio. I.e. you are telling docx-templates that you want the image to end up on the page with dimensions 20cm/14cm = 1,42857143. The image that you input as the `data` variable should have a similar aspect ratio, or you will end up with the distortion that you're seeing as MS Word will simply stretch the image to fit the desired width and height.

**Comment by jjhbw** [comment]
@Vitomir2 this is not related to vue or whatever frontend framework you are using. You need to look up the pixel dimensions of the image you are injecting into your template. Changing the aspect ratio of an image usually involves cropping.

**Comment by Vitomir2** [comment]
> @Vitomir2 this is not related to vue or whatever frontend framework you are using. You need to look up the pixel dimensions of the image you are injecting into your template. Changing the aspect ratio of an image usually involves cropping.

Ahh, okay, gotcha. The thing is that the image that inject is actually the div container where I have some charts. I am using this code to generate the image:

```
generateChartDataForAPI() {
	let chartsData = []

	if (this.$refs.answersChart && this.$refs.answersChart.length != 0) {
		for (const answersChart of this.$refs.answersChart) {
			const option = answersChart.getOption()

			if (option && option.title[0] && option.title[0].subtext) {
				chartsData.push({
					question: option.title[0].subtext,
					imageSrc: answersChart.getDataURL({
						type: 'jpeg',
						pixelRatio: window.devicePixelRatio || 1,
						backgroundColor: '#fff'
					})
					//* if we need to pass the width and the height to the api
					// width: this.$refs.answersChart.getWidth(),
					// height: this.$refs.answersChart.getHeight()
				})
			}
		}
	}

	return chartsData
}
```

So, I suppose I will have to play with the pixelRatio passed to the getDataURL method, right ? Or maybe, I can take the width and height of the image (html element) and calculate the ration based on that, as you did it above.

**Comment by jjhbw** [comment]
I dont know the APIs you're working with by heart, but the latter suggestion sounds best.

**Comment by Vitomir2** [comment]
Hi @jjhbw,

I want to thank you again, because your direction for the pixels and the ratio of the image led me to the solution! I made the input image with a fixed size, thus, I ensure that the size in the word file will be consistent.

I answered a bit late, but I had more important tasks than fixing this.

Wish you all the best!

Best regards,
Vitomir

**Comment by jjhbw** [comment]
@Vitomir2 good to hear that! Thanks for replying and good luck with your project 👍
