### ISSUE TITLE
css style border-radius not work

### ISSUE THREAD

**Issue by minuth** [guigrpa/docx-templates#304]
I tried with to generate image with html and css style like below command:
```
+++HTML `
<meta charset="UTF-8">
<body>
<img src="${basics.image}" alt="HTML5 Icon" width="100" height="100" style="border-radius: 50%;">
</body>
`+++
```
I expected it will generate an image with the circle shape, BUT it didn't.

**Comment by jjhbw** [comment]
If you're sure your HTML itself is correct, please read up on the limitations of HTML altChunk in MS Word. It is possible that what you are trying to do is not supported by MS Word.
