### ISSUE TITLE
Why are nested loops supported, but merging vertical cells not?

### ISSUE THREAD

**Issue by tomorrowShow** [guigrpa/docx-templates#306]
We implemented nested loops, but we couldn't merge cells vertically。
Now:   
a    1    4    3
a    3    1     2
a    5    7     2

we  hope:              
x    1    4     3
a    3    1     2
x    5    7     2    

Please forgive my limited ability to express myself. I hope you can understand what I mean，have a  nice day, bro. ：）

**Comment by jjhbw** [comment]
Your question is clear, don't worry.

The answer is that both features are very different, and require different modifications to the underlying XML of the document. I'm happy to accept an MR if you find a way to get vertical cell merging to work.

Alternatively (and only if you're targeting MS Word users) you can use HTML tables instead, which are more flexible. Note the limitations in #201
