### ISSUE TITLE
Images based in FOR cycle

### ISSUE THREAD

**Issue by arnamb** [guigrpa/docx-templates#307]
I'm generating word document, which has several images (quantity of them is not known until last step). Is there any possibility, I could use FOR cycle to generate images? 

For example.: 

`
{ FOR image in imagesArray }
{ INS IMAGE image() }
{ END-FOR imagesArray }
`

The imagesArray would look something like this: 

`[
    {
        image: 'someKindOfBase64Url-2'
    }, 
    {
        image: 'someKindOfBase64Url-1
    }
]`

**Comment by jjhbw** [comment]
Yes something like that should be possible, but make sure to read the docs (README) first. Each image should be provided as `{ width: 6, height: 6, data, extension: '.gif' }` and the `INS` and `IMAGE` commands should not be combined. You should only use `IMAGE` for your use case.

**Comment by arnamb** [comment]
I was thinking something like this:

`      const data = {
        template,
        data: {
          name,
          code
        },
        cmdDelimiter: ['{', '}'],
        additionalJsContext: {
          imageTest: () => {
            arrayOfImages.map((img) => ({
              width: 1,
              height: 1,
              data: img.buffer,
              extension: '.jpg'
            }));
          }
        }
      };
`

And in template something like this:

![paveikslas](https://user-images.githubusercontent.com/76652997/231427786-36b45f21-05b0-49da-9335-3751e67c58a1.png)

**Comment by arnamb** [comment]
Okay, I got it, thanks :) It worked :)

**Comment by jjhbw** [comment]
Ok great! I'll close the issue then.
