### ISSUE TITLE
I unexpectedly got the error `ObjectCommandResultError`

### ISSUE THREAD

**Issue by daniskhabirov** [guigrpa/docx-templates#308]
I got the error `ObjectCommandResultError` when call the object property in the docx template:

[FOR breach IN breaches]
[INS $breach.number]
[END-FOR breach]

I`m returning "breaches" array from the JS code:
await createReport({
   template,
   data: { breaches: [ { number: "2.1" }, { number: "2.2" } ] }
})

I use the docx-template v4.11.1, node v14.18.1

**Comment by jjhbw** [comment]
Can you give me a reproducible example, including a template?
