### ISSUE TITLE
`IncompleteConditionalStatementError` not exported from `index.ts`

### ISSUE THREAD

**Issue by simonmumenthaler** [guigrpa/docx-templates#314]
I wanted to properly handle the errors and noticed the `IncompleteConditionalStatementError` is not exported from the `index.ts`.
After looking into the source code it seems a bit odd not exporting this one. Is there a particular reason for it?

(version `4.11.1`)

**Comment by jjhbw** [comment]
Good find! Thanks for noticing. Fixed with 2a6aa00d750da5f8a1ba1d11b4be69eae84028ad
