### ISSUE TITLE
how to insert word doc charts

### ISSUE THREAD

**Issue by serveryang** [guigrpa/docx-templates#326]
is there word charts example.
eg : pipChart, barChart etc.
like: https://docxtemplater.com/demo/#bubble-chart

**Comment by jjhbw** [comment]
No, there is no support for that at the moment. It requires generation and insertion of custom XML.

If you can figure out how to create the desired XML for the figure you want you can [insert it using docx-templates](https://github.com/guigrpa/docx-templates#inserting-literal-xml).

You can of course insert arbitrary images using `IMAGE` commands, but you need to create these images outside of docx-templates.
