### ISSUE TITLE
Using base64 as src for <img> inside altChunk

### ISSUE THREAD

**Issue by Darwin1337** [guigrpa/docx-templates#338]
When using base64 as source for the img tag inside the +++HTML <html>+++, the result image will have its lower half completely distorted.
![image](https://github.com/guigrpa/docx-templates/assets/40754665/fd36f27c-c448-4761-8b1a-ad841b0bb136)

I've [read](https://github.com/evidenceprime/html-docx-js/issues/2#issuecomment-125884956) this is because of the way altchunk handles images. I also [read](https://github.com/evidenceprime/html-docx-js/issues/2#issuecomment-129782105) that the solution is to use mht content instead of html.

My use case is: I have an array of HTML strings (with paragraphs and images mostly). The image links are protected with a JWT cookie and I can't seem to append it to word's requests for those images. So I just fetch the image via JS (where I can append the cookie) and feed the base64 raw data to the src attribute. Am I missing an easy solution or is b64 and mht the way to go?

**Comment by jjhbw** [comment]
That's really weird, but I don't think this is a docx-templates issue, but a Word issue. I'll leave this open for now in case others have an idea.

**Comment by Darwin1337** [comment]
Unlikely this will be ever reproduced as this was a bug on my end.

**Comment by jjhbw** [comment]
@Darwin1337 Ah ok, good to know. Thank you for taking the time to close this issue 👍
