### ISSUE TITLE
How to run it on browser side

### ISSUE THREAD

**Issue by AbrahimZaman360** [guigrpa/docx-templates#342]
I am unable to do stuff on the browser side using your guide in readme!

**Comment by AbrahimZaman360** [comment]
I'm using NextJS, the problem is the data is too large to send through API every time, I want to convert it in Browser.
Please Guide me on how to set it up correctly on the NextJS 13 appdir.

**Comment by jjhbw** [comment]
What exactly is your question? Please open a new issue and provide a reproducible example of what you're trying to do.
