### ISSUE TITLE
Update of Word directory

### ISSUE THREAD

**Issue by yangjie161** [guigrpa/docx-templates#348]
**May I ask if docx templates can automatically update directories in Word?**
The table of contents contains page numbers

**Comment by jjhbw** [comment]
AFAIK only Word can do that when saving the document, because the document needs to be rendered completely to know the number of pages. This library cant render the document like Word, so it cant know the number of pages.

**Comment by jjhbw** [comment]
Closing this issue because i think that should answer your question. Just @ me if you want to know more.
