### ISSUE TITLE
How to set image in header which is stick to the top of the header

### ISSUE THREAD

**Issue by csod-bganatra** [guigrpa/docx-templates#351]
I need some help regarding an implementation, 
I want to embed an image in header and the image should stick to top of the header, no margin padding needed from top 
just start from beginnign,

Does anyone has any idea how to do that,  I tried but either image does not display or if it does it displays in middle of header,

**Comment by jjhbw** [comment]
If you are still having this problem, please show what you have already tried and what you expect to happen. Ideally using code I can run. Please use a new issue.
