### ISSUE TITLE
[Question or maybe issue] Newlines on free text insertion

### ISSUE THREAD

**Issue by drogojinaru** [guigrpa/docx-templates#362]
Hello, I am using a textfield input, where the user can insert text with newlines, when inserted in document it looks like that: 
<img width="554" alt="Screenshot 2024-04-07 at 12 10 34" src="https://github.com/guigrpa/docx-templates/assets/17499659/6c9fac94-01d0-4deb-b6f9-0fa95ae085dd">
I already tried to use processLineBreaksAsNewText=true and processLineBreaks=true and it did not help, maybe I am missing smth. How can I force to enter them with new Paragraph on newline from textfield?
** it occurs only on justify text

**Comment by logemann** [comment]
you need to pass \n to the template. How you pass the newline from browser to your backend is another story but at the end you need to pass \n to createReport()

**Comment by drogojinaru** [comment]
Forgot to update, I figured it out, I passed it as an array with \n and making a loop in the document, this seems to work good so far. Thanks!

**Comment by jjhbw** [comment]
Thanks for posting your solution!
