### ISSUE TITLE
inserting HTML  part ?

### ISSUE THREAD

**Issue by olivierSOW** [guigrpa/docx-templates#367]
Hi,

I would like to insert HTML parts. I see the HTML keyword allows inserting HTML
[the example](https://github.com/guigrpa/docx-templates?tab=readme-ov-file#html) shows how to use it but when i try with my template, i get this error: 
```
docx-templates.js:17 
 Uncaught (in promise) Error: Error executing command '`<meta charset="UTF-8"> <body>   <h1>$': SyntaxError: Unexpected end of input
    at runUserJsAndGetRaw (docx-templates.js:17:7454)
    at H (docx-templates.js:18:502)
    at U (docx-templates.js:17:13993)
    at walkTemplate (docx-templates.js:17:12985)
    at async ue (docx-templates.js:18:8491)
    at async HTMLButtonElement.OnExportClick (export.js:465:19)
```

If I remove all inserting tags within the HTML, the creating process is OK.
Could you help me please ?

My final goal is converting multiple html formatted texts (built with XDSoft Jodit) into one docx file. Can i do it with docx-templates via the HTLM inserting tag and submiting Html text into the javascript data ? Must I insert html head/body tag for each HTML parts or can i insert directly the html part ?

i join my template
[export-by-pool.docx](https://github.com/guigrpa/docx-templates/files/15064047/export-by-pool.docx)

**Comment by olivierSOW** [comment]
Ok, i found the solution by myself: i changed command delimiters to use { and }
and these characteres are used in HTML, so i change command delimiters to {# #}
i can insert HTML parts by adding html head/foot (`<meta charset="UTF-8">
<body>`  and `</body>` )

thanks for you great lib !

**Comment by jjhbw** [comment]
Thanks for posting your solution!
