### ISSUE TITLE
Missing documentation in npm for 2.7.1

### ISSUE THREAD

**Issue by vdechef** [guigrpa/docx-templates#37]
On npm repo, the documentation for version 2.7 has not been updated : https://www.npmjs.com/package/docx-templates
This can discourage some people to give it a shot.

BTW, thanks for the release 👍

**Comment by guigrpa** [comment]
Oh, true! I guess I automated publishing too much ;) I'll have a look

**Comment by guigrpa** [comment]
Fixed! Just published a patch (v2.7.2). Thanks for noticing!!
