### ISSUE TITLE
use link insertion for-each-loops

### ISSUE THREAD

**Issue by pki89** [guigrpa/docx-templates#385]
any chance to use link insertion nested (e.g. during a for-each-loop)?
We weren't able to make this work (in the template files):

```
/// delimiters: ["<<", ">>"]

via email: 
<<FOR email IN CP.allEmails >><<INS <<LINK ({ url: allEmails.emailUrl, label: allEmails.email })>>>>
<<end-for email>>
```

while this works (of course):

```
via email: 
<<FOR email IN CP.allEmails >><<INS $email.email>>
<<end-for email>>
```

Thanks a lot!

**Comment by jjhbw** [comment]
Why are you nesting `LINK` in an `INS`? Can you try without the `INS`?

**Comment by KAVA-Leigh** [comment]
It might be just your example here, but allEmails.emailUrl won't work, it should be $email reference, per your second example.

I would think this should work;

```
<<FOR email IN CP.allEmails>>
<<LINK ({ url: $email.emailUrl, label: $email.email })>>
<<END-FOR email>>
```

Assuming the data is in the structure of { CP: { allEmails: [ { emailUrl: "", email: "" } ] } }

Not near a machine to test this at the moment. So, I am just going by memory, sorry.
