### ISSUE TITLE
How to pass multiple parameters in image function 

### ISSUE THREAD

**Issue by DVGY** [guigrpa/docx-templates#389]
How to pass multiple params inside image function ? 

```
+++ IMAGE insertImage($v.imageOne , +++INS $fdi.h+++, +++INS $fdi.w+++)
+++


```

I have this insertImage function defined in additional context

`Encountered error while creating  Report AppError: Error executing command 'insertImage($v.imageOne ,': SyntaxError: Unexpected end of input`

**Comment by SuchiraD** [comment]
Hi, @DVGY you can try 
`+++ IMAGE insertImage($v.imageOne , $fdi.h, $fdi.w) +++`

You cannot use +++INS before you close the `+++IMAGE your_function()+++` section
