### ISSUE TITLE
Rendering CSS that isn't inlined

### ISSUE THREAD

**Issue by PeytonHanel** [guigrpa/docx-templates#391]
I can render css on my inserted HTML but only if it's an inline style. So far I've not been able to get it to work with any css in a style tag. Is this possible?

**Comment by jjhbw** [comment]
I don't think so. Note that HTML in .docx files comes with very severe limitations is only supported by Microsoft Word, and not e.g. LibreOffice as far as I know. Best to check the spec to see if your use case is possible. Maybe you can find that on this site http://officeopenxml.com/WPdocument.php
