### ISSUE TITLE
Placeholder starting with numbers are considered as invalid commands. 

### ISSUE THREAD

**Issue by danishmehmood1612** [guigrpa/docx-templates#393]
**Bug Report**
Title: Placeholder with Number Prefix Causes CommandExecutionError

**Description:**
When using placeholders that start with a number, the system throws the following error:
CommandExecutionError: SyntaxError: Invalid command.

This behavior is not documented, leading to confusion and difficulty in troubleshooting. After significant time spent experimenting, it was discovered that updating the placeholders to avoid starting with a number resolved the issue.

**Steps to Reproduce:**

- Use a placeholder that starts with a number (e.g., {1placeholder}).
- Attempt to execute the command.
- Observe the CommandExecutionError: SyntaxError: Invalid command error.
**Expected Behavior:**
The system should either:
- Support placeholders that start with numbers, or
- Provide a clear error message specifying the validation rule.
**Actual Behavior:**
The system throws a generic syntax error without any guidance on the issue.

**Comment by jjhbw** [comment]
These placeholders you mention are javascript variable names under the hood. Javascript does not allow variable names to start with a number. No way to fix this I'm afraid.
