### ISSUE TITLE
How do I generate the library after doing fork?

### ISSUE THREAD

**Issue by JonathanLSignot** [guigrpa/docx-templates#4]
I just created a fork but at the moment of wanting to implement it in the folder of node_modules using `npm link` it does not run because it does not find the library, checking the project I see that is missing / lib. What do I have to do to generate it?
Greetings.

**Comment by guigrpa** [comment]
You can run `npm install && npm run compile`.

Planning implement an additional feature?

**Comment by JonathanLSignot** [comment]
I need to run it in linux, is not there a possibility in windows?

Yes, I want to implement buffer and stream. So that the document is not saved to the server.

**Comment by AngelMunoz** [comment]
@guigrpa yes we've been working on #3 workaround of replacing images, we've been fighting flow and the test quite a bit but we would like you to check pr #5  and see if it's good enough
we're trying to install from github meanwhile but we're running with some troubles related to lib folder not generatet when doing so, any pointers would be appreciated :package:

**Comment by guigrpa** [comment]
Thanks for the PR! Please find some remarks [there](https://github.com/guigrpa/docx-templates/pull/5).

Regarding your issue with GitHub installation, and assuming you are including docx-templates as a dependency for another project (let's call it Project A), I would suggest:

* Keep the latest published version of docx-templates in Project A's package.json, and install all your dependencies with the standard `npm install`
* Go to your modified local version of docx-templates, and run `npm install && npm run compile && npm link`
* Go back to Project A's folder and run `npm link docx-templates`

This should let you use your modified version of docx-templates, while the PR is reviewed...

**Comment by AngelMunoz** [comment]
thanks we already tried that and works fine locally but qa wants to take it to the staging server and that approach is not really useful in that use case, I've tried to npm install directly from github using the `.git#branchname` syntax but it gets downloaded without the `src` folder which is unfortunate hahaha
i've talked to my partner and he will address your concerns in the pr

**Comment by guigrpa** [comment]
Closed with the integration of #5
