### ISSUE TITLE
Error executing command: ... Cannot read property ‘then’ of null

### ISSUE THREAD

**Issue by koresar** [guigrpa/docx-templates#40]
The template looks like this:
```
First: +++= user.name+++
Middle: +++= user.middle+++
Last: +++= user.last+++
```

Sometimes the `user.middle` is JavaScript `null` value.
```js
const user = {
  first: "John",
  middle: null,
  last: "Smith"
}
```

It would be great if the module wouldn't throw in this case.
> Error executing command: INS user.middle Cannot read property ‘then’ of null

 I very much like how Vue.js is behaving. It prints `undefined` and `null` values as empty strings.

I'm happy to supply a PR if this idea seems ok to the maintainer(s).

**Comment by guigrpa** [comment]
Please update to v2.7.3, it shouldn't throw in that case. I'm not sure what it will display, though, please let me know.

**Comment by koresar** [comment]
@guigrpa hello. thanks for the quick fix. I can't find the 2.7.3 in the NPM registry.
https://www.npmjs.com/package/docx-templates

But I see it in the GitHub releases list: https://github.com/guigrpa/docx-templates/releases
Could you please publish it?

**Comment by guigrpa** [comment]
Ooops, my automated release process failed. v2.7.3 is now available, thanks!
