### ISSUE TITLE
Use non Integer values on image sizes

### ISSUE THREAD

**Issue by LuisSevillano** [guigrpa/docx-templates#42]
First of all, thank you for this awesome library! It is helping me a lot in a printing module (_browser usage_).

That module prints bills/licenses and I'm facing some issues when trying to put images of specific sizes inside one of that documents. 

As `docx-templates` use an `HTMLImageElement`, just _non negative integers_ can be used as values for `width` and `height` attributes. This matter limits a lot the posibilites of place an image within the document.

Does anyone know any way to deal with it? Does someone comes up with how decimal values could be used setting the sizes of an image?

Thanks in advance

**Comment by Gary-Delancy** [comment]
I am using 1.5 for my height and width, they come through as I would expect.  Perhaps this has been added since this request was made?

**Comment by jjhbw** [comment]
Thanks @Gary-Delancy . I don't see anything in the code that would limit users to integers at this time. We're also not using `HTMLImageElement` (anymore).
