### ISSUE TITLE
Sandboxing when used in browser

### ISSUE THREAD

**Issue by vdechef** [guigrpa/docx-templates#43]
As **vm2** module is not available for browsers, and **Node VM** module is way too slow in browsers, I was wondering if Web Workers could be a solution to isolate the docx generation process ?
As webworkers provide access to Ajax and File APIs, it may proves a good alternative.

I am currently calling `createReport()` inside a dedicated worker, by feeding it a File object and a JSON object as input data. Everything works smooth, and I don't have access to window/localStorage/cookies from within the template.

Do you have any ideas or remarks regarding the use of webworker as a kind of security sandbox ?

**Comment by guigrpa** [comment]
I'm no security expert, sorry… But your approach certainly looks interesting.

**Comment by guigrpa** [comment]
v3.0.0 might help you in this. The new hook for running JS may allow you to implement such a solution.

**Comment by GiordanoArman** [comment]
@guigrpa hi, I have tried using the library within a web worker but it complains that document is not present (of course it's present only in the main app context). Are there any polyfills to have this library work in a web worker? I would like to avoid an annoying 3 seconds screen freeze when a document is generated. Thanks!

**Comment by vdechef** [comment]
@GiordanoArman I used to have it work in webworker. It was 2 years ago but it worked. I don't recall having to use dedicated polyfills.

**Comment by mathe42** [comment]
Same as for Deno see https://github.com/guigrpa/docx-templates#deno-usage

**Comment by GiordanoArman** [comment]
@vdechef @mathe42 ok, then I will try to disable the sandbox when using within a web worker, thanks!

**Comment by GiordanoArman** [comment]
maybe it could be helpful for other developers to mention explicitly in the docs that the sandbox needs to be disabled in order to use the library within a web worker?
