### ISSUE TITLE
Insert Page break

### ISSUE THREAD

**Issue by lwallent** [guigrpa/docx-templates#46]
Can a page break somehow be inserted inside a FOR and END-FOR.

In case one is iterating over something and wish to start a new page for each item

Adding a page break from code:
` <w:br w:type="page"/>`

Is inserted as the literal XML  :-)

Can a page break be achieved in the current version? Or is it a missing feature?

**Comment by lwallent** [comment]
Ok, I solved the issue I was facing. Just used a word-style with a "page break before".

**Comment by nabilzhafri** [comment]
@lwallent mine explaining what exactly you did here? trying to achieve the same thing.

**Comment by nabilzhafri** [comment]
@lwallent okay nvm, I figured it out! To others, this was what I did:

```html
+++HTML `
<body>
<p>First page</p>
<p style="page-break-before: always;">Second page</p>
</body>
`+++
```

**Comment by Vitomir2** [comment]
> 

Hey, @nabilzhafri , I used your way to make a page break, but when there is no text (deleted 'Second page'), it skips this paragraph and still add the next on the same page. When I insert even one letter, it do the page break. Do you know a way to make the page break without adding text in the paragraph element?

**Comment by nabilzhafri** [comment]
hey @Vitomir2, i haven't tried it, but have you tried inserting "empty space", something like `&nbsp;`?
+++HTML `
<body>
<p>First page</p>
<p style="page-break-before: always;">&nbsp;</p>
</body>
`+++

**Comment by Vitomir2** [comment]
@nabilzhafri , thanks for the quick reply. I tried with the following, but it looks like it does not work.
```
*FOR chartData IN chartsData*
  *$chartData.question*
  *IMAGE chart($chartData.imageSrc)*
  *HTML `
	<body>
		<h2 style="page-break-before: always;>&nbsp;</h2>
        </body>
   `*
*END-FOR chartData*
```

However, I found another solution for my case. I just added the *$chartData.question* in the HTML and break page before. And, to avoid the break page for the first iteration, I added an IF condition. Here is the code:
```
*! breakPage = false*
*FOR chartData IN chartsData*
   *IF breakPage*
      *HTML `
	  <head>
		<meta charset=utf-8>
          </>
	  <body>
		<h2 style="page-break-before: always; text-align: center; font-weight: bold";> ${$chartData.question}</h2>
           </body>
       `*
    *END-IF*
    *IF !breakPage*
        *$chartData.question*
    *END-IF*
    *IMAGE chart($chartData.imageSrc)*
    *! breakPage = true*
*END-FOR chartData*
```
