### ISSUE TITLE
v2.9.0-rc.0 cannot generate from different templates

### ISSUE THREAD

**Issue by razyon** [guigrpa/docx-templates#49]
Hi,

Since the new release I run into an issue that prevent the library from generating reports from different templates.

I'm creating service that will generate docx reports. The process is running and listening to a port. It can generate reports from different templates. Since the new release it takes only the first template from the first report to generate the other reports.

It must be a cache issue that always takes the first template used to every other report generation.

Great job on the library by the way, I really enjoy it.

Best regards,
David

**Comment by guigrpa** [comment]
You're totally right. I've just released v2.9.0-rc.1. Could you please check whether it solves your issue?

**Comment by razyon** [comment]
Thanks it works!

But I couldn't manage to get the v2.9.0-rc.1 from npm I had to get the sources and compile manually.

Regard,
David

**Comment by guigrpa** [comment]
Glad to hear it works. In principle, the v2.9.0-rc.1 appears to be [in the registry](https://www.npmjs.com/search?q=docx-templates). It's also untagged, so it should work. Maybe you're using a lockfile or something?

**Comment by razyon** [comment]
I figured my issue, the Yarn registry was not updated already.

Everything is fine.
