### ISSUE TITLE
Latest Angular (7) support

### ISSUE THREAD

**Issue by canzy** [guigrpa/docx-templates#53]
Hi!

I am getting errors when I use this package with Angular 7, because it does not support 'require' as the older versions did, e..g. for require('path') etc. Do you think you would be able to make it more Angular 7 friendly? 

Kind regards

**Comment by vdechef** [comment]
@canzy,
I use it with Vue.js, and it works fine. But I had to make some adjustments in my build configuration.
For example, I had to remove vm2, as it is not compatible browser. 

If you use Webpack to build your angular package, you can disable packages that are for node only.
In my vue.config.js, I added :
~~~
configureWebpack: config => {
    // disable vm2 module (required by docx-templates, but not compatible with browsers)
    config.plugins.push(
      new webpack.NormalModuleReplacementPlugin(
        /vm2/,
        path.resolve(process.cwd(), 'src/utils/emptyModule.js')
      )
    )
~~~

with src/utils/emptyModule.js containing only 1 line:
~~~
export default {}
~~~

**Comment by guigrpa** [comment]
I'm not sure I understand the problem. Could you please be more specific (error message)? It would also help if you shared a repo showcasing the problem in an isolated way, thanks!

**Comment by guigrpa** [comment]
Please check out v3.0.0, it may alleviate your problem.

**Comment by stanleyck** [comment]
@vdechef I'm trying to get this library to work in vuejs, but haven't managed to get it to work yet. Am I supposed to just import the library in main.js, and then do Vue.use(createReport)? 

I've tried adding the emptyModule and the configureWebpack in vue.config.js, but when I build the application it's giving me an error that it cannot find the storyboard lib.
 
It would be great if you could describe in some more detail how you managed to get it to work. 

Many thanks!

**Comment by vdechef** [comment]
I don't import the library in main.js. 
I use it in a component: I just import it in my .vue file
```
import Docx from 'docx-templates'
```

and then in my component I have a method that generates the document, by doing
```
let doc = await Docx({
               template: myTemplateAsBuffer,
               noSandbox: true,
               data: myDataAsJson
           })
```

Regarding storyboard, I checked my package.json and I realized that I had added storyboard to dev-dependencies:
```
"storyboard": "^3.1.4",
"storyboard-listener-console": "^3.1.4",
```

This, combined with the webpack config above, works for me.

**Comment by stanleyck** [comment]
@vdechef: Many thanks! I got it to work now. 

@guigrpa: Thanks for this great library!
