### ISSUE TITLE
Update Table of Contents (TOC) after injecting dynamic content

### ISSUE THREAD

**Issue by coobr01** [guigrpa/docx-templates#56]
Is it possible to update the MS Word based TOC after a merge has taken place? As you can imagine, we're injecting a lot of content which changes the page references in the TOC and we'd like to update it in the generated/merged document instead of forcing/instructing the end recipient that they must open it and do the normal MS TOC right-click "Update Entire Table"

![image](https://user-images.githubusercontent.com/1842830/51998130-12bb6780-2486-11e9-9dc3-156e22b18600.png)

**Comment by vdechef** [comment]
This could be great. 
It seems like there is a way to do this easily : https://stackoverflow.com/questions/38844167/update-toc-table-of-contents-in-docx-using-nodejs-and-docxtemplater
Maybe we could add this feature ?

**Comment by guigrpa** [comment]
Definitely worth exploring! Want to give it a try?

**Comment by coobr01** [comment]
Ok, as i'm not as familiar with the code yet, I manually tried this using a .docx file on my desktop and it worked. 

Basically, i used 7-Zip to open and edit the settings.xml file inside of my test .docx file. I added the line suggested in the post by @vdechef (i.e. <w:updateFields w:val="true" />) and then saved the updated settings.xml file in the .docx. 

I then used MS Word (o365 version #1808) to open the updated .docx file and MS Work properly asked me to update references and the table

#first it asked me
![image](https://user-images.githubusercontent.com/1842830/52007820-553c6e80-249d-11e9-8c75-b998ed891283.png)

#second it asked me
![image](https://user-images.githubusercontent.com/1842830/52007844-62f1f400-249d-11e9-9083-c19db8e8a6a1.png)

I'd still prefer if we could figure a way to programmatically do this on the server-side but I think this is a great workaround that I'd love to see implemented in the future. Thanks for the reference @vdechef !

**Comment by guigrpa** [comment]
@vdechef Do you believe there's a way to avoid the first dialogue ("This document contains fields that may refer to other files…")?

I've also seen that even if you update the fields and then save and close the document, the next time you open it the same message appears. This is really annoying — is there any way to avoid it?

**Comment by guigrpa** [comment]
Closing since it's definitely not straightforward, as far as I can tell…

**Comment by coobr01** [comment]
Share,, we could definitely use the feature. I'm not sure the best way to implement it either though.
