### ISSUE TITLE
Bulleted and Ordered Lists

### ISSUE THREAD

**Issue by kisonay** [guigrpa/docx-templates#58]
I don't see any examples for lists and in my tests, the lists get removed.

Is it supported?

**Comment by guigrpa** [comment]
Just added an example report under packages/examples-node: swapi-bullets.docx. Please have a look!

**Comment by kisonay** [comment]
Thanks, this is what I was doing but I guess my issue is using it with HTML...

```
+++FOR question IN questions+++
1.	+++HTML `${$question.query}` +++
+++END-FOR question+++
```
This seems to strip the bullets

**Comment by kisonay** [comment]
Actually here is a better example:

data structure: 
`questions: [{
    query: '<p>some text</p>',
    answers: [{text:'<p>some answer</p>'},{text:'<p>Another answer</p>}]
}]`

template: 
`+++FOR question IN questions+++
1. +++HTML `<body>${$question.query}</body>` +++
    +++FOR answer IN $question.answers+++
       A. +++HTML `<body>${$answer.text}</body>` +++
    +++END-FOR answer+++
+++END-FOR question+++`
This produces just blocks of text, no bullets or formatting

**Comment by guigrpa** [comment]
Maybe HTML is the culprit, yes…
