### ISSUE TITLE
row or table whit if condition

### ISSUE THREAD

**Issue by JonathanLSignot** [guigrpa/docx-templates#6]
Is there any way to put a row or table inside an if?

**Comment by guigrpa** [comment]
There's no `IF` command for the moment, but you can work around it with `FOR`. See [this example](https://github.com/guigrpa/docx-templates/blob/master/src/__tests__/fixtures/if.docx). It iterates over a single-element loop or empty loop, depending on the truthyness of the expression.

It should also work on whole tables or table rows...

**Comment by guigrpa** [comment]
I copy the template contents here for reference:

>Test 1:
>+++FOR i IN (4 > 3 ? [1] : [])+++
>Should appear in the output
>+++END-FOR i+++
>
>Test 2:
>+++FOR i IN (4 < 3 ? [1] : [])+++
>Should **not appear** in the output
>+++END-FOR i+++


Output:

>Test 1:
>Should appear in the output
>
>Test 2:

**Comment by guigrpa** [comment]
Check out the new `IF` command in v2.3.0! :)
