### ISSUE TITLE
Node 8

### ISSUE THREAD

**Issue by kisonay** [guigrpa/docx-templates#60]
I'm trying to use this in node 8 and although it doesn't generate any errors, it creates corrupt documents which cannot be opened.

Is there a minimum version required?

**Comment by guigrpa** [comment]
Just tested with node 8 and it seems to be fine. We're also running all tests on Node 6 and 8 automatically, on every git push… Maybe you could share a small repo that isolates the problem? Or share the template you're using?

**Comment by kisonay** [comment]
I appreciate you looking into it. must be something local to me... i ended up moving it client side and it is working great!
