### ISSUE TITLE
HTML injection doesn't work in google docs

### ISSUE THREAD

**Issue by oeeq** [guigrpa/docx-templates#62]
If I use HTML rule the text is missing when I open it with google docs.
You can try to recreate by simple making docx file that contents
```
+++HTML `<body><span>Simplest html</span></body>`+++
```
If you'll open it in google docs you won't see any text.

I don't really have any clue.

**Comment by oeeq** [comment]
I noticed that if I change anything in the output file with Microsoft Word and reopen it in Google Docs it will work.

**Comment by oeeq** [comment]
Ok, I figured out that the issue is that Google Docs doesn't support altChunk. It seems like there is nothing that can be done. I personally will just convert specific HTML tags I have into XML.

**Comment by guigrpa** [comment]
I didn't know that, thanks for reporting!
