### ISSUE TITLE
LINK style troubles

### ISSUE THREAD

**Issue by d-oleg** [guigrpa/docx-templates#64]
I'm getting some problems, when creating hyperlink by +++LINK method. The link is creating and works well, when I click it, but it doesn't have "hyperlink" style and is not colored in "hyperlink" color. When I try to create it with +++HTML method, it's creating well, with proper style, but html method creates not a text fragment, but a paragraph. What am I doing wrong?

The template code is simple, as in the docs: +++LINK ({url:$item.url, label:$item.name})+++

**Comment by guigrpa** [comment]
Hi there! I suggest using +++LINK and styling the text of the command however you like. For instance, underlined and blue, or any other way…

**Comment by d-oleg** [comment]
Thank you for your answer!

I tried the floowing code with the floowing simple template https://drive.google.com/open?id=0B_I68hJqSZnPLWdJWHo4RlVDWFFSSHJaVFdJdlRLY3NIbDI4

In template I tried both ways - by simple coloring text and by styling it - none of them worked while generating hyperlink

Code in nodejs:

var report = require('docx-templates');
report({
	template: 'template1.docx',
	output: 'report.docx',
	data: {"name":"Sample name","url":"http://gooogle.com"}
});

**Comment by guigrpa** [comment]
Fixed in v3.1.1, thanks for reporting!
