### ISSUE TITLE
Index of FOR loop

### ISSUE THREAD

**Issue by flaglerkid** [guigrpa/docx-templates#65]
Is there a way to get the index of the FOR loop? I was hoping to use it with a conditional so that it does not export content on the first time (index 0) but does for all remaining.

**Comment by guigrpa** [comment]
Yes, but only for the innermost loop: `$idx`. Please tell me if this does not work.

**Comment by davidjb** [comment]
For note, this does work - `$idx` is available within loops and refers to the inner-most index. This was formalised and documented in #323.
