### ISSUE TITLE
Line breaks are missing in LibreOffice Writer

### ISSUE THREAD

**Issue by leovin** [guigrpa/docx-templates#68]
Hello,

Line breaks are missing in LibreOffice Writer (v6.1.6.3, Ubuntu) but show up in online viewer (for example https://onlinedocumentviewer.com).

Steps to reproduce:
1) Modify test '25 Adds line breaks by default' (https://github.com/guigrpa/docx-templates/blob/4c007ad5b5f436996de679d6a398a425f07d5f41/packages/docx-templates/src/__tests__/indexNode.test.js#L465) to output document.
2) Open created document in latest LibreOffice Writer.

Expected result:
According to test template, there should be two line breaks starting with words 'Nullam' and 'Morbi'.

Actual:
Line breaks are missing.

**Comment by guigrpa** [comment]
I'm afraid this library only targets MS Word. Sorry about that!

**Comment by emilong** [comment]
I found a workaround that seems to work in LibreOffice and FreeOffice TextMaker:

```js
const literalXmlDelimiter = "||";
const preserveWhitespace = string =>
  string
    .split(/[\n\r]+/) // could use different split criteria here
    .map(
      para =>
        `${literalXmlDelimiter}<w:p>${literalXmlDelimiter}${para}${literalXmlDelimiter}</w:p>${literalXmlDelimiter}`
    )
    .join("");
```

In other words, switch from using `<w:br>` to wrapping each paragraph in `<w:p></w:p>` tags. I can then wrap all my strings with this function.

If anyone else finds this helpful, I can make a PR... lmk!
