### ISSUE TITLE
Type definition

### ISSUE THREAD

**Issue by mathe42** [guigrpa/docx-templates#71]
Can you add a type Definition {.d.ts file} for Typescript users? In https://github.com/guigrpa/docx-templates/blob/master/packages/docx-templates/src/types.js are allready some types...

**Comment by bogdan-calapod** [comment]
Any news regarding this ? I could lend a hand in writing types if needed 😁

**Comment by guigrpa** [comment]
I don't use Typescript, but feel free to submit a PR — can it be added only for the external API, without requiring changes in the build process, internal types, etc.?

**Comment by bogdan-calapod** [comment]
Cool - I'll have some free time later this week and will get to it.

> can it be added only for the external API, without requiring changes in the build process, internal types, etc.?

Sure 😀

**Comment by nmummau** [comment]
@bogdan-calapod this would help me too so just wondering where you're at with these changes.

**Comment by jjhbw** [comment]
This would help me as well!
I'm currently using a `.d.ts` file that I hacked together from the Flow typedefs in `types.js`, but it is less than ideal.

**Comment by mathe42** [comment]
I made a PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41901 

They merged it, now you can get types with package @types/docx-templates.

https://www.npmjs.com/package/@types/docx-templates
