### ISSUE TITLE
Stops response with cup 100%

### ISSUE THREAD

**Issue by yzhou88** [guigrpa/docx-templates#72]
[stop-response-with-cup100%.docx](https://github.com/guigrpa/docx-templates/files/3235089/stop-response-with-cup100.docx)

Try above, it never returns:
const createReport = require('docx-templates');
createReport({
        template: template_file_name,
        output: output_file,
        //cmdDelimiter: '+++',
        data: {trucking:null},
      }

**Comment by guigrpa** [comment]
Thanks for the reporting! It should be fixed in the next release
