### ISSUE TITLE
Nested repeat never returns, and cpu is 100%

### ISSUE THREAD

**Issue by yzhou88** [guigrpa/docx-templates#74]
Put the  following code in one table row, and it never return
+++FOR x in aa+++
+++FOR y in $x.data +++

put +++END-FOR x+++ +++END-FOR y+++ in the next cell row.

The key here is: nested repeat cannot be in the same row.

**Comment by guigrpa** [comment]
I don't quite understand what you're trying to accomplish with these loops. In any case:

1. Make sure loops are nested correctly:

```
+++FOR x...+++
+++FOR y in $x...+++
+++END-FOR y+++
+++END-FOR x+++
```

2. Try putting `END-FOR`s in different rows. They generate no output, so you should be fine.
