### ISSUE TITLE
Performance for large amounts of Reports

### ISSUE THREAD

**Issue by nikeee** [guigrpa/docx-templates#75]
Thans for this awesome templating library.

In our current project, we are generating a log of reports from the same templates. Is there any way to speed up the process? We're already passing the same constant ZIP file buffer to the `createReport` method. Looking at the code, it seems that it unpacks and parses the ZIP file contents in-menory on every report generation. 

Is there a way to cache this step, as the template is constant?

**Comment by guigrpa** [comment]
I'm not sure which part of docx-templates may be causing the performance hit in your use case — would you care to provide some broad profiling information? For instance, how long it takes in your case to run the various processing steps? Please also feel free to propose simple perf improvements to the codebase!

**Comment by saknarak** [comment]
I have same problem.
I found sandbox is the root cause.
when use 
```
noSandbox: true,
```
It extremely fast.

**Comment by jjhbw** [comment]
Thanks for writing this up. I haven't formally tested this, but it makes perfect sense that disabling the sandbox leads to a significant performance improvement in this case.

I have added a brief note to the README regarding the performance and security implications of `noSandbox`.
