### ISSUE TITLE
Use of alias in header

### ISSUE THREAD

**Issue by joelgiaufer** [guigrpa/docx-templates#76]
Hi and thanks for your work.
I'm trying to use aliases on header but looks like it's not working. I've the "Unknown alias" error.
Is there a way to use alias in headers and/or footer ?
Thanks in advance for your answer.
Joël

**Comment by guigrpa** [comment]
Maybe you're defining aliases in headers/footers and then using them in the document body? I'm afraid that's not supported (internally, headers/footers are separate files from the body…).

**Comment by guigrpa** [comment]
As a workaround, you can define them in the body (as well) — they will not generate any text in the output reports, so this approach should be fine.

**Comment by guigrpa** [comment]
(Oh, and defining aliases in a header/footer and using it in *the same* header/footer should be fine — please tell me if it isn't!)
