### ISSUE TITLE
Is there a way to install this manually on the browser

### ISSUE THREAD

**Issue by DoctorEaker** [guigrpa/docx-templates#77]
I'm wondering if there is a build for docx-templates that can be used on the browser and I can install manually without the need to use Browserify or Webpack.

Thanks a lot...

**Comment by vdechef** [comment]
There is none. But maybe you could make one ? I would be interested in this.

**Comment by jjhbw** [comment]
The simplest approach would be to just minify and pack the library once and include it as a static asset on your site.

Maybe i'll get around to building a minified and bundled version on a CDN some day, but for now  i'm afraid i'll have to scope it out considering there are issues with higher priority.

**Comment by fpuga** [comment]
Just for those failing here, i think the easiest approach for this is run `yarn build` from the browserify example.

```
git clone https://github.com/guigrpa/docx-templates
cd docx-templates/examples/example-browserify
yarn install
yarn build
# The file public/docx-templates.js can be imported in a script tag and used with `docxTemplates.createReport`
```
