### ISSUE TITLE
styles not working at all when injecting HTML to template

### ISSUE THREAD

**Issue by f4z3k4s** [guigrpa/docx-templates#78]
I have tried to inject the following HTML pieces to my template:

```
+++HTML `
<body>
  <style>h3{ color: red; }</style>
  <h3>
    <strong>${a.b}</strong>
  </h3>
</body>
`+++
```

and I also tried injecting:

```
+++HTML `
<body>
  <h3 style="color: red;">
    <strong>${a.b}</strong>
  </h3>
</body>
`+++
```

and I also tried:

```
+++HTML `
<body>
  <strong style="color: red;">${a.b}</strong>
</body>
`+++
```

and none of them seems to add the appropriate styling to the output file. The variable (a.b) on the other hand is correctly replaced. I only want to use HTML templates instead of INS because of the ability to style the output. Do you have any idea why does this not work?

**Comment by vdechef** [comment]
This is working for me : 
`
<meta charset="UTF-8"><body><p><span style="color: rgb(230, 0, 0);">test red text</span></p></body>
`

**Comment by f4z3k4s** [comment]
Your example works. I just pasted what I copied here in the examples and those also seem to work now. Probably I messed something up. Thank you.
