### ISSUE TITLE
Error template.

### ISSUE THREAD

**Issue by Nuadire** [guigrpa/docx-templates#79]
Error in Microsoft Word:
Word found unreadable content in "(filename).docx". Do you want to recover the contents of this document? If you trust the source of this document, click Yes.

If I remove the insertion of the picture, the error disappears.
Also, if I remove the frame with the page number in the footer, the error also disappears.

example: http://plnkr.co/edit/VO6WvAWEkzYMJwDb?p=preview

**Comment by bogdan-calapod** [comment]
I also get this error.

My Word document looks like this:

```
+++INS `${name} ${surname}`+++
+++IMAGE getDummyImage()+++
```

And my JS snippet looks like this:

```
import createReport from 'docx-templates'

createReport({
  template: 'src/template.docx',
  output: 'out.docx',
  data: {
    name: 'test',
    surname: 'test2'
  },
  additionalJsContext: {
    getDummyImage: () => ({
      data:
      'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAh1BMVEUAAAAxd71AfcQxd70yhsUyeL4xeL4zfsMxeL0yeL4xeL4wesExfcQxeb4xeb4yeb8xeL4xecAxeL4xeL0xeL4xeL4xeb8xesAxeMAwe8UxeL4yeb8xer8yeb8yeb4ye8Eyeb8yeb8xesAxeMIxeL4yeb0xd7wzfcYze8M0f8kyecAxeL41gs16QFhpAAAAJnRSTlMA+wP4CNhaEfLdwh8L76ed6zvl1My7ajIpGeCVhGRRIrV3RTZ9ZT8pRf8AAAE9SURBVCjPTZHZmoMgDEaBMO5bW221+zJDCPT9n28CeOG50pyE/HwIRgmR37pDAefpd46/TKof90jWe4cElzyaWG+e5CAipaf9LhkldPUF4GYia4wBhNM60xEgtVV36Q/WB3POY/1uHY7Z0oTpG3hpgC5RVN99JsR1FiqkQGmkL2qu775jLeq2E1opLZrSsqEji/6gxDwg96wLw1l9EItQfNrfPQvcpzCBFQtuzQiMxYTjxNKd00WmsDFdEGTADLG+DE4auwUhipPk6fJnQzlGsfPGF7NqdKLRTaOj+PCAffPHhigehYMQUKuAVqGWqFBK7LVYqV/5OnIjXo8/r91jqU9ZX7QsEiMCryFXtIVBwjKIFBgsG2mcc16CTyIlbokFE16X2nyTrHOEzjuLZMvjNrP4XKdyGA7P6zvF+wdaYR+WPYBj2gAAAABJRU5ErkJggg==',
      extension: 'png'
    })
  }
})
```

**Comment by guigrpa** [comment]
@bogdan-calapod Could you please try with `extension: '.png'`? Notice the dot.

**Comment by guigrpa** [comment]
@Nuadire Could you please try with the same `+++IMAGE customerid_account.entityimage+++` in the body, instead of the header? Does the error go away?

In any case, I think @bogdan-calapod's and @Nuadire's issues are unrelated.

**Comment by bogdan-calapod** [comment]
> @bogdan-calapod Could you please try with `extension: '.png'`? Notice the dot.

Seems to work just fine with the dot 👍

**Comment by guigrpa** [comment]
@Nuadire It's a bit strange. I copied the contents of the frame footer, deleted the frame, recreated the frame, pasted in the contents (page number, etc.) and the template now works.

I'm not sure what's happening, but I suggest modifying the template as a workaround.
