### ISSUE TITLE
Large memory usage with 15MB JSON file and fairly complex template

### ISSUE THREAD

**Issue by bogdan-calapod** [guigrpa/docx-templates#81]
With a fairly large and complex JSON file as a data source input and a complex template, the script fails with an Out-Of-Memory error.

I admit that this is more or less what I expect to be a pretty rare edge-case.

**🚚 Platforms tested**

* Windows Server 2019
* Windows 10 build 19H1
* Ubuntu Server 18.04

All running with NodeJS v12.7.0

**🤷‍♂️ What I've tried**

* Increasing the memory limit of node (`--max_old_space_size=7098`) up to 7 GB - uses up all the memory and then fails
* Increasing the memory limit to a huge amount (12GB) and running with a large swap file

**🔀 Current workarounds**

I'm using `docx-templates` to generate a report with multiple sections.

* One workable workaround is splitting the template into multiple files and merging them later - I am generating a PDF in the end, so a PDF merge after converting the docx files works for me.
* Another workaround seems to be using a large enough swap (I tried with 12GB) and a large enough Node memory limit (also 12GB). It worked fine, with memory use peaking at around 9 GB.

**❓ Possible causes**

I haven't managed to look into the code, but I suspect that all the processing is done in-memory. I think somehow streaming the file and saving it to disk as soon as possible could work.

I am open to tips on how to investigate this and help further. I can provide a template and a JSON file, but only privately (as they do contain partially private information). I'll try to replicate with a file that I can share publicly.

**Comment by JacobReynolds** [comment]
Hey @bogdan-calapod, unfortunately I don't have a bunch of info here, but I was able to reproduce this issue on a similar project I'm working on. I was able to solve it by setting the `noSandbox` flag to `true` when calling `createReport`. Hope this helps you out!

**Comment by jjhbw** [comment]
Thanks for writing this up. I haven't formally tested this, but it makes perfect sense that disabling the sandbox leads to a significant improvement in memory use in this case.

I have added a brief note to the README regarding the performance and security implications of `noSandbox`.
