### ISSUE TITLE
HTML template is not filled

### ISSUE THREAD

**Issue by simsieg** [guigrpa/docx-templates#84]
I tried out `docx-templates@3.1.1` to fill the `htmls.docx` example, but the resulting document does not show the promised paragraphs.

### Input Document
Downloaded [here](https://github.com/guigrpa/docx-templates/blob/master/packages/docx-templates/src/__tests__/fixtures/htmls.docx)

I am running Node v10.16.3.

### Code
```js
const createReport = require('docx-templates').default;

createReport({
  template: 'templates/htmls.docx',
  output: 'reports/result.docx',
  data: {}
});
```

### Output Document

![image](https://user-images.githubusercontent.com/23526306/63866852-301cc980-c9b4-11e9-8082-a65bfce8a9d4.png)

Can you reproduce this behavior?

**Comment by jjhbw** [comment]
I could not reproduce this with the new `4.0.0` release. I think it may have gotten fixed while porting to TypeScript. I have verified the soundness of the unit test that uses `htmls.docx` just to be sure.

Note that i've removed the template-as-filesystem path API. Paths now need to be provided as buffers.

Be sure to let me know if this issue persists.
