### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by preethamnagesh8** [guigrpa/docx-templates#86]
Hi, I am trying to use docx-templates with angular. I have used the code below:
`import createReport from 'docx-templates';

        createReport({
			template: 'assets/s1.docx',
			output: 'reports/myReport.docx',
			data: {
				name: 'John',
				surname: 'Appleseed',
			},
		});
`

But its throwing up multiple errors as:

`ERROR in ./node_modules/graceful-fs/polyfills.js
Module not found: Error: Can't resolve 'constants' in 'some_path\node_modules\graceful-fs'
ERROR in ./node_modules/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'fs' in 'some_path\node_modules\fs-extra\lib\empty'
ERROR in ./node_modules/graceful-fs/fs.js
Module not found: Error: Can't resolve 'fs' in 'some_path\node_modules\graceful-fs'
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'some_path\node_modules\graceful-fs'
ERROR in ./node_modules/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in 'some_path\node_modules\jsonfile'
ERROR in ./node_modules/fs-extra/lib/util/utimes.js
Module not found: Error: Can't resolve 'os' in 'some_path\node_modules\fs-extra\lib\util'
ERROR in ./node_modules/docx-templates/lib/processTemplate.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\docx-templates\lib'
ERROR in ./node_modules/fs-extra/lib/copy/copy.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\copy'
ERROR in ./node_modules/fs-extra/lib/copy/ncp.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\copy'
ERROR in ./node_modules/fs-extra/lib/copy-sync/copy-sync.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\copy-sync'
ERROR in ./node_modules/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\empty'
ERROR in ./node_modules/fs-extra/lib/ensure/symlink-paths.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/ensure/file.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/ensure/link.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/ensure/symlink.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/json/output-json-sync.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\json'
ERROR in ./node_modules/fs-extra/lib/json/output-json.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\json'
ERROR in ./node_modules/fs-extra/lib/mkdirs/win32.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\mkdirs'
ERROR in ./node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\mkdirs'
ERROR in ./node_modules/fs-extra/lib/mkdirs/mkdirs.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\mkdirs'
ERROR in ./node_modules/fs-extra/lib/move/index.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\move'
ERROR in ./node_modules/fs-extra/lib/move-sync/index.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\move-sync'
ERROR in ./node_modules/fs-extra/lib/output/index.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\output'
ERROR in ./node_modules/fs-extra/lib/remove/rimraf.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\remove'
ERROR in ./node_modules/fs-extra/lib/util/utimes.js
Module not found: Error: Can't resolve 'path' in 'some_path\node_modules\fs-extra\lib\util'
ERROR in ./node_modules/docx-templates/lib/debug.js
Module not found: Error: Can't resolve 'storyboard' in 'some_path\node_modules\docx-templates\lib'
ERROR in ./node_modules/docx-templates/lib/debug.js
Module not found: Error: Can't resolve 'storyboard-listener-console' in 'some_path\node_modules\docx-templates\lib'
ERROR in ./node_modules/docx-templates/lib/jsSandbox.js
Module not found: Error: Can't resolve 'vm' in 'some_path\node_modules\docx-templates\lib'`

Please help me in resolving this issue.

**Comment by jjhbw** [comment]
This seems like an issue with your build pipeline. I'm afraid I can't really help here.

Docx-templater version 4.0 will have a simplified entrypoint which will likely make it work better with the likes of Webpack and other compilers. We'll release 4.0 soon. You can subscribe to releases if you're interested.
