### ISSUE TITLE
Zip errors when using with Vue CLI

### ISSUE THREAD

**Issue by nmummau** [guigrpa/docx-templates#88]
I have a Vue CLI project that I'm having trouble implementing this package into.
I followed the instructions but I'm now getting this error when I try to call the `createReport` method. I'm thinking something with Vue CLI and/or webpack is not playing nice. 

`./frontend/src/reports/templates/TemplateName.docx` is my template.

`./frontend/src/reports/docxtemplates.js` is this:
```
const createReport = require('docx-templates').default;
createReport({
	template: './frontend/src/reports/templates/TemplateName.docx',
	data: {
		name: 'John',
		surname: 'Appleseed'
	}
});
```

When I call `createReport` I get this error: 
```
zipEntries.js?4c22:168 Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at ZipEntries.readEndOfCentral (zipEntries.js?4c22:168)
    at ZipEntries.load (zipEntries.js?4c22:256)
    at eval (load.js?bc8e:49)
```

**Comment by vdechef** [comment]
If I understand correctly, you are using docx-templates inside a Vue project. So your code runs in a browser. As you provide your template as a local path, your browser cannot access it. You have to load the file first into a buffer, then provide this buffer to createReport().  
To read a file from browser, you must use an <input> tag, otherwiser you won't be able to create a File object.

**Comment by nmummau** [comment]
Is there is no way to include the template .docx file in the project so that the browser can access it? I'm trying to get my Vue component to load some data, and then when the clicks a button, I want to generate the output .docx file and download it to the user. The user won't know what the template looks like; I don't want to require they upload the template to an input tag.

**Comment by vdechef** [comment]
You can embed the template as a base64 string in a js constant. Or you can put it in the project's assets. Or you can put it in your public folder on the backend and load it through an ajax request.

**Comment by jjhbw** [comment]
This seems like more of a question related to the build pipeline of your project. What @vdechef says is accurate and his suggestion seems to me like the best approach.
