### ISSUE TITLE
Extract all the variables from the word document

### ISSUE THREAD

**Issue by cesarve77** [guigrpa/docx-templates#90]
First thanks and congratulation for this great package

What is the best way to extract all the variables (in dot notation for example) from the word document.

My idea is build the query based in the variables asked in the docx.

Thanks in advance

**Comment by mathe42** [comment]
Interesting question... Maybe use https://www.npmjs.com/package/textract anderen then search with regex

**Comment by wildhart** [comment]
I've come up with an inefficient solution to this, but imo there should be an easier way.

Since the `data` object can be a promise-returning function, I would expect this to work:
```
report = await createReport({
	template,
	cmdDelimiter: ['[', ']'],
	data: function(query) {
		console.log('field:', query);
		return new Promise((resolve, reject) => resolve('hello'));
	},
});
```
But in the `data` function `query` is always undefined.  My templates have fields like `[ProjectNumber]`

Why doesn't this work?

Here's my solution which does work, by catching the error in a loop:
```
const data = {};
let report = null;
do {
	try {
		report = await createReport({
			template,
			cmdDelimiter: ['[', ']'],
			data,
			// USE ONLY IN THE BROWSER, AND WITH TRUSTED TEMPLATES
			noSandbox: true, // WARNING: INSECURE
		});
		import('file-saver').then(FileSaver => FileSaver.saveAs(new Blob([report]), res.name+'.done.docx'));
	} catch(e) {
		const m = e.toString().match(/INS (\w+)/);
		if (m) {
			data[m[1]] = m[1];
			console.log('new field:', m[1]);
		}
		else throw e;
	}
} while (!report);
console.log(Object.keys(data)); // this is a list of the fields!
```
PS - @cesarve77 please can you edit the title of this issue to something like `[question] get list of fields` so people have more chance of finding it.

**Comment by mathe42** [comment]
Maybe you also can use a Proxy object in a first run. And getting the requestet fields...

**Comment by wildhart** [comment]
I tried a Proxy object but that didn't work.  I think internally docx-templates is using something like `Object.keys(data)` to get a list of fields in the data object because it doesn't even try `proxy.get()` on fields which don't already exists.

**Comment by wildhart** [comment]
FYI, the alternative module [docxtemplater](https://github.com/open-xml-templating/docxtemplater) handles this really easily with its `nullgetter` setting:  https://docxtemplater.readthedocs.io/en/latest/configuration.html#nullgetter in which `part.value` is the field name.

**Comment by bulolo** [comment]
i also need to  extract all the variables from docx.
is there any good way to parse the template-docx whitch can auto extract it self.

**Comment by jjhbw** [comment]
I was planning on implementing something like this. I'll let you know when i've gotten around to it.

**Comment by bulolo** [comment]
any progress？

**Comment by bernardohmr** [comment]
I hope someone shows up with this solution soon also (=

**Comment by jjhbw** [comment]
Added this feature in https://github.com/guigrpa/docx-templates/releases/tag/v4.3.0

**Comment by bulolo** [comment]
how to use?


let res = await this.$http.get('static/template2.docx', {
        responseType: 'arraybuffer'
      });
      const commands = await listCommands(res.data, ['{', '}']);
      console.log('commands', commands)

![image](https://user-images.githubusercontent.com/10026498/86245216-beb53500-bbdb-11ea-9d4d-09791599c696.png)

**Comment by Arend-dev** [comment]
Hi there,

When trying to use listCommands, I always get an error:

"...\node_modules\jszip\lib\utils.js:454
                new Error("Can't read the data of '" + name + "'. Is it " +
                ^

Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?"

Do not know what I am doing wrong.

**Comment by jjhbw** [comment]
@Arend-dev Please make a new issue for stuff like this.

I can't do much without seeing your code. First off, can you verify that you are using it correctly by checking the suggestion in the error message (see below)?
`...Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?`

The unhandled rejections flag should have little to do with it.
