### ISSUE TITLE
Deactivate EXEC, QUERY

### ISSUE THREAD

**Issue by sebastian-schlecht** [guigrpa/docx-templates#92]
Hey @guigrpa ,

thanks for the library! We are intending to process user-generated templates. Is it possible to disable certain commands like EXEC or QUERY?

Thanks

**Comment by vdechef** [comment]
Do you need this for security purposes ?

**Comment by mathe42** [comment]
@sebastian-schlecht Have a look at the vm2 example might help you. See also https://www.npmjs.com/package/vm2

**Comment by sebastian-schlecht** [comment]
@mathe42 thanks, stumbled into this a while back. I think this can be closed then.
