### ISSUE TITLE
Could not find out how many pages i have

### ISSUE THREAD

**Issue by drizzef** [guigrpa/docx-templates#94]
Hi, 
first of all, thank's for great library!
I'm trying to find out how many pages do I have but I don't have any indication for page break tag or app.xml file with properties.

Also, i would like to know if there any chance that there is any global function or post-process function that can print the document properties(number of pages, author, etc..) into the document itself.

Thank's!

**Comment by mathe42** [comment]
You can use other packages like https://www.npmjs.com/package/docx-pdf-pagecount

**Comment by jjhbw** [comment]
Interesting. I'll log this as a `feature request`. Thanks for recommending `docx-pdf-pagecount`! I'll see if I can integrate something like that later on.

**Comment by jjhbw** [comment]
See https://github.com/guigrpa/docx-templates/releases/tag/v4.4.0.

Let me know if I missed something!
